| **Inicio** | **atrás 9** | **Siguiente 11** |
|----------- |-------------- |---------------|
| [🏠](../../README.md) | [⏪](./9_Arrays_de_Numpy.ipynb)| [⏩](./11_Numpy_Union_y_Separacion_de_Arrays.ipynb)|

# **10. Numpy: Agregación y Ejes de Arrays (arreglos) para Procesar Datos con Python**

## **Introducción a los Ejes y Funciones de Agregación**

Los ejes y las funciones de agregación son conceptos fundamentales en NumPy que te permiten realizar operaciones en arrays multidimensionales y obtener resultados resumidos. Vamos a explorar en detalle qué son los ejes, cómo funcionan y cómo utilizar las funciones de agregación en NumPy, utilizando ejemplos para ilustrar cada concepto.

**Ejes en Arrays Multidimensionales:**

En NumPy, los ejes son las dimensiones a lo largo de las cuales se realizan operaciones. En un array bidimensional, el primer eje suele representar las filas y el segundo eje las columnas. En arrays tridimensionales y superiores, los ejes adicionales representan dimensiones adicionales.

**Funciones de Agregación en NumPy:**

Las funciones de agregación son operaciones que toman un conjunto de valores y generan un único valor resumido basado en esos valores. Algunos ejemplos son la suma, el promedio, el máximo y el mínimo.

**Ejemplos de Uso de Ejes y Funciones de Agregación:**

In [1]:
import numpy as np

# Crear una matriz de ejemplo
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Suma de todos los elementos en la matriz
suma_total = np.sum(matriz)
print("Suma total:", suma_total)  # Output: 45

# Suma de elementos a lo largo del primer eje (filas)
suma_filas = np.sum(matriz, axis=0)
print("Suma por filas:", suma_filas)  # Output: [12 15 18]

# Suma de elementos a lo largo del segundo eje (columnas)
suma_columnas = np.sum(matriz, axis=1)
print("Suma por columnas:", suma_columnas)  # Output: [ 6 15 24]

# Valor máximo en la matriz
maximo_valor = np.max(matriz)
print("Máximo valor:", maximo_valor)  # Output: 9

# Valor mínimo por filas
minimo_filas = np.min(matriz, axis=0)
print("Mínimo por filas:", minimo_filas)  # Output: [1 2 3]

# Promedio por columnas
promedio_columnas = np.mean(matriz, axis=1)
print("Promedio por columnas:", promedio_columnas)  # Output: [2. 5. 8.]

# Producto acumulado por filas
producto_acumulado_filas = np.cumprod(matriz, axis=0)
print("Producto acumulado por filas:\n", producto_acumulado_filas)
# Output: [[ 1  2  3]
#          [ 4 10 18]
#          [28 80 162]]

Suma total: 45
Suma por filas: [12 15 18]
Suma por columnas: [ 6 15 24]
Máximo valor: 9
Mínimo por filas: [1 2 3]
Promedio por columnas: [2. 5. 8.]
Producto acumulado por filas:
 [[  1   2   3]
 [  4  10  18]
 [ 28  80 162]]


En estos ejemplos, estamos utilizando funciones de agregación como `np.sum`, `np.max`, `np.min`, `np.mean` y `np.cumprod` junto con el parámetro `axis` para especificar a lo largo de qué eje se deben realizar las operaciones. El parámetro `axis` permite controlar cómo se agrupan los datos para calcular el resultado deseado.

En resumen, comprender cómo trabajar con ejes y funciones de agregación en NumPy es esencial para analizar datos multidimensionales de manera efectiva y resumirlos en formas útiles. Estas herramientas son útiles tanto para cálculos básicos como para análisis más avanzados de datos.

## **Función de agregación: min, max, argmin, argmax, sum y mean**

Por supuesto, estaré encantado de proporcionarte una explicación detallada sobre las funciones de agregación `min`, `max`, `argmin`, `argmax`, `sum` y `mean` en NumPy, junto con ejemplos para ilustrar cada una de estas funciones.

**Función `min` y `max`:**

Estas funciones devuelven el valor mínimo y máximo de un array, respectivamente.

In [2]:
import numpy as np

arr = np.array([3, 8, 1, 5, 9, 2])

min_value = np.min(arr)
max_value = np.max(arr)

print("Valor mínimo:", min_value)  # Output: 1
print("Valor máximo:", max_value)  # Output: 9

Valor mínimo: 1
Valor máximo: 9


**Función `argmin` y `argmax`:**

Estas funciones devuelven el índice del valor mínimo y máximo en un array, respectivamente.

In [3]:

arr = np.array([3, 8, 1, 5, 9, 2])

argmin_index = np.argmin(arr)
argmax_index = np.argmax(arr)

print("Índice del valor mínimo:", argmin_index)  # Output: 2 (índice del valor 1)
print("Índice del valor máximo:", argmax_index)  # Output: 4 (índice del valor 9)

Índice del valor mínimo: 2
Índice del valor máximo: 4


**Función `sum`:**

La función `sum` calcula la suma de los elementos en un array.

In [4]:

arr = np.array([3, 8, 1, 5, 9, 2])

sum_result = np.sum(arr)

print("Suma de elementos:", sum_result)  # Output: 28

Suma de elementos: 28


**Función `mean`:**

La función `mean` calcula el promedio de los elementos en un array.

In [5]:
arr = np.array([3, 8, 1, 5, 9, 2])

mean_result = np.mean(arr)

print("Promedio de elementos:", mean_result)  # Output: 4.666666666666667

Promedio de elementos: 4.666666666666667


Estas funciones de agregación son herramientas esenciales en NumPy para realizar cálculos resumidos en arrays. Son útiles para obtener información estadística sobre los datos y para realizar operaciones de agregación en conjuntos de datos más grandes. Recuerda que puedes usar el argumento `axis` para calcular estas funciones a lo largo de ejes específicos en arrays multidimensionales.

## **Función de agregación por Eje (Axis)**

Por supuesto, estaré encantado de proporcionarte una explicación detallada sobre cómo utilizar la función de agregación por eje (axis) en NumPy, junto con ejemplos para ilustrar su funcionamiento.

**Funciones de Agregación por Eje en NumPy:**

En NumPy, muchas funciones de agregación (como `sum`, `min`, `max`, `mean`, etc.) pueden calcular sus resultados a lo largo de un eje específico en arrays multidimensionales. Esto es especialmente útil cuando trabajas con datos en forma de matrices, donde cada eje tiene su propia interpretación (por ejemplo, filas y columnas).

**Ejemplos de Funciones de Agregación por Eje:**

In [7]:
import numpy as np

# Crear una matriz de ejemplo
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Suma de elementos a lo largo del primer eje (filas)
suma_filas = np.sum(matriz, axis=0)
print("Suma por filas:", suma_filas)  # Output: [12 15 18]

# Suma de elementos a lo largo del segundo eje (columnas)
suma_columnas = np.sum(matriz, axis=1)
print("Suma por columnas:", suma_columnas)  # Output: [ 6 15 24]

# Valor mínimo por filas
minimo_filas = np.min(matriz, axis=0)
print("Mínimo por filas:", minimo_filas)  # Output: [1 2 3]

# Valor máximo por columnas
maximo_columnas = np.max(matriz, axis=1)
print("Máximo por columnas:", maximo_columnas)  # Output: [3 6 9]

# Promedio por columnas
promedio_columnas = np.mean(matriz, axis=0)
print("Promedio por columnas:", promedio_columnas)  # Output: [4. 5. 6.]

# Producto acumulado por filas
producto_acumulado_filas = np.cumprod(matriz, axis=1)
print("Producto acumulado por filas:\n", producto_acumulado_filas)
# Output: [[  1   2   6]
#          [  4  20 120]
#          [  7  56 504]]

Suma por filas: [12 15 18]
Suma por columnas: [ 6 15 24]
Mínimo por filas: [1 2 3]
Máximo por columnas: [3 6 9]
Promedio por columnas: [4. 5. 6.]
Producto acumulado por filas:
 [[  1   2   6]
 [  4  20 120]
 [  7  56 504]]


En estos ejemplos, estamos utilizando varias funciones de agregación (`np.sum`, `np.min`, `np.max`, `np.mean`, `np.cumprod`) junto con el argumento `axis` para especificar a lo largo de qué eje deben realizarse las operaciones. El valor `axis` permite controlar cómo se agrupan los datos para calcular el resultado deseado.

Recuerda que el uso correcto del argumento `axis` es esencial para obtener los resultados esperados al realizar funciones de agregación en arrays multidimensionales.

| **Inicio** | **atrás 9** | **Siguiente 11** |
|----------- |-------------- |---------------|
| [🏠](../../README.md) | [⏪](./9_Arrays_de_Numpy.ipynb)| [⏩](./11_Numpy_Union_y_Separacion_de_Arrays.ipynb)|