| **Inicio** | **atrás 10** | **Siguiente 12** |
|----------- |-------------- |---------------|
| [🏠](../../README.md) | [⏪](./10_arreglos_en_numpy.ipynb)| [⏩](./12_Funciones_Universales.ipynb)|

# **11. Numpy: Unión y Separación de Arrays (arreglos) para Procesar Datos con Python**

## **Introducción a la Unión y Separación de Arrays**

Con gusto te proporcionaré una explicación detallada sobre cómo unir y separar arrays en NumPy, junto con ejemplos para ilustrar cada uno de estos conceptos.

**Unión de Arrays en NumPy:**

Unir arrays en NumPy se refiere a combinar dos o más arrays en uno solo. Existen varias formas de realizar la unión, dependiendo de si estamos trabajando con arrays unidimensionales o multidimensionales.

**Unión de Arrays Unidimensionales:**

Para unir arrays unidimensionales, podemos usar la función `np.concatenate`, que toma una secuencia de arrays como argumento y los concatena a lo largo de un eje especificado (por defecto, es el primer eje).

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Unir arrays unidimensionales
resultado = np.concatenate((arr1, arr2))
print("Unión de arrays:", resultado)  # Output: [1 2 3 4 5 6]

Unión de arrays: [1 2 3 4 5 6]


**Unión de Arrays Multidimensionales:**

Para unir arrays multidimensionales, nuevamente usamos `np.concatenate`, pero esta vez especificamos el eje a lo largo del cual queremos unir los arrays.

In [2]:
matriz1 = np.array([[1, 2],
                    [3, 4]])
matriz2 = np.array([[5, 6]])

# Unir matrices a lo largo del primer eje (filas)
resultado_matriz = np.concatenate((matriz1, matriz2))
print("Unión de matrices:\n", resultado_matriz)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]]

Unión de matrices:
 [[1 2]
 [3 4]
 [5 6]]


**Separación de Arrays en NumPy:**

La separación de arrays se refiere a dividir un array en varios arrays más pequeños. NumPy proporciona la función `np.split` para lograr esto. Esta función acepta el array que deseas dividir y una lista de índices o secciones donde deseas realizar las divisiones.

**Separación de Arrays Unidimensionales:**

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Separar array en tres partes
partes = np.split(arr, 3)
print("Partes separadas:", partes)  # Output: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

Partes separadas: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


**Separación de Arrays Multidimensionales:**

In [4]:
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Separar matriz en tres partes a lo largo del primer eje (filas)
partes_matriz = np.split(matriz, 3)
print("Partes separadas:\n", partes_matriz)
# Output:
# [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

Partes separadas:
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


En resumen, unir y separar arrays en NumPy te permite manipular y organizar datos de manera efectiva. Puedes utilizar estas operaciones para combinar o dividir arrays según tus necesidades de análisis de datos.

## **Apilar arrays con Stack**

Apilar arrays con la función `np.stack` en NumPy te permite combinar varios arrays en un solo array multidimensional a lo largo de un nuevo eje. Esta función es útil cuando necesitas combinar múltiples conjuntos de datos en un formato más amplio y estructurado. Aquí tienes una explicación detallada junto con ejemplos para comprender cómo funciona el apilamiento de arrays con `np.stack`.

**Función `np.stack` para Apilar Arrays:**

La función `np.stack` toma una secuencia de arrays y un argumento `axis` que especifica el nuevo eje a lo largo del cual se apilarán los arrays. Esta función crea un nuevo array multidimensional al apilar los arrays a lo largo del eje especificado.

**Ejemplo de Apilamiento de Arrays:**

Supongamos que tienes dos arrays unidimensionales y quieres apilarlos a lo largo de un nuevo eje para crear un array bidimensional.

In [5]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Apilar arrays unidimensionales a lo largo de un nuevo eje (eje 0)
apilado = np.stack((arr1, arr2), axis=0)
print("Arrays apilados:\n", apilado)
# Output:
# [[1 2 3]
#  [4 5 6]]

Arrays apilados:
 [[1 2 3]
 [4 5 6]]


En este ejemplo, hemos creado dos arrays unidimensionales `arr1` y `arr2`. Luego, utilizamos la función `np.stack` para apilar estos arrays a lo largo del nuevo eje 0 (filas) para obtener un array bidimensional.

**Ejemplo de Apilamiento de Arrays Multidimensionales:**

Supongamos que tienes dos matrices y deseas apilarlas a lo largo de un nuevo eje.

In [6]:
matriz1 = np.array([[1, 2],
                    [3, 4]])
matriz2 = np.array([[5, 6],
                    [7, 8]])

# Apilar matrices a lo largo de un nuevo eje (eje 0)
apilado_matrices = np.stack((matriz1, matriz2), axis=0)
print("Matrices apiladas:\n", apilado_matrices)
# Output:
# [[[1 2]
#   [3 4]]
#
#  [[5 6]
#   [7 8]]]

Matrices apiladas:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


En este caso, hemos apilado las matrices `matriz1` y `matriz2` a lo largo del nuevo eje 0 (filas), creando un nuevo array tridimensional.

En resumen, la función `np.stack` en NumPy te permite combinar arrays en un solo array multidimensional a lo largo de un nuevo eje especificado. Esto es útil para organizar conjuntos de datos relacionados en una estructura más grande y manejable.

## **Separar arrays con Split**

Por supuesto, con gusto te proporcionaré una explicación detallada sobre cómo separar arrays con la función `np.split` en NumPy, junto con ejemplos para ilustrar su funcionamiento.

**Función `np.split` para Separar Arrays:**

La función `np.split` en NumPy se utiliza para dividir un array en múltiples subarrays a lo largo de un eje específico. Puedes proporcionar una lista de índices o secciones donde deseas realizar las divisiones.

**Ejemplo de Separación de Arrays Unidimensionales:**

Supongamos que tienes un array unidimensional y deseas dividirlo en tres partes.

In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Separar array en tres partes
partes = np.split(arr, 3)
print("Partes separadas:", partes)
# Output: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

Partes separadas: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


En este ejemplo, hemos utilizado la función `np.split` para dividir el array `arr` en tres partes de igual tamaño.

**Ejemplo de Separación de Arrays Multidimensionales:**

Supongamos que tienes una matriz y deseas separarla en dos submatrices a lo largo del primer eje (filas).

In [12]:
import numpy as np

matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Dividir matriz en dos partes a lo largo del primer eje (filas)
partes_matriz = np.array_split(matriz, 2, axis=0)
print("Partes separadas:\n", partes_matriz)


Partes separadas:
 [array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]])]


En este ejemplo, hemos utilizado la función `np.split` para separar la matriz `matriz` en dos submatrices a lo largo del primer eje (filas).

**Ejemplo de Separación de Arrays con Índices Específicos:**

Puedes proporcionar una lista de índices en los cuales deseas realizar las divisiones utilizando el argumento `indices_or_sections`.

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Separar array en índices 2 y 5
partes_indices = np.split(arr, [2, 5])
print("Partes separadas por índices:", partes_indices)
# Output: [array([1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])]

Partes separadas por índices: [array([1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])]


En este ejemplo, hemos utilizado la función `np.split` para dividir el array `arr` en tres partes en los índices 2 y 5.

En resumen, la función `np.split` en NumPy te permite dividir arrays en subarrays según los índices o secciones que especifiques. Esta función es útil para segmentar y organizar datos en conjuntos más manejables.

| **Inicio** | **atrás 10** | **Siguiente 12** |
|----------- |-------------- |---------------|
| [🏠](../../README.md) | [⏪](./10_arreglos_en_numpy.ipynb)| [⏩](./12_Funciones_Universales.ipynb)|