| **Inicio** | **atrás 7** | **Siguiente 9** |
|----------- |-------------- |---------------|
| [🏠](../../README.md) | [⏪](./7_Manejo_de_Datos_Faltantes.ipynb)| [⏩](./9_Arrays_de_Numpy.ipynb)|

# **8. Procesamiento de Datos con Numpy en Python: Operaciones vectoriales con Arrays ó Arreglos**

## **Introducción a los Arreglos de Numpy**

Los arreglos (arrays) de NumPy son una estructura fundamental en la biblioteca NumPy de Python, diseñada para manejar eficientemente datos numéricos y realizar operaciones matemáticas en ellos. Los arreglos de NumPy son similares a las listas de Python, pero tienen muchas ventajas adicionales, como operaciones vectorizadas y mejor rendimiento en cálculos numéricos. Aquí tienes una explicación detallada junto con ejemplos sobre los arreglos de NumPy.

**Instalación y Importación de NumPy:**

Antes de comenzar, asegúrate de tener NumPy instalado. Si no lo tienes instalado, puedes instalarlo usando el siguiente comando:

```
pip install numpy
```

Luego, puedes importar NumPy en tu código:

In [1]:
import numpy as np

**Creación de Arreglos:**

Puedes crear arreglos de NumPy utilizando varias funciones. Algunas de las formas más comunes son:

1. **Desde una Lista o Tupla:**

In [2]:
lista = [1, 2, 3, 4, 5]
arreglo = np.array(lista)
print(arreglo)

[1 2 3 4 5]


2. **Arreglo de Ceros o Unos:**

In [3]:
arreglo_ceros = np.zeros(5)
arreglo_unos = np.ones(3)
print(arreglo_ceros)
print(arreglo_unos)

[0. 0. 0. 0. 0.]
[1. 1. 1.]


3. **Arreglo Secuencial:**

In [4]:
arreglo_secuencial = np.arange(0, 10, 2)  # Del 0 al 9, saltando de 2 en 2
print(arreglo_secuencial)

[0 2 4 6 8]


4. **Arreglo Espaciado Linealmente:**

In [5]:
arreglo_espaciado = np.linspace(0, 1, 5)  # Espaciado lineal entre 0 y 1 en 5 valores
print(arreglo_espaciado)

[0.   0.25 0.5  0.75 1.  ]


**Operaciones con Arreglos:**

Una de las características clave de los arreglos de NumPy son las operaciones vectorizadas, que permiten realizar operaciones en cada elemento del arreglo sin necesidad de bucles explícitos.

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

suma = a + b
producto = a * b
promedio = np.mean(a)

print("Suma:", suma)
print("Producto:", producto)
print("Promedio:", promedio)

Suma: [5 7 9]
Producto: [ 4 10 18]
Promedio: 2.0


**Indexación y Rebanado:**

Puedes acceder a elementos individuales en un arreglo utilizando la indexación. Los índices en Python comienzan desde 0.

In [7]:
arreglo = np.array([10, 20, 30, 40, 50])
print(arreglo[2])  # Acceder al tercer elemento (índice 2)

30


También puedes utilizar la rebanada para acceder a porciones de un arreglo.

In [8]:
print(arreglo[1:4])  # Elementos del índice 1 al 3

[20 30 40]


**Forma y Dimensiones:**

Un arreglo de NumPy tiene una propiedad "shape" que muestra sus dimensiones.

In [9]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz.shape)  # Muestra (2, 3), que significa 2 filas y 3 columnas

(2, 3)


Estos son solo conceptos básicos sobre arreglos de NumPy. NumPy ofrece una amplia gama de funcionalidades para manipular, operar y analizar datos numéricos de manera eficiente. Los arreglos de NumPy son ampliamente utilizados en análisis de datos, machine learning y muchas otras aplicaciones numéricas en Python debido a su eficiencia y versatilidad.

## **Creación de Arreglos**

La creación de arreglos en NumPy es una parte fundamental de trabajar con esta biblioteca. Los arreglos NumPy son utilizados para almacenar datos numéricos de manera eficiente y realizar operaciones matemáticas en ellos. Aquí te mostraré diferentes formas de crear arreglos en NumPy con ejemplos detallados:

**1. Desde Listas o Tuplas:**

Puedes crear un arreglo NumPy directamente desde una lista o tupla de Python.

In [10]:
import numpy as np

lista = [1, 2, 3, 4, 5]
arreglo = np.array(lista)
print(arreglo)

[1 2 3 4 5]


**2. Arreglos de Ceros o Unos:**

Puedes crear arreglos de ceros o unos con tamaños específicos utilizando las funciones `np.zeros()` y `np.ones()`.

In [11]:
arreglo_ceros = np.zeros(5)
arreglo_unos = np.ones(3)
print(arreglo_ceros)
print(arreglo_unos)

[0. 0. 0. 0. 0.]
[1. 1. 1.]


**3. Arreglos Secuenciales:**

La función `np.arange()` permite crear un arreglo con valores secuenciales.

In [12]:
arreglo_secuencial = np.arange(0, 10, 2)  # Del 0 al 9, saltando de 2 en 2
print(arreglo_secuencial)

[0 2 4 6 8]


**4. Arreglos Espaciados Linealmente:**

La función `np.linspace()` crea un arreglo con valores espaciados linealmente entre un rango.

In [13]:
arreglo_espaciado = np.linspace(0, 1, 5)  # Espaciado lineal entre 0 y 1 en 5 valores
print(arreglo_espaciado)

[0.   0.25 0.5  0.75 1.  ]


**5. Matrices Identidad:**

La función `np.eye()` permite crear matrices identidad (matrices cuadradas con unos en la diagonal principal y ceros en el resto).

In [14]:
matriz_identidad = np.eye(3)  # Matriz identidad de tamaño 3x3
print(matriz_identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**6. Arreglos Aleatorios:**

Puedes generar arreglos con valores aleatorios utilizando `np.random`.

In [15]:
arreglo_aleatorio = np.random.rand(4)  # Arreglo de 4 valores aleatorios entre 0 y 1
print(arreglo_aleatorio)

[0.96590824 0.11322262 0.26953857 0.25138728]


**7. Arreglos Personalizados:**

Puedes crear arreglos personalizados utilizando una función de mapeo.

In [16]:
funcion_personalizada = lambda x: x**2
arreglo_personalizado = np.fromfunction(funcion_personalizada, (5,))
print(arreglo_personalizado)

[ 0.  1.  4.  9. 16.]


Estos son solo algunos ejemplos de las muchas formas en que puedes crear arreglos en NumPy. Cada función tiene sus propias particularidades y opciones para personalizar la creación del arreglo. Los arreglos NumPy son fundamentales en el análisis numérico y científico en Python debido a su eficiencia y versatilidad en operaciones matemáticas y manipulación de datos.

## **Tipos de datos de Arrays y la implicación del tamaño del dato**

En NumPy, una de las bibliotecas más utilizadas en Python para el cálculo científico y computacional, los arrays son la estructura de datos principal para almacenar y manipular datos. Los tipos de datos en los arrays de NumPy son importantes ya que afectan la forma en que los datos se almacenan en memoria y cómo se realizan las operaciones en esos datos.

NumPy ofrece varios tipos de datos predefinidos, y el tamaño del dato tiene implicaciones significativas en términos de consumo de memoria, precisión numérica y rendimiento. Vamos a explorar los tipos de datos más comunes y cómo el tamaño del dato puede influir en el uso de la memoria y las operaciones.

Los tipos de datos más utilizados en NumPy son:

1. **int**:

 Representa números enteros. Puede tener diferentes tamaños, como `int8`, `int16`, `int32`, y `int64`, que indican la cantidad de bits utilizados para representar el número. Un `int8` utiliza 8 bits (1 byte), mientras que un `int64` utiliza 64 bits (8 bytes).

2. **float**:

 Representa números de punto flotante (números reales). Al igual que con los enteros, puedes encontrar diferentes tamaños como `float16`, `float32`, y `float64`, que indican la cantidad de bits utilizados para la representación. Por ejemplo, un `float32` utiliza 32 bits (4 bytes) para representar el número.

3. **complex**:

 Representa números complejos con parte real e imaginaria. Los tamaños son similares a los de los tipos `float` (por ejemplo, `complex64` y `complex128`).

Vamos a ver un ejemplo práctico utilizando diferentes tipos de datos y analizando su impacto en el consumo de memoria:

In [1]:
import numpy as np

# Crear arrays de diferentes tipos de datos
arr_int32 = np.array([1, 2, 3], dtype=np.int32)
arr_float32 = np.array([1.0, 2.0, 3.0], dtype=np.float32)
arr_complex64 = np.array([1 + 2j, 3 + 4j], dtype=np.complex64)

# Obtener el tamaño en bytes de cada array
print("Tamaño de arr_int32:", arr_int32.nbytes, "bytes")
print("Tamaño de arr_float32:", arr_float32.nbytes, "bytes")
print("Tamaño de arr_complex64:", arr_complex64.nbytes, "bytes")

Tamaño de arr_int32: 12 bytes
Tamaño de arr_float32: 12 bytes
Tamaño de arr_complex64: 16 bytes


En este ejemplo, estamos creando arrays con diferentes tipos de datos y analizando su tamaño en bytes utilizando el atributo `nbytes`. Observarás que el tamaño del dato afecta directamente el consumo de memoria. Los números enteros de 32 bits (`int32`) consumen más memoria que los números enteros de 8 bits (`int8`), y lo mismo ocurre con los tipos `float` y `complex`.

En resumen, la elección del tipo de dato adecuado en NumPy es importante para optimizar el uso de memoria y la precisión numérica en tus cálculos. Debes considerar el rango de valores que necesitas representar y el equilibrio entre precisión y consumo de memoria.

## **Share (figura) de los arreglos**

En NumPy, el término "shape" se refiere a las dimensiones y tamaños de un array. El shape de un array especifica la cantidad de elementos a lo largo de cada dimensión. En otras palabras, es una tupla de números enteros que describe el tamaño de cada eje en un array multidimensional.

Para entender mejor qué es el shape de un array en NumPy, consideremos algunos ejemplos:

In [2]:
import numpy as np

# Crear un array unidimensional (vector)
arr1 = np.array([1, 2, 3, 4, 5])
print("Shape de arr1:", arr1.shape)  # Output: (5,)

# Crear un array bidimensional (matriz)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape de arr2:", arr2.shape)  # Output: (2, 3)

# Crear un array tridimensional
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Shape de arr3:", arr3.shape)  # Output: (2, 2, 2)

Shape de arr1: (5,)
Shape de arr2: (2, 3)
Shape de arr3: (2, 2, 2)


En estos ejemplos, el shape de `arr1` es `(5,)`, lo que significa que es un array unidimensional con 5 elementos a lo largo del primer eje. El shape de `arr2` es `(2, 3)`, lo que indica que es una matriz con 2 filas y 3 columnas. El shape de `arr3` es `(2, 2, 2)`, lo que indica que es un array tridimensional con 2 elementos a lo largo de cada uno de los tres ejes.

Es importante tener en cuenta que el shape de un array está relacionado con su estructura y organización en memoria. El shape determina la cantidad de elementos en cada dimensión, y esa información es crucial para realizar operaciones matriciales, broadcasting y otras manipulaciones de arrays.

Puedes modificar el shape de un array utilizando el método `reshape` de NumPy. Esto te permite cambiar la organización de los elementos sin cambiar los datos subyacentes:

In [3]:
# Crear un array unidimensional
arr = np.array([1, 2, 3, 4, 5, 6])

# Cambiar el shape a una matriz de 2x3
reshaped_arr = arr.reshape(2, 3)
print("Shape de reshaped_arr:", reshaped_arr.shape)  # Output: (2, 3)

Shape de reshaped_arr: (2, 3)


En este ejemplo, estamos reorganizando el array unidimensional `arr` en una matriz de 2 filas y 3 columnas utilizando el método `reshape`.

En resumen, el shape de un array en NumPy describe su estructura y tamaño en términos de dimensiones. Entender el shape es fundamental para trabajar eficientemente con arrays multidimensionales y realizar cálculos matriciales y operaciones de broadcasting de manera efectiva.

## **Métodos y operaciones básicas sobre Arreglos**

En NumPy, los métodos y operaciones básicas sobre arrays son esenciales para realizar manipulaciones y cálculos en los datos de manera eficiente. Vamos a explorar algunas de las operaciones y métodos más comunes que puedes realizar con arrays en NumPy.

**Creación de Arrays:**

Puedes crear arrays en NumPy de varias formas, incluyendo listas de Python y funciones dedicadas de creación de arrays, como `np.zeros`, `np.ones`, y `np.arange`.

In [4]:
import numpy as np

# Crear un array a partir de una lista
arr1 = np.array([1, 2, 3, 4, 5])

# Crear un array de ceros
arr_zeros = np.zeros((2, 3))  # Matriz de 2x3 con elementos 0

# Crear un array de unos
arr_ones = np.ones((3, 3))  # Matriz de 3x3 con elementos 1

# Crear un array de valores en un rango
arr_range = np.arange(0, 10, 2)  # Array con valores 0, 2, 4, 6, 8

**Operaciones Aritméticas:**

NumPy permite realizar operaciones aritméticas de manera eficiente elemento a elemento en arrays.

In [5]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

# Suma
sum_result = arr_a + arr_b  # [5, 7, 9]

# Resta
sub_result = arr_b - arr_a  # [3, 3, 3]

# Multiplicación
mul_result = arr_a * arr_b  # [4, 10, 18]

# División
div_result = arr_b / arr_a  # [4.0, 2.5, 2.0]

**Funciones Universales (ufuncs):**

NumPy proporciona funciones universales (ufuncs) que aplican operaciones matemáticas a todos los elementos de un array.

In [6]:
arr = np.array([1, 2, 3, 4])

# Funciones ufuncs
sqrt_arr = np.sqrt(arr)  # Raíz cuadrada
exp_arr = np.exp(arr)  # Exponencial
sin_arr = np.sin(arr)  # Seno
cos_arr = np.cos(arr)  # Coseno

**Indexación y Rebanado (Slicing):**

Puedes acceder y manipular elementos específicos de un array utilizando indexación y rebanado.

In [7]:
arr = np.array([10, 20, 30, 40, 50])

# Acceso a elementos individuales
element = arr[2]  # 30

# Rebanado (slicing)
slice_arr = arr[1:4]  # [20, 30, 40]

**Operaciones de Agregación:**

NumPy permite realizar operaciones de agregación, como calcular la suma, promedio, mínimo y máximo de un array.

In [8]:
arr = np.array([10, 20, 30, 40, 50])

# Suma
sum_arr = np.sum(arr)  # 150

# Promedio
mean_arr = np.mean(arr)  # 30.0

# Mínimo
min_arr = np.min(arr)  # 10

# Máximo
max_arr = np.max(arr)  # 50

Estos son solo algunos ejemplos de las operaciones y métodos básicos que puedes realizar con arrays en NumPy. La biblioteca proporciona muchas más funcionalidades avanzadas para trabajar con datos numéricos, lo que la convierte en una herramienta poderosa para el análisis y cálculo científico.

## **Ejemplo básico de Operaciones Vectoriales: Índice de Masa Corporal**

Claro, aquí tienes un ejemplo básico de cómo realizar operaciones vectoriales para calcular el Índice de Masa Corporal (IMC) utilizando NumPy. El IMC es una medida comúnmente utilizada para evaluar si una persona tiene un peso saludable en relación con su altura.

Supongamos que tenemos dos arrays de NumPy: uno que contiene las alturas en metros y otro que contiene los pesos en kilogramos de varias personas. Queremos calcular el IMC para cada persona utilizando operaciones vectoriales.

In [9]:
import numpy as np

# Alturas en metros
alturas = np.array([1.65, 1.75, 1.80, 1.60, 1.70])

# Pesos en kilogramos
pesos = np.array([60, 70, 85, 50, 65])

# Calcular el IMC (peso / altura^2)
imc = pesos / (alturas ** 2)

print("Alturas:", alturas)
print("Pesos:", pesos)
print("IMC:", imc)

Alturas: [1.65 1.75 1.8  1.6  1.7 ]
Pesos: [60 70 85 50 65]
IMC: [22.03856749 22.85714286 26.2345679  19.53125    22.49134948]


En este ejemplo, estamos utilizando operaciones vectoriales para calcular el IMC para cada persona en función de sus alturas y pesos. La operación `alturas ** 2` calcula el cuadrado de cada altura, y luego dividimos los pesos entre estos valores para obtener el IMC correspondiente. El resultado es un nuevo array `imc` que contiene los valores calculados del IMC para cada persona.

Este es solo un ejemplo simple de cómo realizar operaciones vectoriales en NumPy para realizar cálculos más complejos. Las operaciones vectoriales permiten realizar cálculos eficientes en grandes conjuntos de datos y son una de las razones por las que NumPy es tan ampliamente utilizado en el análisis numérico y científico.

| **Inicio** | **atrás 7** | **Siguiente 9** |
|----------- |-------------- |---------------|
| [🏠](../../README.md) | [⏪](./7_Manejo_de_Datos_Faltantes.ipynb)| [⏩](./9_Arrays_de_Numpy.ipynb)|