# **Operaciones vectoriales con Arrays ó Arreglos**

## **1. Introducción a los Arreglos de Numpy**

Los arreglos de NumPy son estructuras de datos multidimensionales que se utilizan para almacenar y manipular datos numéricos de manera eficiente en Python. Son una parte fundamental de la biblioteca NumPy, que es una biblioteca popular para computación científica en Python.

Aquí hay un ejemplo de cómo crear un arreglo de NumPy y realizar algunas operaciones básicas en él:

In [2]:
import numpy as np

# Crear un arreglo de 1 dimensión con valores del 0 al 4
a = np.array([0, 1, 2, 3, 4])

# Crear un arreglo de 2 dimensiones con forma (2,3) con valores aleatorios
b = np.random.rand(2,3)

# Crear un arreglo de 3 dimensiones con forma (2,3,4) con valores cero
c = np.zeros((2,3,4))

# Imprimir los arreglos
print(a)
print(b)
print(c)



[0 1 2 3 4]
[[0.73697827 0.27546183 0.80495155]
 [0.6994397  0.91299537 0.05979773]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [3]:
# Acceder a un elemento del arreglo de 1 dimensión
print(a[3])

# Acceder a un elemento del arreglo de 2 dimensiones
print(b[1,2])

# Acceder a un elemento del arreglo de 3 dimensiones
print(c[1,2,3])

# Cambiar un elemento del arreglo de 1 dimensión
a[2] = 10

# Cambiar un elemento del arreglo de 2 dimensiones
b[0,1] = 5

# Cambiar un elemento del arreglo de 3 dimensiones
c[1,2,3] = 7

# Imprimir los arreglos actualizados
print(a)
print(b)
print(c)

# Realizar una operación matemática en todos los elementos del arreglo de 1 dimensión
d = 2*a
print(d)

# Realizar una operación matemática en todos los elementos del arreglo de 2 dimensiones
e = b**2
print(e)

# Realizar una operación matemática en todos los elementos del arreglo de 3 dimensiones
f = c + 3
print(f)


3
0.0597977348963471
0.0
[ 0  1 10  3  4]
[[0.73697827 5.         0.80495155]
 [0.6994397  0.91299537 0.05979773]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 7.]]]
[ 0  2 20  6  8]
[[5.43136967e-01 2.50000000e+01 6.47947001e-01]
 [4.89215899e-01 8.33560547e-01 3.57576910e-03]]
[[[ 3.  3.  3.  3.]
  [ 3.  3.  3.  3.]
  [ 3.  3.  3.  3.]]

 [[ 3.  3.  3.  3.]
  [ 3.  3.  3.  3.]
  [ 3.  3.  3. 10.]]]


## **2. Creación de Arreglos**

In [4]:
# Crear un arreglo a partir de una lista o tupla:

import numpy as np

# crear un arreglo unidimensional a partir de una lista
a = np.array([1, 2, 3, 4])
print(a)

# crear un arreglo bidimensional a partir de una lista de listas
b = np.array([[1, 2], [3, 4], [5, 6]])
print(b)

# crear un arreglo a partir de una tupla
c = np.array((1, 2, 3))
print(c)


[1 2 3 4]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3]


In [5]:
# Crear un arreglo de ceros o unos:

import numpy as np

# crear un arreglo de ceros de tamaño (3,3)
a = np.zeros((3,3))
print(a)

# crear un arreglo de unos de tamaño (2,2)
b = np.ones((2,2))
print(b)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [6]:
# Crear un arreglo con valores aleatorios:

import numpy as np

# crear un arreglo de valores aleatorios de tamaño (2,3)
a = np.random.rand(2,3)
print(a)

# crear un arreglo de valores aleatorios enteros de tamaño (3,3)
b = np.random.randint(10, size=(3,3))
print(b)


[[0.66669813 0.5564334  0.64461222]
 [0.06796009 0.17627882 0.42192931]]
[[1 8 3]
 [6 0 1]
 [5 4 2]]


In [7]:
# Crear un arreglo con valores espaciados uniformemente:

import numpy as np

# crear un arreglo de valores espaciados uniformemente entre 0 y 1
a = np.linspace(0, 1, 5)
print(a)

# crear un arreglo de valores espaciados uniformemente entre 1 y 10 con un salto de 2
b = np.arange(1, 10, 2)
print(b)


[0.   0.25 0.5  0.75 1.  ]
[1 3 5 7 9]


## **3. Tipos de datos de Arrays y la implicación del tamaño del dato**

Los tipos de datos en los arreglos de NumPy son importantes porque determinan la cantidad de memoria que se utiliza para almacenar los elementos del arreglo y la precisión de los valores que se pueden representar. Aquí hay un ejemplo de cómo los tipos de datos y el tamaño del dato pueden afectar el tamaño de la memoria utilizada por el arreglo:

In [8]:
import numpy as np

# Crear un arreglo de 1 dimensión con valores enteros de 8 bits
a = np.array([1, 2, 3], dtype=np.int8)
print(a)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)

# Crear un arreglo de 1 dimensión con valores enteros de 32 bits
b = np.array([1, 2, 3], dtype=np.int32)
print(b)
print(b.dtype)
print(b.itemsize)
print(b.nbytes)

# Crear un arreglo de 1 dimensión con valores de punto flotante de 64 bits
c = np.array([1.0, 2.0, 3.0], dtype=np.float64)
print(c)
print(c.dtype)
print(c.itemsize)
print(c.nbytes)


[1 2 3]
int8
1
3
[1 2 3]
int32
4
12
[1. 2. 3.]
float64
8
24


## **4. Share (figura) de los arreglos**

Para compartir o copiar arreglos en NumPy, es importante tener en cuenta que, por defecto, NumPy no realiza copias de los arreglos a menos que sea necesario. Esto significa que si se modifica un arreglo, también se modificarán todos los arreglos que comparten los mismos datos. Aquí hay un ejemplo de cómo compartir arreglos en NumPy:

In [9]:
import numpy as np

# Crear un arreglo de 2 dimensiones
a = np.array([[1, 2, 3], [4, 5, 6]])

# Crear una vista del arreglo original
b = a.view()

# Crear una copia del arreglo original
c = a.copy()

# Imprimir los arreglos originales y sus copias
print("Arreglo original a:")
print(a)
print("Vista del arreglo original b:")
print(b)
print("Copia del arreglo original c:")
print(c)

# Modificar un valor del arreglo original
a[0, 0] = 100

# Imprimir los arreglos modificados
print("Arreglo original a modificado:")
print(a)
print("Vista del arreglo original b modificado:")
print(b)
print("Copia del arreglo original c no modificado:")
print(c)


Arreglo original a:
[[1 2 3]
 [4 5 6]]
Vista del arreglo original b:
[[1 2 3]
 [4 5 6]]
Copia del arreglo original c:
[[1 2 3]
 [4 5 6]]
Arreglo original a modificado:
[[100   2   3]
 [  4   5   6]]
Vista del arreglo original b modificado:
[[100   2   3]
 [  4   5   6]]
Copia del arreglo original c no modificado:
[[1 2 3]
 [4 5 6]]


## **5. Métodos y operaciones básicas sobre Arreglos**

In [10]:
import numpy as np

# Crear un arreglo de 1 dimensión con valores enteros
a = np.array([1, 2, 3, 4, 5])

# Imprimir el arreglo original
print("Arreglo original:")
print(a)

# Sumar todos los elementos del arreglo
print("Suma de los elementos del arreglo:")
print(np.sum(a))

# Obtener el valor mínimo del arreglo
print("Valor mínimo del arreglo:")
print(np.min(a))

# Obtener el valor máximo del arreglo
print("Valor máximo del arreglo:")
print(np.max(a))

# Calcular la media del arreglo
print("Media del arreglo:")
print(np.mean(a))

# Calcular la desviación estándar del arreglo
print("Desviación estándar del arreglo:")
print(np.std(a))

# Añadir un valor a cada elemento del arreglo
print("Arreglo después de añadir 2 a cada elemento:")
print(a + 2)

# Multiplicar cada elemento del arreglo por un valor
print("Arreglo después de multiplicar cada elemento por 3:")
print(a * 3)

# Elevar cada elemento del arreglo a una potencia
print("Arreglo después de elevar cada elemento al cuadrado:")
print(np.power(a, 2))


Arreglo original:
[1 2 3 4 5]
Suma de los elementos del arreglo:
15
Valor mínimo del arreglo:
1
Valor máximo del arreglo:
5
Media del arreglo:
3.0
Desviación estándar del arreglo:
1.4142135623730951
Arreglo después de añadir 2 a cada elemento:
[3 4 5 6 7]
Arreglo después de multiplicar cada elemento por 3:
[ 3  6  9 12 15]
Arreglo después de elevar cada elemento al cuadrado:
[ 1  4  9 16 25]


## **6. Ejemplo básico de Operaciones Vectoriales**

In [11]:
import numpy as np

# Crear dos arreglos de 1 dimensión con valores enteros
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Sumar los dos arreglos
print("Suma de los dos arreglos:")
print(a + b)

# Restar los dos arreglos
print("Resta de los dos arreglos:")
print(a - b)

# Multiplicar los dos arreglos elemento a elemento
print("Multiplicación de los dos arreglos:")
print(a * b)

# Dividir los dos arreglos elemento a elemento
print("División de los dos arreglos:")
print(a / b)

# Calcular el producto punto de los dos arreglos
print("Producto punto de los dos arreglos:")
print(np.dot(a, b))

# Calcular el producto cruz de los dos arreglos
print("Producto cruz de los dos arreglos:")
print(np.cross(a, b))


Suma de los dos arreglos:
[5 7 9]
Resta de los dos arreglos:
[-3 -3 -3]
Multiplicación de los dos arreglos:
[ 4 10 18]
División de los dos arreglos:
[0.25 0.4  0.5 ]
Producto punto de los dos arreglos:
32
Producto cruz de los dos arreglos:
[-3  6 -3]
