# **Arrays de Numpy: Búsqueda y Filtrado de Datos**

## **1. Introducción a las búsquedas y filtros en Numpy**

NumPy ofrece varias funciones para realizar búsquedas y filtros en arreglos. Estas funciones permiten buscar elementos específicos en un arreglo, filtrar elementos basados en ciertas condiciones y seleccionar subconjuntos de datos. Aquí hay un ejemplo de cómo realizar búsquedas y filtros en NumPy:

In [1]:
import numpy as np

# Crear un arreglo de 1 dimensión con valores enteros
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Buscar el índice de un elemento específico en el arreglo
print("El índice del elemento 5 es:")
print(np.where(a == 5))

# Filtrar elementos mayores que 5 en el arreglo
print("Elementos mayores que 5 en el arreglo:")
print(a[a > 5])

# Seleccionar subconjuntos de datos basados en una condición
print("Elementos pares en el arreglo:")
print(a[a % 2 == 0])

# Aplicar una función a cada elemento del arreglo
print("Arreglo después de aplicar la función cuadrática:")
print(np.vectorize(lambda x: x**2)(a))


El índice del elemento 5 es:
(array([4]),)
Elementos mayores que 5 en el arreglo:
[ 6  7  8  9 10]
Elementos pares en el arreglo:
[ 2  4  6  8 10]
Arreglo después de aplicar la función cuadrática:
[  1   4   9  16  25  36  49  64  81 100]


## **2. Búsquedas con Where**

La función ```where()``` de NumPy se utiliza para buscar elementos en un arreglo que cumplan una cierta condición. Aquí hay un ejemplo de cómo utilizar ```where()``` para realizar una búsqueda en un arreglo de 2 dimensiones:

In [3]:
import numpy as np

# Crear un arreglo de 2 dimensiones con valores enteros
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Buscar los índices de los elementos que son mayores que 5
indices = np.where(a > 5)

# Imprimir los índices y los valores correspondientes
print("Índices de los elementos mayores que 5:")
print(indices)
print("Valores de los elementos mayores que 5:")
print(a[indices])


Índices de los elementos mayores que 5:
(array([1, 2, 2, 2]), array([2, 0, 1, 2]))
Valores de los elementos mayores que 5:
[6 7 8 9]


## **3. Filtrado de elementos**

En NumPy, se pueden filtrar elementos de un arreglo basados en ciertas condiciones utilizando la notación de indexado booleano. Aquí hay un ejemplo de cómo utilizar la notación de indexado booleano para filtrar elementos en un arreglo:

In [4]:
import numpy as np

# Crear un arreglo de 1 dimensión con valores enteros
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Filtrar los elementos mayores que 5 en el arreglo
filtro = a > 5
print("Elementos mayores que 5 en el arreglo:")
print(a[filtro])


Elementos mayores que 5 en el arreglo:
[ 6  7  8  9 10]


## **4. Ejemplo de filtrado con vectores Pesos, Alturas y Países**

Supongamos que tenemos tres arreglos de NumPy pesos, alturas y paises que contienen información sobre el peso, altura y país de una lista de personas. Podemos utilizar la notación de indexado booleano para filtrar las personas de cierto país con una altura mayor a cierto valor.

In [5]:
import numpy as np

# Arreglos de ejemplo con información sobre peso, altura y país
pesos = np.array([70, 80, 65, 75, 72, 68, 90, 83, 79, 81])
alturas = np.array([1.75, 1.80, 1.65, 1.70, 1.72, 1.68, 1.90, 1.83, 1.79, 1.81])
paises = np.array(['Argentina', 'Brasil', 'Colombia', 'Argentina', 'Argentina', 'Colombia', 'Brasil', 'Brasil', 'Colombia', 'Argentina'])

# Filtrar personas de Argentina con altura mayor a 1.75 metros
filtro = (paises == 'Argentina') & (alturas > 1.75)
print("Personas de Argentina con altura mayor a 1.75 metros:")
print("Pesos:", pesos[filtro])
print("Alturas:", alturas[filtro])
print("Países:", paises[filtro])


Personas de Argentina con altura mayor a 1.75 metros:
Pesos: [81]
Alturas: [1.81]
Países: ['Argentina']


## **5. Filtrando información con operadores booleanos "and" y "or"**

En NumPy, se pueden utilizar operadores booleanos ```and``` y ```or``` para filtrar información basada en múltiples condiciones. Aquí hay un ejemplo de cómo usar estos operadores para filtrar información de un arreglo:

In [6]:
import numpy as np

# Crear un arreglo de 1 dimensión con valores enteros
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Filtrar los elementos mayores que 5 y menores que 8 en el arreglo
filtro = (a > 5) & (a < 8)
print("Elementos mayores que 5 y menores que 8 en el arreglo:")
print(a[filtro])

# Filtrar los elementos menores que 3 o mayores que 7 en el arreglo
filtro = (a < 3) | (a > 7)
print("Elementos menores que 3 o mayores que 7 en el arreglo:")
print(a[filtro])


Elementos mayores que 5 y menores que 8 en el arreglo:
[6 7]
Elementos menores que 3 o mayores que 7 en el arreglo:
[ 1  2  8  9 10]
