# **Numpy: Unión y Separación de Arrays (arreglos) para Procesar Datos**

## **1. Introducción a la Unión y Separación de Arrays**

In [1]:
import numpy as np

# Crear dos arreglos de 1 dimensión
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Unir los dos arreglos en uno solo
c = np.concatenate((a, b))
print("Unión de los dos arreglos:")
print(c)

# Apilar los dos arreglos en una nueva dimensión
d = np.stack((a, b))
print("Apilamiento de los dos arreglos en una nueva dimensión:")
print(d)

# Unir los dos arreglos en uno solo a lo largo del segundo eje
e = np.hstack((a, b))
print("Unión de los dos arreglos a lo largo del segundo eje:")
print(e)

# Unir los dos arreglos en uno solo a lo largo del primer eje
f = np.vstack((a, b))
print("Unión de los dos arreglos a lo largo del primer eje:")
print(f)

# Separar un arreglo en tres partes iguales
g = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
h = np.split(g, 3)
print("Separación del arreglo en tres partes iguales:")
print(h)


Unión de los dos arreglos:
[1 2 3 4 5 6]
Apilamiento de los dos arreglos en una nueva dimensión:
[[1 2 3]
 [4 5 6]]
Unión de los dos arreglos a lo largo del segundo eje:
[1 2 3 4 5 6]
Unión de los dos arreglos a lo largo del primer eje:
[[1 2 3]
 [4 5 6]]
Separación del arreglo en tres partes iguales:
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


## **2. Explicación del contexto del Ejemplo**

El siguiente ejemplo es una simulación sencilla de un juego de dados en Python utilizando la biblioteca Numpy. En el juego, se lanzan dos dados y se suman los valores obtenidos en cada lanzamiento. El objetivo es predecir cuál será el resultado de la suma de los dados en cada lanzamiento.

En el ejemplo, se crean dos arreglos de Numpy de una dimensión (uno para cada dado) que contienen los valores posibles de cada dado (1 al 6). Luego, se utiliza la función ```random.choice()``` de Numpy para simular el lanzamiento de cada dado en cada turno y se suman los valores obtenidos para obtener la puntuación total.

Se realiza un total de 10 lanzamientos y se guarda el resultado de cada lanzamiento en un arreglo de Numpy. Finalmente, se utiliza la función ```where()``` de Numpy para comparar los resultados obtenidos con una predicción y se imprime el número de aciertos. Este ejemplo muestra cómo se pueden utilizar arreglos de Numpy y algunas de sus funciones para realizar simulaciones sencillas y procesar los datos resultantes.

## **3. Apilar arrays con Stack**

In [2]:
import numpy as np

# Crear dos arreglos de Numpy de una dimensión
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Apilar horizontalmente los dos arreglos
hstacked = np.hstack((arr1, arr2))
print("Apilado horizontal:\n", hstacked)

# Apilar verticalmente los dos arreglos
vstacked = np.vstack((arr1, arr2))
print("Apilado vertical:\n", vstacked)


Apilado horizontal:
 [1 2 3 4 5 6]
Apilado vertical:
 [[1 2 3]
 [4 5 6]]


## **4. Separar arrays con Split**

In [3]:
import numpy as np

# Crear un arreglo de Numpy unidimensional
arr = np.array([1, 2, 3, 4, 5, 6])

# Separar el arreglo en dos sub-arreglos de igual longitud
split_arr = np.split(arr, 2)
print("Sub-arreglo 1:", split_arr[0])
print("Sub-arreglo 2:", split_arr[1])


Sub-arreglo 1: [1 2 3]
Sub-arreglo 2: [4 5 6]
