| **Inicio** | **Siguiente 2** |
|----------- |-------------- |
| [🏠](../../README.md) | [⏩](./2_Pandas.ipynb)|

# **Numpy**

Numpy es el paquete fundamental para computación científica en Python y manejo de arrays numéricos multi-dimensionales.

`pip install numpy`

La forma más común de importar esta librería es usar el alias `np`:

`import numpy as np`

## **ndarray**

En el núcleo de Numpy está el `ndarray`, donde `nd` es por n-dimensional. Un ndarray es un array multidimensional de elementos del mismo tipo.

Aquí tenemos una diferencia fundamental con las listas en Python que pueden mantener objetos heterogéneos. Y esta característica propicia que el rendimiento de un ndarray sea bastante mejor que el de una lista convencional.

Para crear un array podemos usar:

In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [2]:
type(x)

numpy.ndarray

Si queremos obtener información sobre el array creado, podemos acceder a distintos atributos del mismo:

In [3]:
x.ndim # dimensión

1

In [4]:
x.size # tamaño total del array

5

In [5]:
x.shape # forma

(5,)

In [6]:
x.dtype # tipo de sus elementos

dtype('int64')

## **Datos heterogéneos**

Hemos dicho que los ndarray son estructuras de datos que almacenan un único tipo de datos. A pesar de esto, es posible crear un array con los siguientes valore:

In [7]:
x = np.array([4, 'Einstein', 1e-7])

Aunque, a prioro, puede parecer que estamos mezclando tipos enteros, flotantes y cadenas de texto, lo que realmente se produce (de forma implícita) es una coerción de tipos **Unicode**:

In [8]:
x

array(['4', 'Einstein', '1e-07'], dtype='<U32')

In [9]:
x.dtype

dtype('<U32')

## **Tipos de datos**

Numpy maneja gran cantidad de tipos de datos. A diferencia de los tipos de datos numéricos en Python que no establecen un tamaño de bytes de almacenamiento, aquí sí hay una diferencia clara.

Algunos de los tipos de datos numéricos en Numpy se presentan en la siguiente tabla:

| **dtype** | **Descripción** | **Rango** |
|--- |--- |--- |
| np.int32 | Integer | De -2147483648 a 2147483647 |
| np.int64 | Integer | De -9223372036854775808 a 9223372036854775807|
|np.uint32|Unsigned integer|De 0 a 4294967295|
|np.uint64|Unsigned integer|De 0 a 18446744073709551615|
|np.float32|Float|De -3.4028235e+38 a 3.4028235e+38|
|np.float64|Float|De -1.7976931348623157e+308 a 1.7976931348623157e+308|

> **Truco**
>
> Numpy entiende por defecto que `int` hace referencia a `np.int64` y que `float` hace referencia a `np.float64`. Estos son alias bastante utilizados.


Si creamos un array de números enteros, el tipo de datos por defecto será `int64`:

In [10]:
a = np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a.dtype

dtype('int64')

Sin embargo podemos especificar el tipo de datos que nos interese:

In [12]:
b = np.array(range(10), dtype = 'int32') # 'int32' hace referencia a np.int32
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [13]:
b.dtype

dtype('int32')

Lo mismo ocurre con valores flotantes, donde `float64` es el tipo de datos por defecto.

Es posible convertir el tipo de datos que almacena un array mediante el método `astype`.

Por ejemplo:

In [14]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
c = a.astype(float)
c.dtype

dtype('float64')

## **ndarray vs list**

Como ya se ha comentado en la intoducción de esta sección, el uso de `ndarray` frente a `list` está justificado por cuestiones de rendimiento. Pero veamos un ejemplo clarificador en el que sumamos 10 millones de valores enteros:

In [17]:
array_as_list = list(range(int(10e6)))
array_as_ndarray = np.array(array_as_list)

In [18]:
%timeit sum(array_as_list)

287 ms ± 26.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [19]:
%timeit array_as_ndarray.sum()

32.4 ms ± 8.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


> **Nota:**
>
> El cómputo es casi 12 veces más rápido utilizando ndarray frente a listas clásicas.


En cualquier caso, existe la posibilidad de convertir a lista cualquier ndarray mediante el método `tolist()`:

In [20]:
a = np.array([10, 20, 30])
a

array([10, 20, 30])

In [21]:
b = a.tolist()
b

[10, 20, 30]

In [22]:
type(b)

list

## **Matrices**

Una matriz no es más que un array bidimensional. Como ya se ha comentado, Numpy provee `ndarray` que se comporta como un array multidimensional con lo que podríamos crear una matriz sin mayor problema.

Veamos un ejemplo en el que tratamos de construir la siguiente matriz:

\begin{equation*}
M =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
10 & 11 & 12
\end{bmatrix}
\end{equation*}

Nos apoyamos en una lista de listas para la creación de la matriz:

In [24]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
M

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
M.ndim # bidimensional

2

In [26]:
M.size

12

In [27]:
M.shape # 4 filas x 3 columnas

(4, 3)

In [28]:
M.dtype

dtype('int64')

> **Ejercicio**

Cree los siguientes arrays en Numpy:

\begin{equation*}
array1 =
\begin{bmatrix}
88 & 23 & 39 & 41
\end{bmatrix}
\end{equation*}

\begin{equation*}
array2 =
\begin{bmatrix}
76.4 & 21.7 & 38.4 \\
41.2 & 52.8 & 68.9
\end{bmatrix}
\end{equation*}

\begin{equation*}
array3 =
\begin{bmatrix}
12 \\
4 \\
9 \\
8
\end{bmatrix}
\end{equation*}

Obtenga igualmente las siguientes características de cada uno de ellos: dimensión, tamaño, forma y tipo de sus elementos.

In [29]:
import numpy as np

# Crear los arrays
array1 = np.array([88, 23, 39, 41])

array2 = np.array([[76.4, 21.7, 38.4],
                   [41.2, 52.8, 68.9]])

array3 = np.array([[12],
                   [4],
                   [9],
                   [8]])

# Obtener las características de cada array
dim1 = array1.ndim  # Dimensión
size1 = array1.size  # Tamaño
shape1 = array1.shape  # Forma
dtype1 = array1.dtype  # Tipo de elementos

dim2 = array2.ndim
size2 = array2.size
shape2 = array2.shape
dtype2 = array2.dtype

dim3 = array3.ndim
size3 = array3.size
shape3 = array3.shape
dtype3 = array3.dtype

# Imprimir las características de cada array
print("Array1:")
print("Dimensión:", dim1)
print("Tamaño:", size1)
print("Forma:", shape1)
print("Tipo de elementos:", dtype1)
print("\n")

print("Array2:")
print("Dimensión:", dim2)
print("Tamaño:", size2)
print("Forma:", shape2)
print("Tipo de elementos:", dtype2)
print("\n")

print("Array3:")
print("Dimensión:", dim3)
print("Tamaño:", size3)
print("Forma:", shape3)
print("Tipo de elementos:", dtype3)

Array1:
Dimensión: 1
Tamaño: 4
Forma: (4,)
Tipo de elementos: int64


Array2:
Dimensión: 2
Tamaño: 6
Forma: (2, 3)
Tipo de elementos: float64


Array3:
Dimensión: 2
Tamaño: 4
Forma: (4, 1)
Tipo de elementos: int64


## **Cambiando la forma**

Dado un array, podemos cambiar su forma mediante la funcion `np.reshape()`:

In [30]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
np.reshape(a, (3, 4)) # 3 x 4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Si sólo queremos especificar un número determinado de filas o columnas, podemos dejar la otra dimensión a -1:

In [31]:
np.reshape(a, (6, -1)) # 6 filas

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [32]:
np.reshape(a, (-1, 3)) # 3 columnas

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

> **Advertencia**
>
> En el caso de que no exista posibilidad de cambiar la forma del array por el número de filas y/o columnas especificado, obtendremos un error de tipo `ValueError: cannot reshape array`.

## **Almacenando arrays**

Es posible que nos interese almacenar (de forma persistente) los arrays que hemos ido creando. Para ello Numpy nos provee, al menos, de dos mecanismos:

### **Almacenamiento en forma binario propio**

Mediante el método `save()` podemos guardar la estructura de datos en `ficheros.npy`. Veamos un ejemplo:

In [33]:
M

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
np.save('my_matrix', M)

In [35]:
!ls my_matrix.npy

my_matrix.npy


In [36]:
M_reloaded = np.load('my_matrix.npy')

In [37]:
M_reloaded

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### **Almacenamiento en formato de texto plano**

Numpy proporciona el metodo `savetxt()` con el que podremos volcar la estructura de datos a un fichero de texto csv. Veamos un ejemplo:

In [38]:
M

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
np.savetxt('my_matrix.csv', M, fmt='%d')

In [40]:
!cat my_matrix.csv

1 2 3
4 5 6
7 8 9
10 11 12


In [41]:
M_reloaded = np.loadtxt('my_matrix.csv', dtype = int)

In [42]:
M_reloaded

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

> **Truco**
>
> Por defecto el almacenamiento y la carga de arrays en formato texto usa tipos de datos flotantes.
>
> Es por ello que hemos usado el parámetro `fmt` en el almacenamiento y el parámetro `dtype` en la carga.

Es posible cargar un array desempaquetando sus valores a través del parámetro `unpack`. En el siguiente ejemplo separamos las columnas en tres variables diferentes:

In [43]:
M

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
col1, col2, col3 = np.loadtxt('my_matrix.csv', unpack=True, dtype=int)

In [45]:
col1

array([ 1,  4,  7, 10])

In [46]:
col2

array([ 2,  5,  8, 11])

In [47]:
col3

array([ 3,  6,  9, 12])

## **Funciones predefinidas para creación de arrays**

Numpy ofrece una gran variedad de funciones predefinidas para creación de arrays que nos permiten simplificar el proceso de construcción de este tipo de estructuras de datos.

### **Valores fijos**

A continuación veremos una serie de funciones para crear arrays con valores fijos.

**CEROS**

In [48]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Por defecto, ésta y otras funciones del estilo, devuelven valores flotantes. Si quisiéramos trabajar con valores enteros basta con usar el parámetro `dtype`:

In [49]:
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Existe la posibilidad de crear un array de ceros con las mismas dimensiones (y forma) que otro array:

In [50]:
M = np.array([[1, 2, 3], [4, 5, 6]])
M

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.zeros_like(M)

array([[0, 0, 0],
       [0, 0, 0]])

Lo cual sería equivalente a pasar la forma del array a la función predefinida de creación de ceros:

In [52]:
np.zeros(M.shape, dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

**UNOS**

In [53]:
np.ones((3, 4)) # también existe np.ones_like()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**MISMO VALOR**

In [54]:
np.full((3, 4), 7) # También existe np.full_Like()

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

**MATRIZ IDENTIDAD**

In [55]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**MATRIZ DIAGONAL**

In [56]:
np.diag([5, 4, 3, 2, 1])

array([[5, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

>**Ejercicio**

Cree la siguiente matriz mediante código Python:

\begin{equation*}
diagonal =
\begin{pmatrix}
1 & 0 & 0 & \cdots & 0\\
0 & 1 & 0 & \cdots & 0\\
0 & 0 & 2 & \cdots & 0\\
\vdots & \vdots & 0 & \ddots & 0\\
0 & 0 & 0 & \cdots & 49
\end{pmatrix}
\end{equation*}

Obtenga igualmente las siguientes caracteristicas de cada uno de ellos: dimensión, tamaño, forma y tipo de sus elementos.

In [57]:
import numpy as np

# Definir la dimensión de la matriz
dimension = 50  # Cambia este valor según tus necesidades

# Crear la matriz diagonal
diagonal = np.diag(np.arange(1, dimension + 1))

# Obtener las características de la matriz diagonal
dim = diagonal.ndim  # Dimensión
size = diagonal.size  # Tamaño
shape = diagonal.shape  # Forma
dtype = diagonal.dtype  # Tipo de elementos

# Imprimir las características de la matriz diagonal
print("Matriz Diagonal:")
print("Dimensión:", dim)
print("Tamaño:", size)
print("Forma:", shape)
print("Tipo de elementos:", dtype)

Matriz Diagonal:
Dimensión: 2
Tamaño: 2500
Forma: (50, 50)
Tipo de elementos: int64


## **Valores equiespaciados**

A continuación veremos una serie de funciones para crear arrays con valores equiespaciados o en intervalos definidos.

### **Valores Enteros Equiespacidos**

La función que usamos para este propósito es `np.arange()` cuyo comportamiento es totalmente análogo a la función built-in `range()`.

**Especificando Límite superior:**

In [58]:
np.arange(21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

**Especificando límite inferior y superior:**

In [59]:
np.arange(6, 60)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59])

**Especificando límite inferior, superior y paso:**

In [60]:
np.arange(6, 60, 3)

array([ 6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54,
       57])

Es posible especificar una paso flotante en función `arange()`:

In [61]:
np.arange(6, 16, .3)

array([ 6. ,  6.3,  6.6,  6.9,  7.2,  7.5,  7.8,  8.1,  8.4,  8.7,  9. ,
        9.3,  9.6,  9.9, 10.2, 10.5, 10.8, 11.1, 11.4, 11.7, 12. , 12.3,
       12.6, 12.9, 13.2, 13.5, 13.8, 14.1, 14.4, 14.7, 15. , 15.3, 15.6,
       15.9])

## **Valores Flotantes Equiespacidos**

La función que usamos para este propósito es `np.linspace()` cuyo comportamiento es similar a `np.arange()` pero para valores flotantes.

**Especificando límite inferior y superior:**

In [62]:
np.linspace(6, 60) # [6, 60] con 50 valores

array([ 6.        ,  7.10204082,  8.20408163,  9.30612245, 10.40816327,
       11.51020408, 12.6122449 , 13.71428571, 14.81632653, 15.91836735,
       17.02040816, 18.12244898, 19.2244898 , 20.32653061, 21.42857143,
       22.53061224, 23.63265306, 24.73469388, 25.83673469, 26.93877551,
       28.04081633, 29.14285714, 30.24489796, 31.34693878, 32.44897959,
       33.55102041, 34.65306122, 35.75510204, 36.85714286, 37.95918367,
       39.06122449, 40.16326531, 41.26530612, 42.36734694, 43.46938776,
       44.57142857, 45.67346939, 46.7755102 , 47.87755102, 48.97959184,
       50.08163265, 51.18367347, 52.28571429, 53.3877551 , 54.48979592,
       55.59183673, 56.69387755, 57.79591837, 58.89795918, 60.        ])

>**Nota**
>
> Por defecto `np.linspace()` genera 50 elementos.

**Especificando límite inferior, superior y total de elementos:**

In [63]:
np.linspace(6, 60, 20) # [6, 60] con 20 valores

array([ 6.        ,  8.84210526, 11.68421053, 14.52631579, 17.36842105,
       20.21052632, 23.05263158, 25.89473684, 28.73684211, 31.57894737,
       34.42105263, 37.26315789, 40.10526316, 42.94736842, 45.78947368,
       48.63157895, 51.47368421, 54.31578947, 57.15789474, 60.        ])

>**Importante**
>
> A diferencia de `np.arange()`, la función `np.linspace()` incluye por defecto el límite superior especificado.

**Especificando un intervalo abierto [a, b)**

In [64]:
np.linspace(6, 60, 20, endpoint=False) # [6, 60) con 20 elementos

array([ 6. ,  8.7, 11.4, 14.1, 16.8, 19.5, 22.2, 24.9, 27.6, 30.3, 33. ,
       35.7, 38.4, 41.1, 43.8, 46.5, 49.2, 51.9, 54.6, 57.3])

## **Valores aleatorios**

A continuación veremos una serie de funciones para crear arrays con valores aleatorios y distribuciones de probabilidad.

### **Valores Aleatorios Enteros**

**Valores aleatorios enteros en [a, b):**

In [65]:
np.random.randint(3, 30) # escalar

17

In [67]:
np.random.randint(3, 30, size=9) # vector

array([ 9,  4,  7, 13,  3, 10, 11,  4, 16])

In [66]:
np.random.randint(3, 30, size=(3, 3)) # matriz

array([[29, 21, 20],
       [ 4, 16, 19],
       [20, 17,  7]])

### **Valores Aleatorios Flotantes**

Por simplicidad, en el resto de ejemplos vamos a obviar la salida escalar y matriz.

**Valores aleatorios flotantes en [0, 1):**

In [68]:
np.random.random(9)

array([0.32677021, 0.84139731, 0.89327144, 0.26608469, 0.41387332,
       0.57745754, 0.9125807 , 0.84118873, 0.93065424])

**Valores aleatorios flotantes en [a, b):**

In [69]:
np.random.uniform(1, 100, size=9)

array([26.59651438, 88.33564037,  1.13382761, 99.41244289, 11.4866012 ,
       32.07050286, 91.60102242, 94.47414344,  3.93862885])

## **Distribuciones de Probabilidad**

### **Distribución normal:**

Ejemplo en el que generamos un millón de valores usando como parámetros de la distribución $\mu = 0$,  $\sigma = 5$

In [70]:
dist = np.random.normal(0, 5, size=1_000_000)

In [71]:
dist[:20]

array([-8.7369054 ,  0.60337969,  7.18418155, -1.54669039, -0.49919515,
        7.44449941,  0.81261897, 15.70760169,  6.39577447,  2.45633154,
       -8.33478549,  1.68803627, -1.31795235, -1.21583338, -1.07561126,
       -1.87047308, -3.72908556, -3.54071303,  7.34583537,  2.75434369])

In [72]:
dist.mean()

0.0014856147462323289

In [73]:
dist.std()

5.000535114922286

### **Muestra aleatoria:**

Ejemplo en el que generamos una muestra aleatoria de un millón de lanzamientos de una moneda:

In [74]:
coins = np.random.choice(['head', 'tail'], size = 1_000_000)
coins

array(['tail', 'head', 'head', ..., 'tail', 'head', 'head'], dtype='<U4')

In [75]:
sum(coins == 'head')

499386

In [76]:
sum(coins == 'tail')

500614

### **Muestra aleatoria con probabilidades no uniformes:**

Ejemplo en el que generamos una muestra aleatoria de un millón de lanzamientos con un dado **trucado**:

In [78]:
# La cara del "1" tiene un 50% de probabilidades de salir
dices = np.random.choice(range(1, 7), size = 1_000_000, p = [.5, .1, .1, .1, .1, .1])
dices

array([3, 5, 1, ..., 4, 3, 1])

In [79]:
sum(dices == 1)

500095

In [80]:
sum(dices == 6)

99969

### **Muestra aleatoria sin reemplazo:**

Ejemplo en el que seleccionamos 5 principios aleatorios del **Zen de Python** sin reemplazo:

In [81]:
import this
import codecs

zen = codecs.decode(this.s, 'rot-13').splitlines()[3:]

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [82]:
np.random.choice(zen, size=5, replace=False)

array(['Although practicality beats purity.',
       'Flat is better than nested.',
       "Although that way may not be obvious at first unless you're Dutch.",
       'In the face of ambiguity, refuse the temptation to guess.',
       'Now is better than never.'], dtype='<U69')

> **Ejercicio**

Cree:

* Una matriz de 20 filas y 5 columnas con valores flotantes equiespaciados en el intervalo cerrado [1, 10].

* Un array unidimensional con 128 valores aleatorios de una distribución normal $\mu = 1$,  $\sigma = 2$.

* Un array unidimensional con 15 valores aleatorios de una muestra *1, X, 2* donde la probabilidad de que gane el equipo local es del 50%, la probabilidad de que empaten es del 30% y la probabilidad de que gane el visitante es del 20%.

In [83]:
import numpy as np

# 1. Crear una matriz de 20 filas y 5 columnas con valores flotantes en [1, 10]
matriz = np.random.uniform(1, 10, (20, 5))

# 2. Generar un array unidimensional con 128 valores aleatorios de una distribución normal
mu = 1
sigma = 2
valores_normales = np.random.normal(mu, sigma, 128)

# 3. Generar un array unidimensional con 15 valores aleatorios basados en la probabilidad dada
resultados = np.random.choice([1, 'X', 2], size=15, p=[0.5, 0.3, 0.2])

# Imprimir los objetos creados
print("Matriz:")
print(matriz)

print("\nArray de valores normales:")
print(valores_normales)

print("\nArray de resultados:")
print(resultados)

Matriz:
[[8.48419025 2.76534092 2.71202878 1.36547642 5.55132106]
 [5.85399852 5.5043049  5.70793662 1.64621023 1.40442443]
 [9.34381838 9.71459152 5.01643344 1.38349213 1.02697236]
 [9.79939451 3.65412034 1.31646269 7.6610844  1.62278568]
 [8.71479333 8.77907402 1.07000319 1.98481009 5.20289518]
 [5.00267671 3.19798972 8.73558588 6.21271048 3.08144707]
 [6.76272331 2.59102096 2.47157892 6.3828785  7.65800592]
 [2.15302333 3.79797528 3.45096747 9.2906485  8.20358201]
 [5.99380252 8.91389596 3.74783466 1.21585797 2.01959788]
 [5.9089574  6.04920843 7.68815592 7.51380051 5.74534779]
 [2.80194868 7.90638926 6.20590057 5.950822   8.61979428]
 [6.1943209  6.92196048 4.27622821 7.26866105 5.61256525]
 [9.30770595 6.33697256 3.37334755 3.21948369 1.75829783]
 [7.00415922 2.16321713 7.52399855 1.10971445 2.0027458 ]
 [7.62222787 2.81761885 5.84509617 7.767408   9.90874533]
 [6.69012781 6.22293097 6.93342309 2.47132666 7.10435042]
 [3.84521951 1.58664053 5.46045779 9.95037814 5.69401759]
 [2.21

### **Constantes**

Numpy proporciona una serie de constantes predefinidas que facilitan su acceso y reutilización. Veamos algunas de ellas:

In [84]:
import numpy as np

np.Inf

inf

In [85]:
np.nan

nan

In [86]:
np.e

2.718281828459045

In [87]:
np.pi

3.141592653589793

## **Manipulando elementos**

Los arrays multidimensionales de Numpy están indexados por unos ejes que establecen la forma en la que debemos acceder a sus elementos. Véase el siguiente diagrama:

![Array](../img/array.png "Array")

### **Arrays unidimensionales**

**Acceso a Arrays Unidimensionales**

In [89]:
values = np.array([10, 11, 12, 13, 14, 15])
values

array([10, 11, 12, 13, 14, 15])

In [90]:
values[2]

12

In [91]:
values[-3]

13

**Modificación a Arrays Unidimensionales**

In [92]:
values

array([10, 11, 12, 13, 14, 15])

In [93]:
values[0] = values[1] + values[5]
values

array([26, 11, 12, 13, 14, 15])

**Borrando en Arrays Unidimensionales**

In [94]:
values

array([26, 11, 12, 13, 14, 15])

In [95]:
np.delete(values, 2) # índice (como escalar)

array([26, 11, 13, 14, 15])

In [96]:
np.delete(values, (2, 3, 4)) # índices (como tupla)

array([26, 11, 15])

> **Nota**
>
> La función `np.delete()` no es destructiva. Devuelve una copia modificada del array.

**Inserción en Arrays Unidimensionales**

In [97]:
values

array([26, 11, 12, 13, 14, 15])

In [98]:
np.append(values, 16) # añade elementos al final

array([26, 11, 12, 13, 14, 15, 16])

In [99]:
np.insert(values, 1, 101) # añade elementos en una posición

array([ 26, 101,  11,  12,  13,  14,  15])

Para ambas funciones también es posible añadir varios elementos de una sola vez:

In [100]:
values

array([26, 11, 12, 13, 14, 15])

In [101]:
np.append(values, [16, 17, 18])

array([26, 11, 12, 13, 14, 15, 16, 17, 18])

> **Nota**
>
> La funciones `np.append()` y `np.insert()` no son destructivas. Devuelven una copia modificada del array.

### **Arrays multidimensionales**

Partimos del siguiente array bidimensional (matriz) para ejemplificar las distintas operaciones:

In [102]:
values = np.arange(1, 13).reshape(3, 4)
values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### **Acceso a Arrays Multidimensionales**

In [103]:
values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Acceso a elementos individuales:**

In [104]:
values[0, 0]

1

In [105]:
values[-1, -1]

12

In [106]:
values[1, 2]

7

**Acceso a múltiples elementos:**

In [107]:
values[[0, 2], [1, 2]] # Elementos [0, 1] y [2, 2]

array([ 2, 11])

**Acceso a filas o columnas completas:**

In [108]:
values[2] # tercera fila

array([ 9, 10, 11, 12])

In [109]:
values[:, 1] # segunda columna

array([ 2,  6, 10])

**Acceso a zonas parciales del array:**

In [110]:
values[0:2, 0:2]

array([[1, 2],
       [5, 6]])

In [111]:
values[0:2, [1, 3]]

array([[2, 4],
       [6, 8]])

> **Importante**
>
> Todos estos accesos crean una copia (vista) del array original. Esto significa que, si modificamos un valor en el array copia, se ve reflejado en el origen. Para evitar esta situación podemos usar la función `np.copy()` y desvincular la vista de su fuente.

**Modificación de Arrays Multidimensionales**

In [112]:
values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [114]:
values[0, 0] = 100
values[1] = [55, 66, 77, 88]
values[:, 2] = [30, 70, 110]
values

array([[100,   2,  30,   4],
       [ 55,  66,  70,  88],
       [  9,  10, 110,  12]])

**Borrando en Arrays Multidimensionales**

In [115]:
values

array([[100,   2,  30,   4],
       [ 55,  66,  70,  88],
       [  9,  10, 110,  12]])

In [116]:
np.delete(values, 0, axis=0) # Borrando de la primera fila

array([[ 55,  66,  70,  88],
       [  9,  10, 110,  12]])

In [117]:
np.delete(values, (1, 3), axis = 1) # Borrado de la segunda y cuarta columna

array([[100,  30],
       [ 55,  70],
       [  9, 110]])

> **Truco**
>
> Tener en cuenta que `axis = 0` hace referencia a **filas** y `axis = 1` hace referencia a **columnas** tal y como describe el diagrama del comienzo de la sección.

### **Inserción en Arrays Multidimensionales**

**Añadir elementos al final del array:**

In [121]:
import numpy as np

values = np.array([[1, 2], [3, 4]])
values


array([[1, 2],
       [3, 4]])

In [122]:
np.append(values, [[5, 6]], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [123]:
np.append(values, [[5], [6]], axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

**Insertar elementos en posiciones arbitarias del array:**

In [124]:
values

array([[1, 2],
       [3, 4]])

In [125]:
np.insert(values, 0, [0, 0], axis = 0)

array([[0, 0],
       [1, 2],
       [3, 4]])

In [126]:
np.insert(values, 1, [0, 0], axis = 1)

array([[1, 0, 2],
       [3, 0, 4]])

> **Ejercicio**

Utilzando las operaciones de modificación, borrado e inserción, convierta la siguiente matriz:

\begin{equation*}
\begin{bmatrix}
17 & 12 & 31\\
49 & 11 & 51\\
21 & 31 & 62\\
63 & 75 & 22
\end{bmatrix}
\end{equation*}

es esta :

\begin{equation*}
\begin{bmatrix}
17 & 12 & 31 & 63\\
49 & 11 & 51 & 75\\
21 & 31 & 62 & 22
\end{bmatrix}
\end{equation*}

y luego en esta:

\begin{equation*}
\begin{bmatrix}
17 & 12 & 31 & 63\\
49 & 49 & 49 & 63\\
21 & 31 & 62 & 63
\end{bmatrix}
\end{equation*}

In [145]:
import numpy as np

matrix = np.array([[17, 12, 31], [49, 11, 51], [21, 31, 62], [63, 75, 22]])

print('Matrix:')
print(matrix)
print()

last_row = matrix[-1]
matrix2 = np.delete(matrix, -1, axis=0)
last_row_as_column = last_row.reshape(3, -1)
matrix2 = np.append(matrix2, last_row_as_column, axis=1)

print('Matrix 2:')
print(matrix2)
print()

matrix3 = matrix2
matrix3[1] = matrix3[1, 0]
matrix3[:, -1] = matrix3[0, -1]

print('Matrix 3:')
print(matrix3)

Matrix:
[[17 12 31]
 [49 11 51]
 [21 31 62]
 [63 75 22]]

Matrix 2:
[[17 12 31 63]
 [49 11 51 75]
 [21 31 62 22]]

Matrix 3:
[[17 12 31 63]
 [49 49 49 63]
 [21 31 62 63]]


### **Apilando matrices**

Hay veces que nos interesa combinar dos matrices (arrays en general). Una de los mecanismos que nos proporciona Numpy es el **apilado**.

**Apilado Vertical**:

In [146]:
m1 = np.random.randint(1, 100, size = (3, 2))
m2 = np.random.randint(1, 100, size = (1, 2))
m1

array([[25, 55],
       [55, 17],
       [66, 37]])

In [147]:
m2

array([[41, 56]])

In [148]:
np.vstack((m1, m2))

array([[25, 55],
       [55, 17],
       [66, 37],
       [41, 56]])

**Apilando horizontal:**

In [149]:
m1 = np.random.randint(1, 100, size = (3, 2))
m2 = np.random.randint(1, 100, size = (3, 1))
m1

array([[77, 92],
       [63, 19],
       [55, 78]])

In [150]:
m2

array([[22],
       [ 8],
       [89]])

In [151]:
np.hstack((m1, m2))

array([[77, 92, 22],
       [63, 19,  8],
       [55, 78, 89]])

### **Repitiendo elementos**

**Repetición por ejes:**

El parámetro de repetición indica el número de veces que repetimos el array completo por cada eje:

In [153]:
import numpy as np

values = np.array([[1, 2], [3, 4], [5, 6]])
values

array([[1, 2],
       [3, 4],
       [5, 6]])

In [154]:
np.tile(values, 3) # x3 en columnas

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6]])

In [155]:
np.tile(values, (2, 3)) # x2 en filas; x3 en columnas

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6]])

### **Repetición por elementos:**

El parámetro de repetición indica el número de veces que repetimos cada elemento del array:

In [163]:
import numpy as np

values = np.array([[1, 2], [3, 4], [5, 6]])
values

array([[1, 2],
       [3, 4],
       [5, 6]])

In [157]:
np.repeat(values, 2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [158]:
np.repeat(values, 2, axis = 0) # x2 en filas

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [5, 6],
       [5, 6]])

In [160]:
np.repeat(values, 3 ,axis = 1) # x3 en columnas

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4],
       [5, 5, 5, 6, 6, 6]])

### **Acceso por diagonal**

Es bastante común acceder a elementos de una matriz (array en general) tomando como referencia su diagonal. Para ello, Numpy nos provee de ciertos mecanismos que veremos a continuación.

Para ejemplificarlo, partiremos del siguiente array:

In [164]:
import numpy as np

values = np.array([[73, 86, 90, 20], [96, 55, 15, 48], [38, 63, 96, 95], [13, 87, 32, 96]])
values

array([[73, 86, 90, 20],
       [96, 55, 15, 48],
       [38, 63, 96, 95],
       [13, 87, 32, 96]])

## **Extracción de elementos por Diagonal**

La función `np.diag()` permite acceder a los elementos de un array especificando un parámetro `k` que indica la distancia con la diagonal principal:

![Array diagonal](../img/arraydiagonal.png "Array diagonal")


Veamos cómo variando el parámetro `k` obtenemos distintos resultados:

In [165]:
np.diag(values) # k = 0

array([73, 55, 96, 96])

In [167]:
for k in range(1, values.shape[0]):
  print(f'k = {k}', np.diag(values, k = k))

k = 1 [86 15 95]
k = 2 [90 48]
k = 3 [20]


In [168]:
for k in range(1, values.shape[0]):
  print(f'k = {-k}', np.diag(values, k = -k))

k = -1 [96 63 32]
k = -2 [38 87]
k = -3 [13]


### **Modificación de Elementos por Diagonal**

Numpy también provee un método `np.diag_indices()` que retorna los índices de los elementos de la diagonal principal, con lo que podemos modificar sus valores directamente:

In [169]:
values

array([[73, 86, 90, 20],
       [96, 55, 15, 48],
       [38, 63, 96, 95],
       [13, 87, 32, 96]])

In [170]:
di = np.diag_indices(values.shape[0])
di

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [171]:
values[di] = 0
values

array([[ 0, 86, 90, 20],
       [96,  0, 15, 48],
       [38, 63,  0, 95],
       [13, 87, 32,  0]])

> **Truco**
>
> Existen igualmente las funciones `np.triu_indices()` y `np.tril_indices()` para obtener los índices de la diagonal superior e inferior de una matriz.

## **Operaciones sobre arrays**

### **Operaciones lógicas**

**Indexado Booleano**

El indexado booleano es una operación que permite conocer (a nivel de elemento) si un array cumple o no con una determinada condición:

In [174]:
import numpy as np

values = np.array([[60, 47, 34, 38],
       [43, 63, 37, 68],
       [58, 28, 31, 43],
       [32, 65, 32, 96]])
values

array([[60, 47, 34, 38],
       [43, 63, 37, 68],
       [58, 28, 31, 43],
       [32, 65, 32, 96]])

In [175]:
values > 50 # indexado booleano

array([[ True, False, False, False],
       [False,  True, False,  True],
       [ True, False, False, False],
       [False,  True, False,  True]])

In [177]:
values[values > 50] # uso de máscara

array([60, 63, 68, 58, 65, 96])

In [178]:
values[values > 50] = -1 #modificación de valores
values

array([[-1, 47, 34, 38],
       [43, -1, 37, -1],
       [-1, 28, 31, 43],
       [32, -1, 32, -1]])

Las condiciones pueden ser más complejas e incorporar operadores lógicos | (or) y & (and):

In [180]:
import numpy as np

values = np.array([[60, 47, 34, 38],
       [43, 63, 37, 68],
       [58, 28, 31, 43],
       [32, 65, 32, 96]])
values

array([[60, 47, 34, 38],
       [43, 63, 37, 68],
       [58, 28, 31, 43],
       [32, 65, 32, 96]])

In [181]:
(values < 25) | (values > 75)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [182]:
(values > 25) & (values < 75)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

> **Consejo**
>
> El uso de paréntesis es obligatorio si queremos mantener la precedencia y que funcione correctamente.

> **Ejercicio**

Extraiga todos los números impares de la siguiente matriz:

\begin{equation*}
values =
\begin{bmatrix}
10 & 11 & 12 & 13\\
14 & 15 & 16 & 17\\
18 & 19 & 20 & 21
\end{bmatrix}
\end{equation*}

In [183]:
import numpy as np

# Definir la matriz
values = np.array([[10, 11, 12, 13],
                  [14, 15, 16, 17],
                  [18, 19, 20, 21]])

# Utilizar NumPy para filtrar los números impares
numeros_impares = values[values % 2 != 0]

# Imprimir los números impares
print(numeros_impares)

[11 13 15 17 19 21]


Si lo que nos interesa es obtener los índices del array que satisfacen una determinada condición, Numpy nos proporciona el método `where()` cuyo comportamiento se ejemplifica a continuación:

In [185]:
values = np.array([[60, 47, 34, 38],
       [43, 63, 37, 68],
       [58, 28, 31, 43],
       [32, 65, 32, 96]])
values

array([[60, 47, 34, 38],
       [43, 63, 37, 68],
       [58, 28, 31, 43],
       [32, 65, 32, 96]])

In [186]:
idx = np.where(values > 50)
idx

(array([0, 1, 1, 2, 3, 3]), array([0, 1, 3, 0, 1, 3]))

In [187]:
values[idx]

array([60, 63, 68, 58, 65, 96])

> **Ejercicio**

Pariendo de una matriz de 10 filas y 10 columnas con valores aleatorios en el intervalo [0, 100], realice las operaciones necesarias para obtener una matriz de las mismas dimensiones donde:

* Todos los elementos de la diagonal sean 50.
* Los elementos mayores que 50 tenga valor 100.
* Los elementos menores que 50 tengan valor 0.

In [188]:
import numpy as np

# Crear una matriz aleatoria de 10x10 con valores entre 0 y 100
matriz_original = np.random.randint(0, 101, (10, 10))

# Establecer todos los elementos de la diagonal en 50
np.fill_diagonal(matriz_original, 50)

# Reemplazar los valores mayores que 50 por 100
matriz_original[matriz_original > 50] = 100

# Reemplazar los valores menores que 50 por 0
matriz_original[matriz_original < 50] = 0

# Imprimir la matriz resultante
print(matriz_original)

[[ 50   0   0 100   0 100   0 100 100 100]
 [  0  50   0   0 100 100 100   0   0   0]
 [100   0  50 100   0 100   0   0 100 100]
 [100 100   0  50   0   0 100 100 100   0]
 [100 100   0   0  50   0 100   0 100 100]
 [  0   0   0 100   0  50 100   0 100 100]
 [  0 100   0   0 100 100  50 100 100 100]
 [100 100   0 100   0 100   0  50   0 100]
 [100 100 100   0   0 100   0 100  50   0]
 [  0 100 100 100 100   0 100 100 100  50]]


### **Comparando Arrays**

Dados dos arrays podemos compararlos usando el operador `==` del mismo modo que con cualquier otro objeto en Python. La cuestión es que el resultado se evalúa a nivel de elemento:

In [190]:
m1 = np.array([[1, 2], [3, 4]])
m3 = np.array([[1, 2], [3, 4]])

m1 == m3

array([[ True,  True],
       [ True,  True]])

Si queremos comparar arrays en su totalidad, podemos hacer uso de la siguiente función:

In [191]:
np.array_equal(m1, m3)

True

### **Operaciones de conjunto**

Al igual que existen operaciones sobre conjuntos en Python, tambien podemos llevarlas a cabo sobre arrays en Numpy.

**UNIÓN DE ARRAYS**

$x \cup y$

In [194]:
x = np.array([9, 4, 11, 3, 14, 5, 13, 12, 7, 14])
y = np.array([17, 9, 19, 4, 18, 4, 7, 13, 11, 10])

In [195]:
x

array([ 9,  4, 11,  3, 14,  5, 13, 12,  7, 14])

In [196]:
y

array([17,  9, 19,  4, 18,  4,  7, 13, 11, 10])

In [197]:
np.union1d(x, y)

array([ 3,  4,  5,  7,  9, 10, 11, 12, 13, 14, 17, 18, 19])

**INTERSECCIÓN DE ARRAYS**

$ x \cap y$

In [198]:
x

array([ 9,  4, 11,  3, 14,  5, 13, 12,  7, 14])

In [199]:
y

array([17,  9, 19,  4, 18,  4,  7, 13, 11, 10])

In [200]:
np.intersect1d(x, y)

array([ 4,  7,  9, 11, 13])

**DIFERENCIA DE ARRAYS**

$x \setminus y$

In [201]:
x

array([ 9,  4, 11,  3, 14,  5, 13, 12,  7, 14])

In [202]:
y

array([17,  9, 19,  4, 18,  4,  7, 13, 11, 10])

In [203]:
np.setdiff1d(x, y)

array([ 3,  5, 12, 14])

### **Ordenación de arrays**

En términos generales, existen dos formas de ordenar cualquier estructura de datos, una que modifica in-situ los valores (destructiva) y otra que devuelve nuevos valores (no destructiva). En el caso de Numpy también es así.

**ORDENACIÓN SOBRE ARRAYS UNIDIMENSIONALES**

In [205]:
values = np.array([23, 24, 92, 88, 75, 68, 12, 91, 94, 24, 9, 21, 42, 3, 66])
values

array([23, 24, 92, 88, 75, 68, 12, 91, 94, 24,  9, 21, 42,  3, 66])

In [206]:
np.sort(values) # no destructivo

array([ 3,  9, 12, 21, 23, 24, 24, 42, 66, 68, 75, 88, 91, 92, 94])

In [207]:
values.sort() # destructivo

In [208]:
values

array([ 3,  9, 12, 21, 23, 24, 24, 42, 66, 68, 75, 88, 91, 92, 94])

**ORDENACIÓN SOBRE ARRAYS MULTIDIMENSIONALES**

In [210]:
values = np.array([[52, 23, 90, 46],
       [61, 63, 74, 59],
       [75, 5, 58, 70],
       [21, 7, 80, 52]])
values

array([[52, 23, 90, 46],
       [61, 63, 74, 59],
       [75,  5, 58, 70],
       [21,  7, 80, 52]])

In [211]:
np.sort(values, axis=1) # equivale a np.sort(values)

array([[23, 46, 52, 90],
       [59, 61, 63, 74],
       [ 5, 58, 70, 75],
       [ 7, 21, 52, 80]])

In [212]:
np.sort(values, axis = 0)

array([[21,  5, 58, 46],
       [52,  7, 74, 52],
       [61, 23, 80, 59],
       [75, 63, 90, 70]])

> **Nota**
>
> También existe `values.sort(axis = 1)` y `values.sort(axis = 0)` como métodos destructivos de ordenación.

### **Contando valores**

Otra de las herramientas útiles que proporciona Numpy es la posibilidad de contar el número de valores que existen en un array en base a ciertos criterios.

Para ejemplificarlo, partiremos de un array unidimensional con valores de una distribución aleatoria uniforme en el intervalo [1, 10]:

In [213]:
randomized = np.random.randint(1 , 11, size = 1000)
randomized

array([ 8,  6, 10, 10,  4,  3,  3,  7,  2,  7,  8,  4,  2,  6, 10, 10,  7,
        9,  5,  9,  2,  9,  9,  9,  3,  1,  5,  5,  1,  9,  7,  8,  4,  5,
        9,  1,  1,  8,  9,  5,  7,  8,  4,  4,  3,  9,  1,  4,  4,  7,  3,
        4,  6,  8,  9, 10,  3,  3,  7,  4, 10,  8,  2,  2,  5,  1,  7,  6,
        5,  3,  6,  6,  9,  1,  8,  4,  9,  6,  8,  1, 10,  9,  2,  6,  6,
        1,  4,  2,  5,  8, 10,  7,  4,  8,  9,  2,  3,  5,  2,  1,  4,  8,
        5,  6,  7,  4, 10,  4,  5,  4,  3,  1,  7,  7, 10,  5,  2,  6,  1,
        6,  7,  6,  6, 10,  8,  6,  9, 10,  3,  2,  3,  2,  8,  5, 10,  3,
        6,  1,  2, 10,  8,  1,  9,  5,  5,  8,  4, 10,  5,  8,  2,  4,  9,
        3,  2,  5,  7,  9,  2,  8,  6,  8,  5,  9,  1,  5,  2,  7,  9,  3,
        1,  5,  5,  6,  4,  4,  4,  7,  4,  4,  3,  2,  5,  5,  9,  9,  7,
        8,  7,  7,  6,  5,  1,  1, 10,  4,  1,  6,  2,  1,  2,  8,  9,  9,
        4,  4,  5, 10,  1,  5, 10,  3,  3,  4,  3, 10,  7,  9,  5,  1,  9,
        2,  3,  7,  8,  5

**Valores únicos:**

In [214]:
np.unique(randomized)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Valores únicos (incluyendo frecuencias):**

In [215]:
np.unique(randomized, return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([108, 100,  90, 116, 102,  94,  87, 108,  99,  96]))

**Valores distintos de cero:**

In [216]:
np.count_nonzero(randomized)

1000

**Valores distintos de cero (incluyendo condición):**

In [217]:
np.count_nonzero(randomized > 5)

484

### **Operaciones aritméticas**

Una de las grandes ventajas del uso de arrays numéricos en Numpy es la posibilidad de trabajar con ellos como si fueran objetos simples pero sacando partido de la aritmética vectorial. Esto redunda en una mayor eficacia y rapidez de cómputo.

**OPERACIONES ARITMÉTICAS CON MISMAS DIMENSIONES**

Cuando operamos entre arrays de las mismas dimensiones, las operaciones aritméticas se realizan elemento a elemento (ocupando misma posición) y el resultado, obviamente, tiene las mismas dimensiones:

In [218]:
m1 = np.array([[21, 86, 45],
       [31, 36, 78],
       [31, 64, 70]])
m1

array([[21, 86, 45],
       [31, 36, 78],
       [31, 64, 70]])

In [219]:
m2 = np.array([[58, 67, 17],
       [99, 53, 9],
       [92, 42, 75]])
m2

array([[58, 67, 17],
       [99, 53,  9],
       [92, 42, 75]])

In [220]:
m1 + m2

array([[ 79, 153,  62],
       [130,  89,  87],
       [123, 106, 145]])

In [221]:
m1 - m2

array([[-37,  19,  28],
       [-68, -17,  69],
       [-61,  22,  -5]])

In [222]:
m1 * m2

array([[1218, 5762,  765],
       [3069, 1908,  702],
       [2852, 2688, 5250]])

In [223]:
m1 / m2 # división flotante

array([[0.36206897, 1.28358209, 2.64705882],
       [0.31313131, 0.67924528, 8.66666667],
       [0.33695652, 1.52380952, 0.93333333]])

In [224]:
m1 // m2 # división entera

array([[0, 1, 2],
       [0, 0, 8],
       [0, 1, 0]])

### **OPERACIONES ARITMÉTICAS CON DISTINTAS DIMENSIONES**

Cuando operamos entre arrays con dimensiones diferentes, siempre y cuando se cumplan ciertas restricciones en tamaños de filas y/o columnas, lo que se produce es un broadcasting (o difusión) de los valores.

**Suma con array (fila):**

In [226]:
m = np.array([[9, 8, 1],
       [7, 6, 7]])
m

array([[9, 8, 1],
       [7, 6, 7]])

In [227]:
v = np.array([[2, 3, 6]])
v

array([[2, 3, 6]])

In [228]:
m + v # broadcasting

array([[11, 11,  7],
       [ 9,  9, 13]])

**Suma con array (Columna):**

In [229]:
m

array([[9, 8, 1],
       [7, 6, 7]])

In [232]:
v = np.array([[1], [6]])
v

array([[1],
       [6]])

In [233]:
m + v # broadcasting

array([[10,  9,  2],
       [13, 12, 13]])

> **Advertencia**
>
> En el caso de que no coincidan dimensiones de filas y/o columnas, Numpy no podrá ejecutar la operación y obtendremos un error `ValueError: operands could not be broadcast together with shapes.`

### **OPERACIONES ENTRE ARRAYS Y ESCALARES**

Al igual que ocurría en los casos anteriores, si operamos con un array y un escalr, éste último será difundido para abarcar el tamaño del array:

In [234]:
m = np.array([[9, 8, 1],
              [7, 6, 7]])
m

array([[9, 8, 1],
       [7, 6, 7]])

In [235]:
m + 5

array([[14, 13,  6],
       [12, 11, 12]])

In [236]:
m - 5

array([[ 4,  3, -4],
       [ 2,  1,  2]])

In [237]:
m * 5

array([[45, 40,  5],
       [35, 30, 35]])

In [238]:
m / 5

array([[1.8, 1.6, 0.2],
       [1.4, 1.2, 1.4]])

In [239]:
m // 5

array([[1, 1, 0],
       [1, 1, 1]])

In [240]:
m ** 5

array([[59049, 32768,     1],
       [16807,  7776, 16807]])

### **Operaciones unarias**

Existen multitud de operaciones sobre un único array. A continuación veremos algunas de las más utilizadas en Numpy.

**Funciones Universales**

Las funciones universales ufunc son funciones que operan sobre arrays elemento a elemento. Existen muchas funciones universales definidas en Numpy, parte de ellas operan sobre dos arrays y parte sobre un único array.

Un ejemplo de algunas de estas funciones:

In [241]:
values = np.array([[48.32172375, 24.89651106, 77.49724241],
       [77.81874191, 22.54051494, 65.11282444],
       [ 5.54960482, 59.06720303, 62.52817198]])
values

array([[48.32172375, 24.89651106, 77.49724241],
       [77.81874191, 22.54051494, 65.11282444],
       [ 5.54960482, 59.06720303, 62.52817198]])

In [242]:
np.sqrt(values)

array([[6.95138287, 4.98964037, 8.80325181],
       [8.82149318, 4.74768522, 8.06925179],
       [2.35575992, 7.68551905, 7.9074757 ]])

In [243]:
np.sin(values)

array([[-0.93125201, -0.23403917,  0.86370434],
       [ 0.66019205, -0.52214693,  0.75824777],
       [-0.66953344,  0.58352078, -0.29903488]])

In [244]:
np.ceil(values)

array([[49., 25., 78.],
       [78., 23., 66.],
       [ 6., 60., 63.]])

In [245]:
np.floor(values)

array([[48., 24., 77.],
       [77., 22., 65.],
       [ 5., 59., 62.]])

In [246]:
np.log(values)

array([[3.87788123, 3.21472768, 4.35024235],
       [4.3543823 , 3.11531435, 4.17612153],
       [1.71372672, 4.07867583, 4.13561721]])

### **REDUCIENDO EL RESULTADO**

Numpy nos permite aplicar cualquier función sobre un array reduciendo el resultado por alguno de sus ejes. Esto abre una amplia gama de posibilidades.

A modo de ilustración, veremos un par de ejemplos con la suma y el producto:

In [247]:
values = np.array([[8, 2, 7],
       [2, 0, 6],
       [6, 3, 4]])
values

array([[8, 2, 7],
       [2, 0, 6],
       [6, 3, 4]])

In [248]:
np.sum(values, axis = 0) # suma por columnas

array([16,  5, 17])

In [249]:
np.sum(values, axis = 1) # suma por filas

array([17,  8, 13])

In [250]:
np.prod(values, axis = 0) # Producto por columnas

array([ 96,   0, 168])

In [251]:
np.prod(values, axis = 1) # Producto por filas

array([112,   0,  72])

> **Ejercicio**

Compruebe que, para $\theta = 2\pi$ y $k = 20$ se cumple la siguiente igualdad del producto infinito de Euler:

$\cos(\frac{\theta}{2}).\cos(\frac{\theta}{4}).\cos(\frac{\theta}{8})... = \prod_{i=1}^{k}\cos(\frac{\theta}{2^i}) \thickapprox \frac{\sin(\theta)}{\theta}$

In [252]:
import numpy as np

# Valores dados
theta = 2 * np.pi  # θ = 2π
k = 20

# Crear un array con los términos cos(θ/2^i)
terminos = np.array([np.cos(theta / 2**i) for i in range(1, k + 1)])

# Calcular el producto infinito
producto_infinito = np.prod(terminos)

# Calcular sin(θ)/θ
sin_theta_over_theta = np.sin(theta) / theta

# Imprimir el resultado del producto infinito y sin(θ)/θ
print("Resultado del producto infinito de Euler:", producto_infinito)
print("sin(θ)/θ:", sin_theta_over_theta)

Resultado del producto infinito de Euler: -3.8981718325427036e-17
sin(θ)/θ: -3.8981718325193755e-17


**FUNCIONES ESTADÍSTICAS**

Numpy proporciona una gran cantidad de funciones estadísticas que pueden ser aplicadas sobre arrays.

Veamos algunas de ellas:

In [253]:
dist

array([-8.7369054 ,  0.60337969,  7.18418155, ..., -1.88915292,
       -4.16582484,  0.85310836])

In [254]:
np.mean(dist)

0.0014856147462323289

In [255]:
np.std(dist)

5.000535114922286

In [256]:
np.median(dist)

0.0007904844656450511

**Máximos y MÍNIMOS**

Una de las operaciones más comunes en el manejo de datos es encontrar máximos o mínimos. Para ello, disponemos de las típicas funciones con las ventajas del uso de arrays multidimensionales:

In [258]:
values = np.array([[66, 54, 33, 15, 58],
       [55, 46, 39, 16, 38],
       [73, 75, 79, 25, 83],
       [81, 30, 22, 32,  8],
       [92, 25, 82, 10, 90]])
values

array([[66, 54, 33, 15, 58],
       [55, 46, 39, 16, 38],
       [73, 75, 79, 25, 83],
       [81, 30, 22, 32,  8],
       [92, 25, 82, 10, 90]])

In [259]:
np.min(values)

8

In [260]:
np.min(values, axis = 0)

array([55, 25, 22, 10,  8])

In [261]:
np.min(values, axis = 1)

array([15, 16, 25,  8, 10])

In [262]:
np.max(values)

92

In [263]:
np.max(values, axis = 0)

array([92, 75, 82, 32, 90])

In [264]:
np.max(values, axis = 1)

array([66, 55, 83, 81, 92])

Si lo que interesa es obtener los índices de aquellos elementos con valores máximos o mínimos, podemos hacer uso de las funciones `argmax()` y `argmin()` respectivamente.

Veamos un ejemplo donde obtenemos los valores máximos por columnas (mediante sus indices):

In [265]:
values

array([[66, 54, 33, 15, 58],
       [55, 46, 39, 16, 38],
       [73, 75, 79, 25, 83],
       [81, 30, 22, 32,  8],
       [92, 25, 82, 10, 90]])

In [267]:
idx = np.argmax(values, axis = 0)
idx

array([4, 2, 4, 3, 4])

In [268]:
values[idx, range(values.shape[1])]

array([92, 75, 82, 32, 90])

### **Vectorizando funciones**

Una de las ventajas de trabajar con arrays numéricos en Numpy es sacar provecho de la optimización que se produce a nivel de la propia estructura de datos. En el caso de que queremos implementar una función propia para realizar una determinada acción, sería deseable seguir aprovechando esa característica.

Veamos un ejemplo en el que queremos realizar el siguiente cálculo entre dos matrices $A$ y $B$:

$
A_{ij} \cdot B_{ij} =
\begin{cases}
  A_{ij} + B_{ij}, & \text{si } A_{ij} > B_{ij} \\
  A_{ij} - B_{ij}, & \text{si } A_{ij} < B_{ij} \\
  0, & \text{en otro caso}
\end{cases}
$


Esta función, definida en Python, quedaría tal que así:

In [269]:
def customf(a, b):
  if a > b:
    return a + b
  elif a < b:
    return a - b
  else:
    return 0

Las dos matrices de partida tienen 9M de valores aleatorios entre -100 y 100:

In [270]:
A = np.random.randint(-100, 100, size = (3000, 3000))
B = np.random.randint(-100, 100, size = (3000, 3000))

Una primera aproximación para aplicar esta función a cada elemento de las matrices de entrada sería la siguiente:

In [272]:
result = np.zeros_like(A)

In [273]:
%%timeit
for i in range(A.shape[0]):
  for j in range(A.shape[1]):
    result[i, j] = customf(A[i, j], B[i, j])

36.1 s ± 4.62 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


### **Mejorando rendimiento con funciones vectorizadas**

Con un pequeño detalle podemos mejorar el rendimiento de la función que hemos diseñado anteriormente. Se trata de decorarla con `np.vectorize` con lo que estamos otorgándole un comportamiento distinto y enfocado al procesamiento de arrays númericos:

In [274]:
@np.vectorize
def customf(a, b):
  if a > b:
    return a + b
  elif a < b:
    return a - b
  else:
    return 0

Dado que ahora ya se trata de una función vectorizada podemos aplicarla directamente a las matrices de entrada (aprovechamos para medir su tiempo de ejecución):

In [275]:
%timeit customf(A, B)

17.5 s ± 7.07 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


Hemos obtenido una mejora de `2.32x` con respecto al uso de funciones simples.

> **Truco**
>
> La mejora de rendimiento se aprecia más claramente a medida que los tamaños de las matrices (arrays) de entrada son mayores.

> **Consejo**
>
> El uso de funciones lambda puede ser útil en vectorización: `np.vectorize(lambda a, b: return a + b)`.

> **Ejercicio**

1. Cree dos matrices cuadrados de 20x20 con valores aleatorios flotantes uniformes en el intervalo [0, 1000)

2. Vectorice una función que devuelva la media (elemento a elemento) entre las dos matrices.

3. Realice la misma operación que en 2 pero usando suma de matrices y división por escalar.

4. Compute los tiempos de ejecución de 2 y 3.

In [276]:
import numpy as np
import time

# Paso 1: Crear dos matrices aleatorias
np.random.seed(0)  # Establecer una semilla para reproducibilidad
matriz_A = np.random.uniform(0, 1000, (20, 20))
matriz_B = np.random.uniform(0, 1000, (20, 20))

# Paso 2: Vectorizar la función para calcular la media
def media_entre_matrices(A, B):
    return (A + B) / 2

# Paso 3: Realizar la operación usando suma de matrices y división por escalar
inicio = time.time()
resultado_suma = (matriz_A + matriz_B) / 2
tiempo_suma = time.time() - inicio

# Paso 4: Realizar la operación vectorizada y medir el tiempo
inicio = time.time()
resultado_vectorizado = media_entre_matrices(matriz_A, matriz_B)
tiempo_vectorizado = time.time() - inicio

# Comprobación de igualdad
igualdad = np.allclose(resultado_suma, resultado_vectorizado)

# Imprimir resultados y tiempos de ejecución
print("Matriz A:")
print(matriz_A)
print("\nMatriz B:")
print(matriz_B)
print("\nResultado (suma de matrices y división por escalar):")
print(resultado_suma)
print("\nResultado (función vectorizada):")
print(resultado_vectorizado)
print("\n¿Los resultados son iguales?", igualdad)
print("\nTiempo de ejecución (suma de matrices y división por escalar):", tiempo_suma, "segundos")
print("Tiempo de ejecución (función vectorizada):", tiempo_vectorizado, "segundos")

Matriz A:
[[548.81350393 715.18936637 602.76337607 544.883183   423.65479934
  645.89411307 437.58721126 891.77300078 963.6627605  383.44151883
  791.72503808 528.89491975 568.04456109 925.59663829  71.0360582
   87.1292997   20.21839744 832.61984555 778.15675095 870.01214825]
 [978.61834223 799.15856422 461.47936225 780.52917629 118.27442587
  639.92102133 143.35328741 944.66891705 521.84832175 414.66193999
  264.5556121  774.23368943 456.15033222 568.43394887  18.78980044
  617.63549708 612.09572272 616.93399687 943.74807851 681.8202991 ]
 [359.50790057 437.0319538  697.63119593  60.22547163 666.76671545
  670.63786962 210.38256107 128.92629765 315.42835092 363.71077094
  570.19677042 438.60151346 988.37383806 102.04481075 208.87675609
  161.30951788 653.10832547 253.29160254 466.31077286 244.425592  ]
 [158.96958365 110.37514116 656.32958947 138.18295135 196.58236168
  368.72517066 820.99322985  97.10127579 837.9449075   96.09840789
  976.45946501 468.65120165 976.76108819 604.84551

## **Álgebra lineal**

Numpy tiene una sección dedicado al álgebra lineal cuyas funciones pueden resultar muy interesantes según el contexto en el que estemos trabajando.

### **Producto de matrices**

Si bien hemos hablado del producto de arrays elemento a elemento, Numpy nos permite hacer la multiplicación clásica de matrices:

In [277]:
m1 = np.array([[1, 8, 4],
       [8, 7, 1],
       [1, 3, 8]])
m1

array([[1, 8, 4],
       [8, 7, 1],
       [1, 3, 8]])

In [278]:
m2 = np.array([[1, 5, 7],
       [9, 4, 2],
       [1, 4, 2]])
m1

array([[1, 8, 4],
       [8, 7, 1],
       [1, 3, 8]])

In [279]:
np.dot(m1, m2)

array([[77, 53, 31],
       [72, 72, 72],
       [36, 49, 29]])

En Python 3.5 se introdujo el operador `@` que permitía implementar el método especial `__matmul__()` de multiplicación de matrices. Numpy lo ha desarrollado y simplifica la multiplicación de matrices de la siguiente manera:

In [280]:
m1 @ m2

array([[77, 53, 31],
       [72, 72, 72],
       [36, 49, 29]])

> **Ejercicio**

Compruebe que la matriz
\begin{bmatrix}
1 & 2\\
3 & 5
\end{bmatrix}

satisface la ecuación matricial: $X^2 - 6x - I = 0$ donde $I$ es la matriz identidad de orden 2.

In [281]:
import numpy as np

# Definir la matriz X
X = np.array([[1, 2], [3, 5]])

# Calcular X^2
X_squared = np.dot(X, X)

# Calcular 6X
six_X = 6 * X

# Definir la matriz identidad I
I = np.identity(2)

# Calcular X^2 - 6X - I
resultado = X_squared - six_X - I

# Verificar si la matriz resultado es igual a la matriz cero
es_cero = np.array_equal(resultado, np.zeros((2, 2)))

if es_cero:
    print("La matriz X satisface la ecuación matricial X^2 - 6X - I = 0.")
else:
    print("La matriz X no satisface la ecuación matricial X^2 - 6X - I = 0.")

La matriz X satisface la ecuación matricial X^2 - 6X - I = 0.


### **Determinante de una matriz**

El cálculo del determinante es una operación muy utilizada en álgebra lineal. Lo podemos realizar en Numpy de la siguiente manera:

In [283]:
m = np.array([[4, 1, 6],
       [4, 8, 8],
       [2, 1, 7]])
m

array([[4, 1, 6],
       [4, 8, 8],
       [2, 1, 7]])

In [284]:
np.linalg.det(m)

108.00000000000003

### **Inversa de una matriz**

La inversa de una matriz se calcula de la siguiente manera:

In [285]:
m

array([[4, 1, 6],
       [4, 8, 8],
       [2, 1, 7]])

In [286]:
m_inv = np.linalg.inv(m)
m_inv

array([[ 0.44444444, -0.00925926, -0.37037037],
       [-0.11111111,  0.14814815, -0.07407407],
       [-0.11111111, -0.01851852,  0.25925926]])

Una propiedad de la matriz inversa es que si la multiplicamos por la matriz de partida obtenemos la matriz identidad. Veamos que cumple $A . A^{-1} = I$:

In [287]:
np.dot(m, m_inv)

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 0.00000000e+00, 1.00000000e+00]])

### **Traspuesta de una matriz**

La traspuesta de una matriz $A$ se denota por: $(A^t)_{ij} = A_{ji}$, $1 \leq i \leq n$, $1 \leq j \leq m$, pero básicamente consiste en intercambiar filas por columnas.

Aún más fácil es computar la traspuesta de una matriz con Numpy:

In [289]:
m = np.array([[1, 2, 3],
       [4, 5, 6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [290]:
m.T

array([[1, 4],
       [2, 5],
       [3, 6]])

> **Ejercicio**

Dadas las matrices:


\begin{equation*}
A =
\begin{bmatrix}
1 & -2 & 1\\
3 & 0 & 1
\end{bmatrix}
\end{equation*}

\begin{equation*}
B =
\begin{bmatrix}
4 & 0 & -1\\
-2 & 1 & 0
\end{bmatrix}
\end{equation*}

Comprueba que se cumplen las siguientes igualdades:

* $(A + B)^t = A^t + B^t$

* $(3A)^t = 3A^t$

In [291]:
import numpy as np

# Definir las matrices A y B
A = np.array([[1, -2, 1],
              [3, 0, 1]])

B = np.array([[4, 0, -1],
              [-2, 1, 0]])

# Calcular la transpuesta de A y B
A_transpuesta = np.transpose(A)
B_transpuesta = np.transpose(B)

# Verificar la igualdad 1: (A + B)^t = A^t + B^t
izquierda = np.transpose(A + B)
derecha = A_transpuesta + B_transpuesta
igualdad1 = np.array_equal(izquierda, derecha)

# Verificar la igualdad 2: (3A)^t = 3A^t
izquierda = np.transpose(3 * A)
derecha = 3 * A_transpuesta
igualdad2 = np.array_equal(izquierda, derecha)

# Imprimir los resultados
if igualdad1:
    print("(A + B)^t = A^t + B^t se cumple.")
else:
    print("(A + B)^t = A^t + B^t no se cumple.")

if igualdad2:
    print("(3A)^t = 3A^t se cumple.")
else:
    print("(3A)^t = 3A^t no se cumple.")

(A + B)^t = A^t + B^t se cumple.
(3A)^t = 3A^t se cumple.


### **Elevar matriz a potencia**

En el mundo del álgebra lineal es muy frecuente recurrir a la exponenciación de matrices a través de su producto clásico. En este sentido, Numpy nos proporciona una función para computarlo:

In [294]:
m = np.array([[4, 1, 6],
       [4, 8, 8],
       [2, 1, 7]])
m

array([[4, 1, 6],
       [4, 8, 8],
       [2, 1, 7]])

In [295]:
np.linalg.matrix_power(m, 3) # más eficiente que np.dot(m, np.dot(m, m))

array([[ 348,  250,  854],
       [ 848,  816, 2000],
       [ 310,  231,  775]])

> **Ejercicio**

Dada la matriz

\begin{equation*}
A =
\begin{bmatrix}
4 & 5 & -1\\
-3 & -4 & 1\\
-3 & -4 & 0
\end{bmatrix}
\end{equation*}

Calcule: $A^2, A^3, ....., A^{128}$

¿Nota algo especial en los resultados?

In [296]:
import numpy as np

# Definir la matriz A
A = np.array([[4, 5, -1],
              [-3, -4, 1],
              [-3, -4, 0]])

# Inicializar una lista para almacenar las potencias sucesivas de A
potencias_A = [A]

# Calcular las potencias de A desde 2 hasta 128
for n in range(2, 129):
    A_n = np.dot(potencias_A[-1], A)
    potencias_A.append(A_n)

# Verificar si hay algún patrón especial en los resultados
patron_especial = True
for i in range(len(potencias_A) - 1):
    if not np.array_equal(potencias_A[i], potencias_A[i + 1]):
        patron_especial = False
        break

# Imprimir los resultados
if patron_especial:
    print("Se observa un patrón especial: A^n es igual para todos los valores de n desde 2 hasta 128.")
else:
    print("No se observa un patrón especial en los resultados.")

# Imprimir una muestra de los resultados
print("A^2:")
print(potencias_A[0])
print("A^128:")
print(potencias_A[-1])

No se observa un patrón especial en los resultados.
A^2:
[[ 4  5 -1]
 [-3 -4  1]
 [-3 -4  0]]
A^128:
[[ 4  4  1]
 [-3 -3 -1]
 [ 0  1 -1]]


### **Sistemas de ecuaciones lineales**

Numpy también nos permite resolver sistemas de ecuaciones lineales. Para ello debemos modelar nuestro sistema a través de arrays.

Veamos un ejemplo en el que queremos resolver el siguiente sistemas de ecuaciones lineales:

\begin{equation*}
\begin{cases}
x_1 + 2x_3 = 1\\
x_1 - x_2 = -2\\
x_2 + x_3 = -1
\end{cases}

\Longrightarrow

\begin{bmatrix}
1 & 0 & 2 \\
1 & -1 & 0 \\
0 & 1 & 1
\end{bmatrix}

\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}
=
\begin{bmatrix}
1 \\
-2 \\
-1
\end{bmatrix}

\Longrightarrow

AX = B

\end{equation*}

Podemos alamacenar las matrices de coeficientes $A$ y $B$ de la siguiente manera:

In [297]:
A = np.array([[1, 0, 2], [1, -1, 0], [0, 1, 1]])
B = np.array([1, -2, -1]).reshape(-1, 1)

In [298]:
A

array([[ 1,  0,  2],
       [ 1, -1,  0],
       [ 0,  1,  1]])

In [299]:
B

array([[ 1],
       [-2],
       [-1]])

La solución al sistema viene dada por la siguiente función:

In [300]:
np.linalg.solve(A, B)

array([[-7.],
       [-5.],
       [ 4.]])

La solución del sistema debe ser la misma que si obtenemos $X = A^{-1}.B$

In [301]:
np.dot(np.linalg.inv(A), B)

array([[-7.],
       [-5.],
       [ 4.]])

> **Ejercicio**

Resuelva el siguiente sistema de ecuaciones lineales:


\begin{cases}
3x + 4y - z = 8 \\
5x - 2y + z = 4 \\
2x - 2y + z = 1
\end{cases}


In [302]:
import numpy as np

# Definir la matriz de coeficientes A y el vector de términos constantes B
A = np.array([[3, 4, -1],
              [5, -2, 1],
              [2, -2, 1]])

B = np.array([8, 4, 1])

# Resolver el sistema de ecuaciones AX = B
X = np.linalg.solve(A, B)

# Imprimir la solución
print("La solución del sistema de ecuaciones es:")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])

La solución del sistema de ecuaciones es:
x = 1.0
y = 1.999999999999999
z = 2.9999999999999973


| **Inicio** | **Siguiente 2** |
|----------- |-------------- |
| [🏠](../../README.md) | [⏩](./2_Pandas.ipynb)|