| **Inicio** | **atrás 15** | **Siguiente 17** |
|----------- |-------------- |---------------|
| [🏠](../../README.md) | [⏪](./15.Modulos_de_math_cmath.ipynb)| [⏩](./17.Representacion_grafica.ipynb)|

# **16. Modulos de Python: Numpy**

## **Introducción a numpy**

Numpy (Numerical Python) es una biblioteca de Python que se utiliza para trabajar con matrices y arrays multidimensionales. Es una de las bibliotecas más utilizadas en el campo de la ciencia de datos y el análisis numérico. Numpy proporciona una gran cantidad de funciones y herramientas para realizar operaciones matemáticas y estadísticas en arrays.

Para utilizar Numpy, primero debemos instalar la biblioteca en nuestro sistema. Podemos hacer esto utilizando pip, el gestor de paquetes de Python. Para instalar Numpy, abrimos una terminal o línea de comandos y ejecutamos el siguiente comando:

`pip install numpy`

Una vez que Numpy está instalado, podemos comenzar a utilizarlo en nuestros programas de Python. Para ello, debemos importar la biblioteca utilizando la siguiente línea de código:

In [1]:
import numpy as np


En este ejemplo, utilizamos la abreviación `"np"` para referirnos a la biblioteca `Numpy` en nuestro programa.

A continuación, mostraremos algunos ejemplos de cómo utilizar `Numpy` para trabajar con arrays multidimensionales.

* **Crear un array**

Podemos crear un array de `Numpy` utilizando la función `np.array()`. Por ejemplo, para crear un array de una dimensión con los números del 0 al 4, podemos escribir lo siguiente:

In [2]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4])

print(arr)  # Salida: [0 1 2 3 4]


[0 1 2 3 4]


También podemos crear un array de dos dimensiones especificando una lista de listas como argumento para `np.array()`. Por ejemplo, para crear una matriz de 2x3 con los números del 0 al 5, podemos escribir lo siguiente:

In [3]:
import numpy as np

arr = np.array([[0, 1, 2], [3, 4, 5]])

print(arr)
# Salida:
# [[0 1 2]
#  [3 4 5]]


[[0 1 2]
 [3 4 5]]


* **Operaciones con arrays**

Podemos realizar operaciones matemáticas con `arrays` utilizando `Numpy`. Por ejemplo, para sumar dos arrays, podemos utilizar la función `np.add()`. En el siguiente ejemplo, sumamos dos arrays de una dimensión:

In [4]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

sum_arr = np.add(arr1, arr2)

print(sum_arr)  # Salida: [5 7 9]


[5 7 9]


También podemos realizar operaciones entre un escalar y un array. En el siguiente ejemplo, multiplicamos cada elemento del array por 2:

In [5]:
import numpy as np

arr = np.array([1, 2, 3])

mult_arr = np.multiply(arr, 2)

print(mult_arr)  # Salida: [2 4 6]


[2 4 6]


* **Funciones estadísticas**

Numpy proporciona una gran cantidad de funciones para realizar operaciones estadísticas en arrays. Por ejemplo, podemos calcular la media, la mediana y la desviación estándar de un array utilizando las funciones `np.mean()`, `np.median()` y `np.std()`, respectivamente.

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)

print("Media:", mean)  # Salida: Media: 3.0
print("Mediana:", median)  # Salida: Mediana: 3.0
print("Desviación estándar:", std_dev)  # Salida: Desviación estándar: 1.4142135623730951


Media: 3.0
Mediana: 3.0
Desviación estándar: 1.4142135623730951


* **Indexación y segmentación**

Podemos acceder a elementos individuales de un array utilizando la indexación de Numpy. Por ejemplo, para acceder al segundo elemento de un array de una dimensión, podemos escribir lo siguiente:

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

second_elem = arr[1]

print(second_elem)  # Salida: 2


2


También podemos acceder a segmentos de un array utilizando la segmentación de Numpy. Por ejemplo, para acceder a los primeros tres elementos de un array de una dimensión, podemos escribir lo siguiente:

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

first_three = arr[:3]

print(first_three)  # Salida: [1 2 3]


[1 2 3]


**Conclusiones**

Numpy es una biblioteca fundamental para cualquier persona que trabaje con datos numéricos en Python. Nos proporciona una gran cantidad de herramientas para trabajar con arrays multidimensionales y realizar operaciones matemáticas y estadísticas en ellos. En esta introducción, hemos visto algunos ejemplos básicos de cómo utilizar Numpy, pero hay muchas más funciones y herramientas disponibles en la biblioteca.

## **Creando arrays con numpy**

Numpy es una de las bibliotecas más utilizadas en Python para trabajar con arreglos, matrices y operaciones matemáticas. Para empezar a trabajar con Numpy, primero debemos importar la biblioteca. Se puede hacer esto con la siguiente línea de código:

In [9]:
import numpy as np


Una vez importada la biblioteca, podemos empezar a crear arreglos con Numpy. Hay varias formas de hacerlo:

1. **Creando un arreglo a partir de una lista**

Podemos crear un arreglo a partir de una lista de Python utilizando la función `array` de Numpy. Por ejemplo:

In [10]:
import numpy as np

lista = [1, 2, 3, 4, 5]
arreglo = np.array(lista)
print(arreglo)


[1 2 3 4 5]


**2. Creando un arreglo de ceros**

Podemos crear un arreglo de ceros utilizando la función `zeros` de Numpy. Por ejemplo, si queremos crear un arreglo de 3 elementos con ceros, podemos hacerlo así:

In [11]:
import numpy as np

arreglo_ceros = np.zeros(3)
print(arreglo_ceros)


[0. 0. 0.]


**3. Creando un arreglo de unos**

Podemos crear un arreglo de unos utilizando la función `ones` de Numpy. Por ejemplo, si queremos crear un arreglo de 4 elementos con unos, podemos hacerlo así:

In [12]:
import numpy as np

arreglo_unos = np.ones(4)
print(arreglo_unos)


[1. 1. 1. 1.]


**4. Creando un arreglo de valores aleatorios**

Podemos crear un arreglo de valores aleatorios utilizando la función `random` de Numpy. Por ejemplo, si queremos crear un arreglo de 5 elementos con valores aleatorios entre 0 y 1, podemos hacerlo así:

In [13]:
import numpy as np

arreglo_aleatorio = np.random.random(5)
print(arreglo_aleatorio)


[0.9061231  0.58983353 0.93040559 0.23636625 0.81672775]


**5. Creando un arreglo de valores espaciados uniformemente**

Podemos crear un arreglo de valores espaciados uniformemente utilizando la función `linspace` de Numpy. Por ejemplo, si queremos crear un arreglo con 5 valores espaciados uniformemente entre 0 y 1, podemos hacerlo así:

In [14]:
import numpy as np

arreglo_uniforme = np.linspace(0, 1, 5)
print(arreglo_uniforme)


[0.   0.25 0.5  0.75 1.  ]


**6. Creando un arreglo de valores espaciados con un paso**

Podemos crear un arreglo de valores espaciados con un paso utilizando la función `arange` de Numpy. Por ejemplo, si queremos crear un arreglo con valores espaciados de 2 en 2 entre 0 y 8, podemos hacerlo así:

In [15]:
import numpy as np

arreglo_paso = np.arange(0, 8, 2)
print(arreglo_paso)


[0 2 4 6]


## **Dimensiones de un array**

En Python, los arrays tienen una o más dimensiones, lo que significa que podemos tener un arreglo de una dimensión (vector) o un arreglo de varias dimensiones (matriz o tensor). Cada dimensión se refiere al número de índices necesarios para acceder a un elemento particular en el arreglo.

Por ejemplo, en un arreglo de dos dimensiones, necesitamos dos índices para acceder a un elemento en particular. En un arreglo de tres dimensiones, necesitamos tres índices para acceder a un elemento en particular, y así sucesivamente.

Para ver las dimensiones de un array en Python, podemos utilizar la función `ndim` de Numpy. Veamos algunos ejemplos:

In [16]:
import numpy as np

# Un arreglo de una dimensión
a = np.array([1, 2, 3])
print(a.ndim) # Salida: 1

# Un arreglo de dos dimensiones
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.ndim) # Salida: 2

# Un arreglo de tres dimensiones
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c.ndim) # Salida: 3


1
2
3


En el primer ejemplo, `a` es un arreglo de una dimensión (vector), por lo que su dimensión es 1. En el segundo ejemplo, `b` es un arreglo de dos dimensiones (matriz), por lo que su dimensión es 2. En el tercer ejemplo, `c` es un arreglo de tres dimensiones (tensor), por lo que su dimensión es 3.

Podemos acceder a cada elemento de un arreglo utilizando sus índices. Por ejemplo, para acceder al segundo elemento de `a`, podemos hacer lo siguiente:

In [17]:
print(a[1]) # Salida: 2


2


Para acceder al elemento (2, 3) en `b`, podemos hacer lo siguiente:

In [18]:
print(b[1, 2]) # Salida: 6


6


Y para acceder al elemento (1, 2, 1) en `c`, podemos hacer lo siguiente:

In [19]:
print(c[1, 0, 1]) # Salida: 6


6


En resumen, las dimensiones de un array en Python nos indican cuántos índices se necesitan para acceder a un elemento en particular en el arreglo. Podemos utilizar la función `ndim` de Numpy para obtener la dimensión de un arreglo y acceder a los elementos del arreglo utilizando sus índices.

## **Shape de un array**

En Python, el `shape` de un array se refiere a la tupla de números que describe el tamaño de cada dimensión del array. Es decir, si tenemos un array de dos dimensiones con una forma `(shape)` de `(3, 4)`, significa que el array tiene tres filas y cuatro columnas.

Para obtener la forma `(shape)` de un array en Python, podemos utilizar la función `shape()` de la librería `Numpy`. Veamos algunos ejemplos:

In [20]:
import numpy as np

# Un arreglo de una dimensión
a = np.array([1, 2, 3])
print(a.shape) # Salida: (3,)

# Un arreglo de dos dimensiones
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape) # Salida: (2, 3)

# Un arreglo de tres dimensiones
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c.shape) # Salida: (2, 2, 2)


(3,)
(2, 3)
(2, 2, 2)


En el primer ejemplo, `a` es un arreglo de una dimensión (vector) con tres elementos, por lo que su forma es `(3,)`. El paréntesis indica que `a` es un vector (unidimensional), y el número dentro del paréntesis indica la cantidad de elementos en ese vector.

En el segundo ejemplo, `b` es un arreglo de dos dimensiones (matriz) con dos filas y tres columnas, por lo que su forma es `(2, 3)`.

En el tercer ejemplo, `c` es un arreglo de tres dimensiones (tensor) con dos niveles, dos filas y dos columnas, por lo que su forma es `(2, 2, 2)`.

Podemos utilizar la forma `(shape)` de un array para acceder a cada elemento utilizando un bucle `for`. Por ejemplo, para recorrer todos los elementos de `b`, podemos hacer lo siguiente:

In [21]:
for i in range(b.shape[0]):
  for j in range(b.shape[1]):
    print(b[i, j])


1
2
3
4
5
6


Este código recorre todos los elementos de `b` utilizando los índices de fila `(i)` y columna `(j)`, y los imprime en la pantalla.

En resumen, el `shape` de un array en Python nos indica el tamaño de cada dimensión del array. Podemos utilizar la función `shape()` de Numpy para obtener la forma de un array y acceder a los elementos del array utilizando un bucle `for` y los índices de fila y columna.

## **Reshape de un array**

En Python, `reshape` es una función de la librería `Numpy` que nos permite cambiar la forma `(shape)` de un array sin modificar sus datos. En otras palabras, podemos reorganizar los elementos de un array en diferentes formas sin alterar su contenido.

La sintaxis básica de `reshape` es la siguiente:

`numpy.reshape(array, newshape, order='C')`

**Donde:**

* **array** es el array que queremos remodelar.

* **newshape** es una tupla que indica la nueva forma deseada para el array.

* **order** es opcional y especifica cómo se deben leer los elementos del array. Puede ser `'C'` para leer los elementos en orden de fila (por defecto) o `'F'` para leer los elementos en orden de columna.

Veamos algunos ejemplos para entender mejor cómo funciona `reshape`:

In [22]:
import numpy as np

# Creamos un array de una dimensión con 12 elementos
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

# Cambiamos la forma del array a una matriz de 3 filas y 4 columnas
b = np.reshape(a, (3, 4))
print(b)
# Salida:
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# Cambiamos la forma del array a una matriz de 4 filas y 3 columnas
c = np.reshape(a, (4, 3))
print(c)
# Salida:
# [[ 0  1  2]
#  [ 3  4  5]
#  [ 6  7  8]
#  [ 9 10 11]]

# Cambiamos la forma del array a una matriz de 2 niveles, 3 filas y 2 columnas
d = np.reshape(a, (2, 3, 2))
print(d)
# Salida:
# [[[ 0  1]
#   [ 2  3]
#   [ 4  5]]

#  [[ 6  7]
#   [ 8  9]
#   [10 11]]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


* En el primer ejemplo, creamos un array de una dimensión con 12 elementos y luego usamos `reshape` para convertirlo en una matriz de 3 filas y 4 columnas.

* En el segundo ejemplo, usamos `reshape` para convertir el mismo array de una dimensión en una matriz de 4 filas y 3 columnas.

* En el tercer ejemplo, usamos `reshape` para convertir el mismo array de una dimensión en un tensor de dos niveles, con tres filas y dos columnas en cada nivel.

Es importante tener en cuenta que el número de elementos en el array original debe ser igual al número de elementos en la forma deseada después de usar `reshape`. Si la cantidad de elementos no coincide, se producirá un error.

En resumen, `reshape` es una función útil de `Numpy` que nos permite cambiar la forma de un array sin modificar sus datos. Podemos usar esta función para transformar un array de una dimensión en una matriz o tensor de dos o más dimensiones, y viceversa.

## **Reshape con dimensión desconocida**

En Python, la función `reshape` se utiliza para cambiar la forma `(shape)` de una matriz o un arreglo `(array)` `NumPy` sin alterar sus datos. La función `reshape` permite reorganizar los elementos de la matriz o arreglo `NumPy` en una nueva forma especificada por el usuario.

Cuando utilizamos la función `reshape` en Python, podemos especificar la forma deseada de la nueva matriz o arreglo `NumPy` mediante una `tupla` que contiene las dimensiones de la matriz. A veces, sin embargo, puede haber una dimensión desconocida en la `tupla`. Esto significa que no sabemos exactamente el tamaño que debe tener esa dimensión, y la dejamos como una variable que se puede calcular automáticamente.

Para crear una nueva matriz o arreglo `NumPy` utilizando la función `reshape` con una dimensión desconocida, debemos especificar la forma deseada de la matriz utilizando una `tupla` que contenga un `"-1"` en lugar de la dimensión desconocida. El `"-1"` indica a `NumPy` que debe calcular automáticamente el tamaño de esa dimensión para asegurarse de que todos los elementos de la matriz o arreglo que queremos reorganizar puedan encajar en ella.

A continuación, presentamos un ejemplo de cómo utilizar la función `reshape` en Python con una dimensión desconocida `(-1)`:

In [1]:
import numpy as np

# Creamos un arreglo NumPy de 20 elementos
arr = np.arange(20)

# Utilizamos la función reshape para reorganizar el arreglo en una matriz de 4 filas y una dimensión desconocida en las columnas
matriz = arr.reshape(4, -1)

# Imprimimos la forma (shape) de la nueva matriz
print(matriz.shape)


(4, 5)


En este ejemplo, creamos un arreglo `NumPy` de 20 elementos utilizando la función arange de `NumPy`. Luego, utilizamos la función `reshape` para reorganizar el arreglo en una matriz de 4 filas y una dimensión desconocida en las columnas. Como especificamos `"-1"` como la dimensión desconocida, `NumPy` calcula automáticamente el tamaño de esa dimensión para que todos los 20 elementos del arreglo original puedan encajar en la nueva matriz.

Finalmente, imprimimos la forma `(shape)` de la nueva matriz, que es `(4, 5)`. Esto significa que la nueva matriz tiene `4` filas y `5` columnas, lo que es el tamaño calculado automáticamente por `NumPy` para acomodar todos los elementos del arreglo original.

## **Elementos de un array**

En Python, un array es un tipo de estructura de datos que puede contener elementos de un solo tipo, como números, cadenas de caracteres, booleanos, entre otros. En este contexto, los elementos de un array son los valores que se almacenan en él.

Los elementos de un `array` en Python se pueden acceder y manipular utilizando sus índices. Los índices de un array `NumPy` comienzan en `0` y se extienden hasta la longitud del `array` menos `1`. Para acceder a un elemento específico de un `array` en Python, debemos usar la notación de corchetes y pasar el índice correspondiente.

A continuación, presentamos un ejemplo de cómo acceder a los elementos de un `array` en Python:

In [2]:
import numpy as np

# Creamos un array NumPy de números enteros
arr = np.array([1, 2, 3, 4, 5])

# Accedemos al primer elemento del array
print(arr[0])

# Accedemos al último elemento del array
print(arr[-1])

# Cambiamos el valor del segundo elemento del array
arr[1] = 10

# Imprimimos el array actualizado
print(arr)


1
5
[ 1 10  3  4  5]


En este ejemplo, creamos un `array` `NumPy` de números enteros utilizando la función `array` de `NumPy`. Luego, accedimos al primer elemento del `array` utilizando el índice `0` y lo imprimimos en la consola. También accedimos al último elemento del `array` utilizando el índice `-1`, que indica el último elemento del `array`.

Después, cambiamos el valor del segundo elemento del `array` de `2` a `10` utilizando el índice `1` y asignando el nuevo valor. Finalmente, imprimimos el `array` actualizado utilizando la función `print`.

También podemos acceder a los elementos de un `array` utilizando la notación de `slices` en Python. La notación de `slices` se utiliza para acceder a un rango de elementos de un `array`. Se utiliza una sintaxis similar a la de la notación de corchetes, pero con dos puntos para indicar un rango de índices.

A continuación, presentamos un ejemplo de cómo utilizar la notación de `slices` para acceder a un rango de elementos de un `array` en Python:

In [3]:
import numpy as np

# Creamos un array NumPy de números enteros
arr = np.array([1, 2, 3, 4, 5])

# Accedemos a los primeros tres elementos del array
print(arr[:3])

# Accedemos a los elementos del segundo al cuarto del array
print(arr[1:4])

# Accedemos a los elementos del segundo al último del array con un paso de dos elementos
print(arr[1::2])


[1 2 3]
[2 3 4]
[2 4]


En este ejemplo, creamos un `array` `NumPy` de números enteros utilizando la función `array` de `NumPy`. Luego, utilizamos la notación de `slices` para acceder a diferentes rangos de elementos del `array`. En la primera línea, accedemos a los primeros tres elementos del array utilizando la sintaxis `[:3]`. En la segunda línea, accedemos a los elementos del segundo al cuarto del array utilizando la sintaxis `[1:4]`. En la tercera línea, accedemos a los elementos del segundo al último del array con un paso de dos elementos utilizando la sintaxis `[1::2]`.

En resumen, los elementos de un `array` en Python son los valores que se almacenan en él. Podemos acceder y manipular los elementos de un `array`

## **Concepto de slicing**

En Python, el `slicing` se refiere a la técnica de acceder a un subconjunto de elementos de una secuencia, como una lista, una cadena de caracteres o un array. La sintaxis de `slicing` en Python utiliza los corchetes y dos puntos `[:]` para indicar un rango de elementos que se desea acceder.

La sintaxis general de `slicing` en Python es la siguiente:

`secuencia[inicio:fin:paso]`

donde inicio es el índice del primer elemento en el subconjunto, fin es el índice del primer elemento que no se incluye en el subconjunto y paso es el tamaño del salto que se da entre elementos consecutivos. Todos estos parámetros son opcionales.

A continuación, presentamos algunos ejemplos de cómo utilizar la sintaxis de `slicing` en Python:

In [4]:
# Creamos una lista de números
numeros = [1, 2, 3, 4, 5]

# Accedemos a los primeros dos elementos de la lista
primeros_dos = numeros[:2]
print(primeros_dos) # [1, 2]

# Accedemos a los elementos de la lista desde el tercero hasta el último
desde_el_tercero = numeros[2:]
print(desde_el_tercero) # [3, 4, 5]

# Accedemos a los elementos de la lista desde el segundo al cuarto con un paso de 2
del_segundo_al_cuarto_con_paso_de_2 = numeros[1:4:2]
print(del_segundo_al_cuarto_con_paso_de_2) # [2, 4]


[1, 2]
[3, 4, 5]
[2, 4]


En este ejemplo, creamos una lista de números y utilizamos la sintaxis de `slicing` para acceder a diferentes subconjuntos de elementos de la lista. En la primera línea, accedemos a los primeros dos elementos de la lista utilizando la sintaxis `[:2]`. En la segunda línea, accedemos a los elementos de la lista desde el tercero hasta el último utilizando la sintaxis `[2:]`. En la tercera línea, accedemos a los elementos de la lista desde el segundo al cuarto con un paso de `2` utilizando la sintaxis `[1:4:2]`.

También podemos utilizar la sintaxis de `slicing` en una cadena de caracteres:

In [5]:
# Creamos una cadena de caracteres
texto = "Hola mundo"

# Accedemos a los primeros cuatro caracteres de la cadena
primeros_cuatro = texto[:4]
print(primeros_cuatro) # "Hola"

# Accedemos a los caracteres de la cadena desde el quinto hasta el último
desde_el_quinto = texto[5:]
print(desde_el_quinto) # "mundo"


Hola
mundo


En este ejemplo, creamos una cadena de caracteres y utilizamos la sintaxis de `slicing` para acceder a diferentes subconjuntos de caracteres de la cadena. En la primera línea, accedemos a los primeros cuatro caracteres de la cadena utilizando la sintaxis `[:4]`. En la segunda línea, accedemos a los caracteres de la cadena desde el quinto hasta el último utilizando la sintaxis `[5:]`.

También podemos utilizar la sintaxis de `slicing` en un array `NumPy`:

In [6]:
import numpy as np

# Creamos un array NumPy de números enteros
arr = np.array([1, 2, 3, 4, 5])

# Accedemos a los primeros dos elementos del array
primeros_dos = arr[:2]
print(primeros_dos) # [1, 2]

# Accedemos a los elementos de la lista desde el tercero hasta el último
desde_el_tercero = arr[2:]
print(desde_el_tercero) # [3, 4, 5]

# Accedemos a los elementos de la lista desde el segundo al cuarto con un paso de 2
del_segundo_al_cuarto_con_paso_de_2 = arr[1:4:2]
print(del_segundo_al_cuarto_con_paso_de_2) # [2, 4]


[1 2]
[3 4 5]
[2 4]


En este ejemplo, importamos la librería `NumPy` y creamos un `array` `NumPy` de números enteros utilizando la función `np.array()`. Luego, utilizamos la sintaxis de `slicing` para acceder a diferentes subconjuntos de elementos del `array`. En la primera línea, accedemos a los primeros dos elementos del `array` utilizando la sintaxis `[:2]`. En la segunda línea, accedemos a los elementos del `array` desde el tercero hasta el último utilizando la sintaxis `[2:]`. En la tercera línea, accedemos a los elementos del `array` desde el segundo al cuarto con un paso de `2` utilizando la sintaxis `[1:4:2]`.

## **Filtrando arrays**

Filtrar arrays en Python es una técnica muy útil para seleccionar un subconjunto de elementos que cumplen ciertas condiciones. En Python, esto se puede hacer de varias maneras, pero una de las más comunes es utilizando la función `np.where()` de la librería `NumPy`.

Supongamos que tenemos un `array` `NumPy` de números enteros:

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])


Queremos seleccionar los elementos del `array` que son mayores que `2`. Podemos hacer esto utilizando la función `np.where()` de la siguiente manera:

In [8]:
mayores_que_dos = np.where(arr > 2)
print(mayores_que_dos) # (array([2, 3, 4]),)


(array([2, 3, 4]),)


La función `np.where()` devuelve una tupla que contiene un array con los índices de los elementos que cumplen la condición y una coma después para indicar que es una tupla. En este caso, los elementos del array arr que son mayores que 2 son los elementos en los índices 2, 3 y 4, por lo que `mayores_que_dos` contiene el valor `(array([2, 3, 4]),)`.

Podemos usar la tupla que devuelve `np.where()` para seleccionar los elementos correspondientes del `array` original. Por ejemplo, para obtener un nuevo `array` que contenga solo los elementos mayores que 2, podemos hacer lo siguiente:

In [9]:
nuevo_arr = arr[np.where(arr > 2)]
print(nuevo_arr) # [3, 4, 5]


[3 4 5]


En este caso, utilizamos la sintaxis de indexación de arrays para seleccionar solo los elementos del array original que cumplen la condición. En otras palabras, pasamos los índices devueltos por `np.where()` como argumento para seleccionar los elementos correspondientes del array original.

También es posible combinar varias condiciones utilizando los operadores lógicos `&` `(y)` y `|` `(o)`. Por ejemplo, si queremos seleccionar los elementos del array que son mayores que 2 y menores que 5, podemos hacer lo siguiente:

In [10]:
mayores_que_dos_y_menores_que_cinco = np.where((arr > 2) & (arr < 5))
print(mayores_que_dos_y_menores_que_cinco) # (array([2, 3]),)

nuevo_arr_2 = arr[np.where((arr > 2) & (arr < 5))]
print(nuevo_arr_2) # [3, 4]


(array([2, 3]),)
[3 4]


En este caso, la expresión `(arr > 2)` & `(arr < 5)` devuelve un `array` booleano que indica qué elementos del `array` original cumplen ambas condiciones. Luego, utilizamos `np.where()` para obtener los índices correspondientes y seleccionar los elementos del `array` original.

## **Tipos de datos en numpy**

`NumPy` es una librería muy utilizada en Python para trabajar con arrays multidimensionales y matrices. Ofrece una amplia gama de tipos de datos, algunos de los cuales son similares a los tipos de datos estándar de Python, pero otros son específicos de `NumPy`.

Aquí te presento algunos de los tipos de datos más comunes en `NumPy`, junto con una explicación de lo que representan y algunos ejemplos de cómo se utilizan:

* **int:**

 Este tipo de datos representa números enteros con signo. Se pueden especificar diferentes tamaños de `bits`, como `int8` `(8 bits)`, `int16` `(16 bits)`, `int32` `(32 bits)` e `int64` `(64 bits)`. Por ejemplo:

In [12]:
import numpy as np

x = np.array([1, 2, 3], dtype=np.int32)
y = np.array([1, 2, 3], dtype=np.int64)
print(x,y)

[1 2 3] [1 2 3]


* **float:**

 Este tipo de datos representa números reales con precisión simple o doble. Los tamaños de `bits` comunes incluyen `float16` `(16 bits)`, `float32` `(32 bits)` y `float64` `(64 bits)`. Por ejemplo:

In [14]:
import numpy as np

x = np.array([1.0, 2.0, 3.0], dtype=np.float32)
y = np.array([1.0, 2.0, 3.0], dtype=np.float64)
print(x,y)

[1. 2. 3.] [1. 2. 3.]


* **bool:**

 Este tipo de datos representa valores booleanos, es decir, `True` o `False`. El tamaño de `bits` predeterminado es de `8` `bits`. Por ejemplo:

In [17]:
import numpy as np

x = np.array([True, False, True], dtype=bool)
print(x)

[ True False  True]


In [18]:
import numpy as np

x = np.array([True, False, True], dtype=np.bool_)
print(x)

[ True False  True]


* **complex:**

 Este tipo de datos representa números complejos con precisión simple o doble. Los tamaños de `bits` comunes incluyen `complex64` `(dos floats de 32 bits)` y `complex128` `(dos floats de 64 bits)`. Por ejemplo:

In [19]:
import numpy as np

x = np.array([1+2j, 2+3j, 3+4j], dtype=np.complex64)
y = np.array([1+2j, 2+3j, 3+4j], dtype=np.complex128)
print(x,y)

[1.+2.j 2.+3.j 3.+4.j] [1.+2.j 2.+3.j 3.+4.j]


* **string:**

 Este tipo de datos representa cadenas de texto. Se pueden especificar diferentes tamaños de caracteres, como `S10` `(cadenas de hasta 10 caracteres)` o `U10` `(cadenas de hasta 10 caracteres Unicode)`. Por ejemplo:

In [20]:
import numpy as np

x = np.array(['hola', 'mundo'], dtype=np.string_)
y = np.array(['你好', '世界'], dtype=np.unicode_)
print(x)
print(y)

[b'hola' b'mundo']
['你好' '世界']


* **datetime:**

 Este tipo de datos representa fechas y horas. Se pueden especificar diferentes formatos, como `YYYY-MM-DD` para fechas o `YYYY-MM-DD` `HH:MM:SS` para fechas y horas. Por ejemplo:

In [21]:
import numpy as np

x = np.array(['2022-01-01', '2022-02-01'], dtype=np.datetime64)
y = np.array(['2022-01-01 12:00:00', '2022-02-01 12:00:00'], dtype=np.datetime64)
print(x)
print(y)

['2022-01-01' '2022-02-01']
['2022-01-01T12:00:00' '2022-02-01T12:00:00']


Estos son solo algunos ejemplos de los tipos de datos disponibles en `NumPy`. También hay otros tipos de datos menos comunes, como los tipos de datos estructurados.

## **Copias y views de arrays**

En `NumPy`, cuando se trabaja con arrays, existen dos formas principales de acceder y manipular los datos: a través de copias o a través de vistas. La diferencia entre ambas se encuentra en cómo se almacenan y se acceden a los datos subyacentes del array.

* **Copias:**

 Una copia de un array es una nueva instancia de array que tiene los mismos valores que el array original pero está almacenado en una ubicación de memoria diferente. Al modificar la copia no se afecta el array original. Para crear una copia se puede utilizar la función `copy()`.

**Ejemplo:**

In [22]:
import numpy as np

# Crear un array original
original = np.array([1, 2, 3, 4])

# Crear una copia del array original
copia = original.copy()

# Modificar la copia
copia[0] = 10

# Verificar que la copia ha cambiado y el original no
print("Array original:", original)  # [1 2 3 4]
print("Copia modificada:", copia)  # [10  2  3  4]


Array original: [1 2 3 4]
Copia modificada: [10  2  3  4]


* **Views:**

Una vista de un array es una referencia al mismo bloque de memoria que el array original, pero con una forma o un tipo de datos diferente. Las vistas no ocupan memoria adicional y, por lo tanto, son muy útiles para trabajar con grandes conjuntos de datos.

**Ejemplo:**

In [23]:
import numpy as np

# Crear un array original
original = np.array([[1, 2, 3], [4, 5, 6]])

# Crear una vista de este array
vista = original.reshape((3, 2))

# Modificar la vista
vista[0][1] = 10

# Verificar que la vista ha cambiado y el original también
print("Array original modificado:", original)  # [[ 1 10][ 3  4][ 5  6]]
print("Vista modificada:", vista)  # [[1 10][3 4][5 6]]


Array original modificado: [[ 1 10  3]
 [ 4  5  6]]
Vista modificada: [[ 1 10]
 [ 3  4]
 [ 5  6]]


En este ejemplo, la vista del array se creó con una forma diferente utilizando la función `reshape()`. La vista es una referencia al mismo bloque de memoria que el array original, por lo que cualquier cambio realizado en la vista también afecta al array original.

En resumen, las copias y vistas de arrays son útiles en diferentes situaciones, según se necesite o no crear una nueva instancia de array o se quiera trabajar con un bloque de memoria de manera más eficiente.

## **Arrays y bucles**

Los arrays son una estructura de datos fundamental en `NumPy` que permite almacenar y manipular grandes conjuntos de datos de manera eficiente. A menudo, se utilizan bucles para procesar y manipular datos en un `array`. En Python, los bucles se pueden escribir de varias formas, pero aquí nos centraremos en los bucles `for`.

Un bucle `for` es una estructura de control que permite repetir una sección de código varias veces. En el caso de procesar un `array`, los bucles `for` se utilizan para recorrer los elementos del `array` y realizar alguna operación sobre ellos.

**Ejemplo:**

In [24]:
import numpy as np

# Crear un array
arr = np.array([1, 2, 3, 4, 5])

# Sumar 1 a cada elemento del array usando un bucle for
for i in range(len(arr)):
    arr[i] += 1

# Verificar el array modificado
print(arr)  # [2 3 4 5 6]


[2 3 4 5 6]


En este ejemplo, se crea un `array` de números enteros y se utiliza un bucle `for` para recorrer cada elemento del `array` y sumarle `1`. La función `range()` se utiliza para crear una secuencia de números que se utilizan como índices para acceder a cada elemento del `array`. La función `len()` se utiliza para obtener la longitud del `array`, que se utiliza como límite superior para la secuencia de números.

Otro ejemplo de uso de bucles `for` con arrays es el siguiente:

In [25]:
import numpy as np

# Crear un array de dos dimensiones
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Recorrer el array de dos dimensiones usando dos bucles for
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        arr[i][j] *= 2

# Verificar el array modificado
print(arr)
# [[ 2  4  6]
#  [ 8 10 12]
#  [14 16 18]]


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


En este ejemplo, se crea un `array` de dos dimensiones y se utiliza un par de bucles `for` para recorrer cada elemento del `array` y multiplicarlo por `2`. La función `shape` se utiliza para obtener la forma del `array`, es decir, el número de filas y columnas, que se utilizan como límites superiores para los bucles.

En resumen, los bucles `for` son una herramienta útil para procesar y manipular `arrays` en Python. Se pueden utilizar para recorrer elementos de un `array` y realizar operaciones en ellos de manera iterativa.

## **Bucles con .nditer() y .ndenumerate()**

En `NumPy`, existen dos métodos para recorrer los elementos de un array multidimensional de manera eficiente: `.nditer()` y `.ndenumerate()`.

* **.nditer():**

 Este método devuelve un objeto iterador que puede utilizarse para recorrer los elementos de un array multidimensional de manera eficiente. El método `.nditer()` toma como argumento el array a recorrer y opcionalmente, algunos parámetros que definen cómo se realizará el recorrido. El objeto iterador que se devuelve puede ser utilizado en un bucle `for` para procesar los elementos del array.

**Ejemplo:**

In [26]:
import numpy as np

# Crear un array de dos dimensiones
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Iterar sobre los elementos del array con nditer()
for x in np.nditer(arr):
    print(x)


1
2
3
4
5
6
7
8
9


En este ejemplo, se crea un array de dos dimensiones y se utiliza el método `.nditer()` para recorrer todos los elementos del array de manera eficiente. El bucle `for` recorre los elementos del iterador y los imprime uno por uno.

* **.ndenumerate():**

 Este método es similar al método `.nditer()`, pero devuelve una tupla que contiene la posición del elemento en el array y el propio elemento. El método `.ndenumerate()` también toma como argumento el array a recorrer y opcionalmente, algunos parámetros que definen cómo se realizará el recorrido. El objeto iterador que se devuelve puede ser utilizado en un bucle `for` para procesar los elementos del array junto con sus posiciones.

**Ejemplo:**

In [27]:
import numpy as np

# Crear un array de dos dimensiones
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Iterar sobre los elementos del array con ndenumerate()
for pos, val in np.ndenumerate(arr):
    print(f"El elemento en la posición {pos} es {val}")


El elemento en la posición (0, 0) es 1
El elemento en la posición (0, 1) es 2
El elemento en la posición (0, 2) es 3
El elemento en la posición (1, 0) es 4
El elemento en la posición (1, 1) es 5
El elemento en la posición (1, 2) es 6
El elemento en la posición (2, 0) es 7
El elemento en la posición (2, 1) es 8
El elemento en la posición (2, 2) es 9


En este ejemplo, se crea un array de dos dimensiones y se utiliza el método `.ndenumerate()` para recorrer todos los elementos del array junto con sus posiciones. El bucle `for` recorre los elementos del iterador y los imprime junto con sus posiciones.

En resumen, los métodos `.nditer()` y `.ndenumerate()` son herramientas útiles para recorrer los elementos de un array multidimensional de manera eficiente y con una sintaxis simplificada en comparación con los bucles `for` tradicionales.

## **Concatenación de arrays**

La concatenación de arrays en Python se refiere a la operación de unir dos o más arrays en uno solo, con una forma más grande que contiene los elementos de todos los arrays de entrada. En `NumPy`, existen varias funciones que permiten concatenar arrays, como `concatenate()`, `hstack()`, `vstack()` y `dstack()`.

La función `concatenate()` permite concatenar arrays a lo largo de un eje específico. Los arrays deben tener la misma forma en todas las dimensiones excepto la que se especifica en el parámetro `axis`. La sintaxis general de la función es la siguiente:

`numpy.concatenate((a1, a2, ...), axis=0, out=None)`

donde `a1, a2, ...` son los arrays que se quieren concatenar y `axis` es el eje a lo largo del cual se realiza la concatenación (0 para concatenar verticalmente y 1 para concatenar horizontalmente). El parámetro out especifica el `array` de salida donde se guarda el resultado de la concatenación.

**Ejemplo:**

In [28]:
import numpy as np

# Creamos dos arrays a concatenar
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# Concatenamos los arrays a lo largo del eje 0 (verticalmente)
c = np.concatenate((a, b), axis=0)

print(c)


[[1 2]
 [3 4]
 [5 6]]


Este código imprimirá la matriz `[[1 2], [3 4], [5 6]]`.

La función `hstack()` permite concatenar dos o más arrays horizontalmente, es decir, a lo largo del segundo eje. Los arrays deben tener la misma forma en la primera dimensión. La sintaxis general de la función es la siguiente:

`numpy.hstack(tup)`

donde `tup` es una tupla de arrays que se quieren concatenar horizontalmente.

**Ejemplo:**

In [29]:
import numpy as np

# Creamos dos arrays a concatenar
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Concatenamos los arrays horizontalmente
c = np.hstack((a, b))

print(c)


[1 2 3 4 5 6]


Este código imprimirá el array `[1 2 3 4 5 6]`.

La función `vstack()` permite concatenar dos o más arrays verticalmente, es decir, a lo largo del primer eje. Los arrays deben tener la misma forma en la segunda dimensión. La sintaxis general de la función es la siguiente:

`numpy.vstack(tup)`

donde `tup` es una tupla de arrays que se quieren concatenar verticalmente.

**Ejemplo:**

In [30]:
import numpy as np

# Creamos dos arrays a concatenar
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

# Concatenamos los arrays verticalmente
c = np.vstack((a, b))

print(c)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


Este código imprimirá la matriz `[[1], [2], [3], [4], [5], [6]]`.

Por último, la función `dstack()` permite concatenar dos o más arrays a lo largo del tercer eje. Los arrays deben tener la misma forma en la primera y segunda dimensión. La sintaxis general de la función es la siguiente:

`numpy.dstack(tup)`

`numpy.dstack(tup)` es una función de `NumPy` que se utiliza para apilar arrays en profundidad a lo largo del tercer eje. La función toma como entrada una tupla de arrays y devuelve un solo array tridimensional.

Aquí te dejo un ejemplo de cómo usar la función `numpy.dstack(tup)`:

In [31]:
import numpy as np

# Crear dos arrays de ejemplo
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Apilar los arrays en profundidad
arr_dstack = np.dstack((arr1, arr2))

# Imprimir el resultado
print("Apilamiento en profundidad:\n", arr_dstack)


Apilamiento en profundidad:
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


Este código crea dos arrays de ejemplo `arr1` y `arr2` y luego los apila en profundidad utilizando la función `np.dstack()`. El resultado se almacena en la variable `arr_dstack` y se imprime en pantalla para su visualización. El resultado debería ser un array tridimensional en el que cada elemento corresponde a una fila y columna en los dos arrays originales.

In [32]:
import numpy as np

# Crear dos arrays de ejemplo
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenar verticalmente
arr_v = np.concatenate((arr1, arr2), axis=0)
print("Concatenación vertical:\n", arr_v)

# Concatenar horizontalmente
arr_h = np.concatenate((arr1, arr2), axis=1)
print("Concatenación horizontal:\n", arr_h)


Concatenación vertical:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenación horizontal:
 [[1 2 5 6]
 [3 4 7 8]]


Este código crea dos arrays de ejemplo `arr1` y `arr2` y luego los concatena verticalmente y horizontalmente utilizando la función `np.concatenate()`. La concatenación vertical se realiza utilizando `axis=0`, lo que resulta en la unión de las filas de los dos arrays. La concatenación horizontal se realiza utilizando `axis=1`, lo que resulta en la unión de las columnas de los dos arrays. El resultado de cada concatenación se almacena en una variable separada y se imprime en pantalla para su visualización.

## **Concatenación con el método .stack()**

La función `numpy.stack()` se utiliza para apilar arrays a lo largo de un nuevo eje. A diferencia de la función `numpy.concatenate()`, que une arrays a lo largo de un eje existente, `numpy.stack()` agrega un nuevo eje en la dirección especificada.

Aquí te dejo un ejemplo de cómo usar la función `numpy.stack()`:

In [33]:
import numpy as np

# Crear dos arrays de ejemplo
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Apilar los arrays a lo largo del nuevo eje
arr_stack = np.stack((arr1, arr2))

# Imprimir el resultado
print("Apilamiento con stack:\n", arr_stack)


Apilamiento con stack:
 [[1 2 3]
 [4 5 6]]


Este código crea dos arrays de ejemplo `arr1` y `arr2` y luego los apila a lo largo del nuevo eje utilizando la función `np.stack()`. El resultado se almacena en la variable `arr_stack` y se imprime en pantalla para su visualización. El resultado debería ser un array bidimensional en el que cada elemento corresponde a una fila y columna en los dos arrays originales.

También se puede especificar el eje a lo largo del cual apilar los arrays. Por ejemplo, si se desea apilar los arrays a lo largo del segundo eje, se puede utilizar la siguiente sintaxis:

`arr_stack = np.stack((arr1, arr2), axis=1)`

En este caso, los dos arrays se apilan a lo largo del segundo eje, lo que significa que los elementos correspondientes se colocan en la misma columna del nuevo array. El resultado debería ser un array bidimensional en el que cada elemento corresponde a una fila y columna en los dos arrays originales, pero los elementos de `arr1` y `arr2` están en diferentes columnas.

## **Concatenando por filas, por columnas y por profundidad**

La concatenación de arrays en `NumPy` es una operación muy común en el procesamiento de datos. En `NumPy`, hay varias formas de concatenar arrays, dependiendo de cómo se desee unirlos: por filas, por columnas o por profundidad.

A continuación se explican cada una de estas formas de concatenación con ejemplos:

* **Concatenación por filas**

La concatenación por filas une dos o más arrays a lo largo del eje `0` (el eje vertical) para formar un nuevo array. Para concatenar arrays por filas, se puede utilizar la función `numpy.concatenate()` con el parámetro `axis=0`, o bien la función `numpy.vstack()`.

In [34]:
import numpy as np

# Crear dos arrays de ejemplo
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenar los arrays por filas
arr_concat = np.concatenate((arr1, arr2), axis=0)
arr_vstack = np.vstack((arr1, arr2))

# Imprimir los resultados
print("Concatenación por filas:\n", arr_concat)
print("vstack por filas:\n", arr_vstack)


Concatenación por filas:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
vstack por filas:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


En este ejemplo, se crean dos arrays de ejemplo `arr1` y `arr2`, y luego se concatenan por filas utilizando las funciones `numpy.concatenate()` y `numpy.vstack()`. Los resultados se almacenan en las variables `arr_concat` y `arr_vstack`, y se imprimen en pantalla.

* **Concatenación por columnas**

La concatenación por columnas une dos o más arrays a lo largo del eje `1` (el eje horizontal) para formar un nuevo array. Para concatenar arrays por columnas, se puede utilizar la función `numpy.concatenate()` con el parámetro `axis=1`, o bien la función `numpy.hstack()`.



In [35]:
import numpy as np

# Crear dos arrays de ejemplo
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenar los arrays por columnas
arr_concat = np.concatenate((arr1, arr2), axis=1)
arr_hstack = np.hstack((arr1, arr2))

# Imprimir los resultados
print("Concatenación por columnas:\n", arr_concat)
print("hstack por columnas:\n", arr_hstack)


Concatenación por columnas:
 [[1 2 5 6]
 [3 4 7 8]]
hstack por columnas:
 [[1 2 5 6]
 [3 4 7 8]]


En este ejemplo, se crean dos `arrays` de ejemplo `arr1` y `arr2`, y luego se concatenan por columnas utilizando las funciones `numpy.concatenate()` y `numpy.hstack()`. Los resultados se almacenan en las variables `arr_concat` y `arr_hstack`, y se imprimen en pantalla.

* **Concatenación por profundidad**

La concatenación por profundidad une dos o más `arrays` a lo largo del eje `2` (el eje de profundidad) para formar un nuevo `array`. Para concatenar `arrays` por profundidad, se puede utilizar la función `numpy.dstack()`.

In [36]:
import numpy as np

# Crear dos arrays de ejemplo
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenar los arrays por profundidad
arr_dstack = np.dstack((arr1, arr2))

# Imprimir el resultado
print("Concatenación por profundidad:\n", arr_dstack)


Concatenación por profundidad:
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


En este ejemplo, se han creado dos arrays de ejemplo `arr1` y `arr2` y se han concatenado por profundidad utilizando la función `np.dstack()`. El resultado se almacena en la variable `arr_dstack`. Luego, se imprime el resultado utilizando la función `print()`. La salida muestra que los dos arrays se han concatenado por profundidad y se han apilado uno encima del otro en un nuevo `array` de `3` dimensiones.

## **Dividiendo arrays 1D**

La división de arrays en `NumPy` se refiere a la separación de un `array` en varios `sub-arrays` más pequeños. Esto es útil cuando queremos trabajar con partes específicas de un `array`, o cuando queremos separar un `array` en bloques más pequeños para procesarlo de manera más eficiente.

En este caso, nos centraremos en la división de `arrays 1D`. En `NumPy`, hay varias formas de dividir un `array 1D` en `sub-arrays` más pequeños, a través de las funciones `split()`, `array_split()`, y `hsplit()`.

* La función `split()` divide un `array` en `sub-arrays` de tamaño igual.

* La función `array_split()` divide un `array` en `sub-arrays` de tamaño desigual.

* La función `hsplit()` divide un `array` horizontalmente a lo largo del segundo eje.

A continuación, se muestran ejemplos de cada uno de ellos:

In [39]:
import numpy as np

# Creamos un array de ejemplo
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Dividimos el array en tres sub-arrays de tamaño igual
arr_split = np.split(arr, 3)
print("División con split():\n", arr_split)


División con split():
 [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [40]:
import numpy as np

# Creamos un array de ejemplo
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Dividimos el array en cuatro sub-arrays de tamaño desigual
arr_split = np.array_split(arr, 4)
print("División con array_split():\n", arr_split)

División con array_split():
 [array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [44]:
import numpy as np

# Creamos un array de ejemplo
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Dividimos el array en una matriz de 3x3
arr = arr.reshape(3, 3)

# Dividimos la matriz horizontalmente en tres partes iguales
arr_split = np.hsplit(arr, 3)
print("División con hsplit():\n", arr_split)


División con hsplit():
 [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


En este ejemplo, primero creamos un `array` de ejemplo `arr` de 9 elementos. A continuación, utilizamos la función `split()` para dividir el `array` en 3 `sub-arrays` de tamaño igual. La función `split()` devuelve una lista de los `sub-arrays` resultantes.

Luego, utilizamos la función `array_split()` para dividir el `array` en 4 `sub-arrays` de tamaño desigual. La función `array_split()` también devuelve una lista de los `sub-arrays` resultantes.

Finalmente, utilizamos la función `hsplit()` para dividir el `array` horizontalmente en dos partes iguales. Antes de usar esta función, cambiamos la forma del `array` a una matriz de 3x3 con la función `reshape()`. La función `hsplit()` devuelve una lista de los `sub-arrays` resultantes.

En resumen, la división de `arrays` es una operación útil en `NumPy` que nos permite trabajar con partes específicas de un `array` o procesarlo de manera más eficiente en bloques más pequeños. En este ejemplo, hemos mostrado cómo dividir un `array 1D` en `sub-arrays` más pequeños utilizando las funciones `split()`, `array_split()`, y `hsplit()`.

## **El método .split()**

En Python, el método `.split()` es una función de cadenas que se utiliza para dividir una cadena en una lista de subcadenas, utilizando un separador específico. Por defecto, el separador es el espacio en blanco, pero también se puede especificar otro separador.

La sintaxis del método `.split()` es la siguiente:



`string.split(separador, maxsplit)`

* **string:** la cadena que se va a dividir.
* **separador:** el separador que se va a utilizar para dividir la cadena. Por defecto, es el espacio en blanco.
* **maxsplit:** el número máximo de divisiones que se van a realizar. Si no se especifica, se realizarán todas las divisiones posibles.

Veamos algunos ejemplos:

In [45]:
texto = "Hola, ¿cómo estás? Espero que bien."
palabras = texto.split()
print(palabras)


['Hola,', '¿cómo', 'estás?', 'Espero', 'que', 'bien.']


En este ejemplo, se ha creado una cadena de texto y se ha utilizado el método `.split()` para dividir la cadena en una lista de palabras. Como no se ha especificado un separador, el método ha utilizado el espacio en blanco como separador.

In [46]:
texto = "Hola, ¿cómo estás? Espero que bien."
palabras = texto.split(",")
print(palabras)


['Hola', ' ¿cómo estás? Espero que bien.']


En este ejemplo, se ha utilizado el método `.split()` para dividir la cadena en una lista de palabras utilizando la coma como separador. En este caso, el método ha separado la cadena en dos elementos: "Hola" y "¿cómo estás? Espero que bien."

In [47]:
texto = "Hola, ¿cómo estás? Espero que bien."
palabras = texto.split(" ", 2)
print(palabras)


['Hola,', '¿cómo', 'estás? Espero que bien.']


En este ejemplo, se ha utilizado el método `.split()` para dividir la cadena en una lista de palabras utilizando el espacio en blanco como separador. Sin embargo, se ha especificado que solo se realicen dos divisiones como máximo. Como resultado, se han obtenido tres elementos en la lista: "Hola,", "¿cómo" y "estás? Espero que bien."

## **Dividiendo arrays 2D**

En `Numpy`, es posible dividir un `array 2D` en `sub-arrays` más pequeños a lo largo de las filas o columnas mediante las funciones `split()` y `hsplit()` respectivamente. Estas funciones son similares a las que se usan para dividir `arrays 1D`.

* La función `split()` permite dividir un `array 2D` en `sub-arrays` a lo largo del eje horizontal o vertical. Específicamente, esta función toma dos argumentos: el `array 2D` a dividir y la posición a lo largo del eje especificado donde se realizará la división. El resultado es una lista de `sub-arrays`.

* La función `hsplit()` es similar a `split()`, pero divide el `array` a lo largo del eje horizontal. Esta función toma dos argumentos: el `array 2D` a dividir y el número de `sub-arrays` a crear a lo largo del eje horizontal. El resultado es una lista de `sub-arrays`.

A continuación se muestran algunos ejemplos de cómo se pueden utilizar estas funciones:

In [49]:
import numpy as np

# Creamos un array de ejemplo
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Dividimos el array a lo largo de las filas
arr_split = np.split(arr, 3)
print("División con split():\n", arr_split)


División con split():
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [50]:
import numpy as np

# Creamos un array de ejemplo
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Dividimos el array a lo largo de las columnas
arr_split = np.split(arr, 3, axis=1)
print("División con split() a lo largo de las columnas:\n", arr_split)

División con split() a lo largo de las columnas:
 [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [52]:
import numpy as np

# Creamos un array de ejemplo
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Dividimos el array horizontalmente en tres partes iguales
arr_split = np.hsplit(arr, 3)
print("División con hsplit():\n", arr_split)



División con hsplit():
 [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


El primer ejemplo divide el array `arr` en tres `sub-arrays` a lo largo de las filas. El resultado es una lista de tres `sub-arrays`, cada uno de los cuales contiene una fila del array original:

```
División con split():
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
```

En el segundo ejemplo, se divide el array a lo largo de las columnas en tres `sub-arrays`. El resultado es una lista de tres `sub-arrays`, cada uno de los cuales contiene una columna del array original:

```
División con split() a lo largo de las columnas:
 [array([[1],
        [4],
        [7]]),
  array([[2],
        [5],
        [8]]),
  array([[3],
        [6],
        [9]])]
```

Finalmente, el tercer ejemplo divide el array en dos `sub-arrays` a lo largo del eje horizontal. El resultado es una lista de dos `sub-arrays`, cada uno de los cuales contiene la mitad de las filas del array original:

```
División con hsplit():
 [array([[1, 2],
        [4, 5],
        [7, 8]]),
  array([[3],
        [6],
        [9]])]
```

Es importante tener en cuenta que el número de `sub-arrays` que se pueden crear depende del tamaño del array original y de la posición a lo largo del eje donde se realiza la división. Además, cuando se utiliza la función `split()`, el tamaño de los `sub-arrays` debe ser un divisor del tamaño del array a lo largo del eje especificado.

## **Divisiones por filas, columnas y por profundidad**

Las divisiones por filas, columnas y por profundidad en Python son técnicas de procesamiento de arrays que permiten separar un array en partes más pequeñas a lo largo de un eje específico.

A continuación, se presentan ejemplos de cada tipo de división:

* **División por filas**

La división por filas, también conocida como `"split vertical"`, se refiere a la separación de un array a lo largo de su eje vertical. Esto resulta en dos o más sub-arrays, cada uno con el mismo número de columnas.

Para hacer la división por filas en Python, se utiliza la función `numpy.vsplit()`.

**Ejemplo:**

In [54]:
import numpy as np

# Creamos un array de ejemplo
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Dividimos el array verticalmente en tres partes iguales
arr_split = np.vsplit(arr, 3)

print("División con vsplit():\n", arr_split)


División con vsplit():
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


En este ejemplo, el array `arr` se divide en dos sub-arrays, cada uno con 2 y 1 fila(s) respectivamente.

* **División por columnas**

La división por columnas, también conocida como `"split horizontal"`, se refiere a la separación de un array a lo largo de su eje horizontal. Esto resulta en dos o más sub-arrays, cada uno con el mismo número de filas.

Para hacer la división por columnas en Python, se utiliza la función `numpy.hsplit()`.

**Ejemplo:**

In [57]:
import numpy as np

# Creamos un array de ejemplo con 4 columnas
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Dividimos el array horizontalmente en dos partes iguales
arr_split = np.hsplit(arr, 2)

print("División con hsplit():\n", arr_split)


División con hsplit():
 [array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


En este ejemplo, el array `arr` se divide en dos sub-arrays, cada uno con 3 y 1 columna(s) respectivamente.

* **División por profundidad**

La división por profundidad se refiere a la separación de un array a lo largo de su eje de profundidad. Esto resulta en dos o más sub-arrays, cada uno con el mismo número de filas y columnas, pero con un número diferente de capas.

Para hacer la división por profundidad en Python, se utiliza la función `numpy.dsplit()`.

**Ejemplo:**

In [55]:
import numpy as np

# Creamos un array de ejemplo
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Dividimos el array por profundidad en dos partes iguales
arr_split = np.dsplit(arr, 2)

print("División con dsplit():\n", arr_split)


División con dsplit():
 [array([[[1],
        [3]],

       [[5],
        [7]]]), array([[[2],
        [4]],

       [[6],
        [8]]])]


## **Buscando elementos en un array**

En Python, se pueden buscar elementos en un array utilizando el método `np.where` de la librería `Numpy`, que devuelve los índices de los elementos que cumplan una determinada condición.

Supongamos que tenemos el siguiente array de ejemplo:

In [58]:
import numpy as np

arr = np.array([2, 4, 6, 8, 10])


Para buscar un elemento específico en el array, podemos hacer lo siguiente:

In [59]:
index = np.where(arr == 8)
print(index)


(array([3]),)


Esto devolverá un tuple con el índice del elemento que cumple la condición, en este caso, el número `3`, ya que el elemento `8` se encuentra en la posición `3` del array.

También podemos buscar elementos que cumplan una determinada condición. Por ejemplo, si queremos encontrar los índices de los elementos que son mayores que `5`, podemos hacer lo siguiente:

In [60]:
indices = np.where(arr > 5)
print(indices)


(array([2, 3, 4]),)


Esto devolverá un array con los índices de los elementos que cumplen la condición, en este caso, los elementos `2`, `3`, y `4`.

Además, podemos utilizar la función `np.argwhere` para buscar los índices de los elementos que cumplen una determinada condición de manera más compacta. Por ejemplo, si queremos encontrar los índices de los elementos que son múltiplos de `3`, podemos hacer lo siguiente:

In [61]:
indices = np.argwhere(arr % 3 == 0)
print(indices)


[[2]]


Esto devolverá un array con los índices de los elementos que cumplen la condición, en este caso, los elementos `0`, `2`, y `4`.

## **El método .searchsorted()**

El método `.searchsorted()` es una función que se utiliza para encontrar el índice en el que se debe insertar un elemento en un array ordenado de forma ascendente para que se mantenga el orden del mismo. Si el elemento ya está en el array, la función devuelve el índice correspondiente a ese elemento.

La sintaxis del método es la siguiente:

`numpy.searchsorted(a, v, side='left', sorter=None)`

**donde:**

* **a:** array de entrada, debe estar ordenado de forma ascendente.
* **v:** valor o valores a buscar en el array de entrada.
* **side:** puede ser `'left'` o `'right'`. Si el valor ya está en el array, determina si se devuelve el índice más a la izquierda o más a la derecha.
* **sorter:** objeto que se utiliza para ordenar el array de entrada. Si no se especifica, se utiliza un algoritmo interno para ordenar el array.
Veamos algunos ejemplos:

In [62]:
import numpy as np

# Creamos un array de ejemplo
arr = np.array([2, 3, 6, 7, 9])

# Buscamos el índice en el que se debería insertar el número 4
indice = np.searchsorted(arr, 4)

# Imprimimos el resultado
print(indice) # Devuelve 2, ya que el 4 debería ir en la tercera posición (índice 2) para mantener el orden

# Ahora buscamos el índice en el que se debería insertar el número 7, pero devolviendo el índice más a la derecha
indice2 = np.searchsorted(arr, 7, side='right')

# Imprimimos el resultado
print(indice2) # Devuelve 4, ya que el 7 ya está en el array y el índice más a la derecha es el 4

# También podemos buscar múltiples valores a la vez
indices3 = np.searchsorted(arr, [2, 5, 8])

# Imprimimos el resultado
print(indices3) # Devuelve [0 2 4], que son los índices en los que deberían ir los valores [2, 5, 8] para mantener el orden


2
4
[0 2 4]


En resumen, el método `.searchsorted()` es útil cuando necesitamos buscar valores en un array ordenado y queremos saber en qué posición deberíamos insertar un valor para mantener el orden del mismo.

## **Ordenando arrays**

En Python, es posible ordenar un array utilizando el método `np.sort()` de la biblioteca `NumPy`. Este método ordena un array a lo largo de un eje específico y devuelve una copia ordenada del array original.

El método `np.sort()` tiene varios parámetros opcionales que permiten personalizar el ordenamiento. Por ejemplo, el parámetro `axis` indica el eje a lo largo del cual se ordenará el array. El valor predeterminado es `-1`, lo que significa que se ordenará a lo largo del último eje. El parámetro `kind` indica el tipo de algoritmo de ordenamiento que se utilizará. Los algoritmos disponibles son: `'quicksort'`, `'mergesort'`, `'heapsort'` y `'stable'`. El valor predeterminado es `'quicksort'`. El parámetro order se utiliza para especificar el orden en que se deben ordenar los campos de un array estructurado.

Veamos algunos ejemplos de cómo utilizar `np.sort()`:

In [63]:
import numpy as np

# Creamos un array de ejemplo
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

# Ordenamos el array
arr_sorted = np.sort(arr)

print("Array ordenado:", arr_sorted)


Array ordenado: [1 1 2 3 3 4 5 5 6 9]


En este ejemplo, creamos un array de números enteros desordenados y lo ordenamos con `np.sort()`. El resultado será un nuevo array con los mismos elementos, pero ordenados de menor a mayor.

También podemos ordenar un array multidimensional especificando el eje a lo largo del cual queremos ordenar. Por ejemplo:

In [64]:
import numpy as np

# Creamos un array de ejemplo
arr = np.array([[3, 2, 1], [6, 5, 4], [9, 8, 7]])

# Ordenamos el array a lo largo del segundo eje
arr_sorted = np.sort(arr, axis=1)

print("Array ordenado:", arr_sorted)


Array ordenado: [[1 2 3]
 [4 5 6]
 [7 8 9]]


En este caso, el array original tiene dos ejes, por lo que especificamos el segundo eje `(axis=1)` para ordenar a lo largo de las filas.

Además, `NumPy` proporciona una función llamada `np.argsort()`, que devuelve los índices que ordenarían el array en lugar de ordenar el array en sí. Por ejemplo:

In [65]:
import numpy as np

# Creamos un array de ejemplo
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

# Obtenemos los índices que ordenarían el array
idx = np.argsort(arr)

print("Índices de ordenación:", idx)
print("Array ordenado según los índices:", arr[idx])


Índices de ordenación: [1 3 6 0 9 2 4 8 7 5]
Array ordenado según los índices: [1 1 2 3 3 4 5 5 6 9]


En este ejemplo, utilizamos `np.argsort()` para obtener los índices que ordenarían el array original. Luego, utilizamos estos índices para ordenar el array original sin modificarlo directamente.

## **El módulo random**

El módulo `random` de Python es una biblioteca incorporada que se utiliza para generar números aleatorios. Este módulo proporciona una variedad de funciones para generar números aleatorios, incluidos enteros, flotantes y secuencias aleatorias.

Aquí hay algunos ejemplos de cómo se puede utilizar el módulo `random` en Python:

* **Generar un número entero aleatorio**

Se puede generar un número entero aleatorio utilizando la función `randint()` del módulo `random`. Esta función toma dos argumentos, `a` y `b`, y genera un número entero aleatorio entre `a` y `b` (ambos inclusive).

In [66]:
import random

# Generar un número entero aleatorio entre 1 y 10
numero_aleatorio = random.randint(1, 10)

print(numero_aleatorio)


4


* **Generar un número flotante aleatorio**

Se puede generar un número flotante aleatorio utilizando la función `uniform()` del módulo `random`. Esta función toma dos argumentos, `a` y `b`, y genera un número flotante aleatorio entre `a` y `b` (ambos inclusive).

In [67]:
import random

# Generar un número flotante aleatorio entre 0 y 1
numero_aleatorio = random.uniform(0, 1)

print(numero_aleatorio)


0.7736133076277276


* **Mezclar una lista**

Se puede mezclar una lista utilizando la función `shuffle()` del módulo `random`. Esta función toma una lista como argumento y la reorganiza de forma aleatoria.

In [68]:
import random

# Mezclar una lista de números
numeros = [1, 2, 3, 4, 5]
random.shuffle(numeros)

print(numeros)


[1, 3, 4, 5, 2]


* **Elegir un elemento aleatorio de una lista**

Se puede elegir un elemento aleatorio de una lista utilizando la función `choice()` del módulo `random`. Esta función toma una lista como argumento y devuelve un elemento aleatorio de esa lista.

In [69]:
import random

# Elegir un elemento aleatorio de una lista
nombres = ["Juan", "Pedro", "Luis", "Ana", "María"]
nombre_aleatorio = random.choice(nombres)

print(nombre_aleatorio)


María


Estos son solo algunos ejemplos de cómo se puede utilizar el módulo `random` de Python para generar números y realizar operaciones aleatorias.

## **Arrays aleatorios**

Los arrays aleatorios en Python son arrays que se crean con valores aleatorios generados por la librería `NumPy` a través del módulo `random`. Los arrays aleatorios son útiles en diferentes aplicaciones como la simulación de datos o la creación de ejemplos de prueba.

Para crear un array aleatorio en Python, podemos utilizar la función `random` de `NumPy`, que nos permite especificar la forma del array y el tipo de dato que queremos generar. A continuación, se muestran algunos ejemplos de cómo crear diferentes tipos de arrays aleatorios:

In [70]:
import numpy as np

# Crear un array aleatorio de una dimensión con 5 elementos entre 0 y 1
a = np.random.rand(5)
print(a)

# Crear un array aleatorio de una dimensión con 5 enteros entre 0 y 10
b = np.random.randint(0, 10, size=5)
print(b)

# Crear un array aleatorio de dos dimensiones con 3 filas y 4 columnas
c = np.random.rand(3, 4)
print(c)


[0.50197452 0.84518124 0.11245042 0.61103818 0.58257738]
[5 6 4 0 2]
[[0.68741016 0.79190034 0.84734427 0.74012861]
 [0.55983916 0.02516423 0.30532703 0.23715932]
 [0.86306661 0.82703085 0.95719444 0.64606087]]


* En el primer ejemplo, creamos un array unidimensional de `5` elementos con valores aleatorios entre `0` y `1`. La función `rand()` genera números aleatorios en un rango entre `0` y `1`.

* En el segundo ejemplo, creamos un array unidimensional con `5` enteros aleatorios entre `0` y `10`. La función `randint()` nos permite especificar el rango de los enteros y la cantidad de elementos que queremos generar.

* En el tercer ejemplo, creamos un array de dos dimensiones con `3` filas y `4` columnas con valores aleatorios entre `0` y `1`. La función `rand()` de `NumPy` nos permite crear arrays con diferentes formas y dimensiones.

También podemos utilizar otras funciones de `NumPy` para generar arrays aleatorios con diferentes distribuciones, como la distribución normal o la distribución uniforme.

In [71]:
import numpy as np

# Crear un array aleatorio de una dimensión con 5 elementos con distribución normal
d = np.random.normal(size=5)
print(d)

# Crear un array aleatorio de una dimensión con 5 elementos con distribución uniforme
e = np.random.uniform(size=5)
print(e)


[-0.2464963  -0.14330148 -0.53402006 -0.81862637  0.81174745]
[0.92731465 0.16091234 0.75332673 0.77344194 0.65967971]


* En el primer ejemplo, creamos un array unidimensional de `5` elementos con valores aleatorios generados a partir de la distribución normal. La función `normal()` nos permite especificar el tamaño del array y otros parámetros de la distribución normal.

* En el segundo ejemplo, creamos un array unidimensional con `5` elementos con valores aleatorios generados a partir de la distribución uniforme. La función `uniform()` nos permite especificar el tamaño del array y otros parámetros de la distribución uniforme.

En resumen, los arrays aleatorios en Python son una herramienta útil para generar datos aleatorios para diferentes aplicaciones, y `NumPy` nos ofrece diferentes funciones para crear arrays aleatorios con diferentes distribuciones y formas.

## **Elegir un elemento aleatorio de un array**

En Python, se puede elegir un elemento aleatorio de un array utilizando el módulo `random` de Python y la función `choice` que proporciona este módulo.

La función `choice` toma un array y devuelve un elemento aleatorio del array. Veamos un ejemplo:

In [72]:
import numpy as np
from numpy import random

# Creamos un array de ejemplo
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Elegimos un elemento aleatorio del array
x = random.choice(arr)

# Imprimimos el elemento aleatorio
print(x)


5


En este ejemplo, importamos los módulos `numpy` y `random`. Creamos un array `arr` y luego usamos la función `choice` para elegir un elemento aleatorio del array `arr`. Luego imprimimos el elemento aleatorio usando la función `print`.

Podemos también elegir varios elementos aleatorios del array utilizando el parámetro `size` de la función `choice`. Veamos otro ejemplo:

In [73]:
import numpy as np
from numpy import random

# Creamos un array de ejemplo
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Elegimos tres elementos aleatorios del array
x = random.choice(arr, size=3, replace=False)

# Imprimimos los elementos aleatorios
print(x)


[9 3 1]


En este ejemplo, usamos el parámetro `size` de la función `choice` para elegir tres elementos aleatorios del array `arr`. El parámetro `replace=False` indica que los elementos elegidos no se reemplazarán en el array. Por lo tanto, cada elemento elegido es único. Luego imprimimos los elementos aleatorios usando la función `print`.

En resumen, elegir un elemento aleatorio de un array en Python es fácil con la función `choice` del módulo `random`. También podemos elegir varios elementos aleatorios del array utilizando el parámetro `size` de la función `choice`.

## **Permutaciones aleatorias**

En programación, una permutación aleatoria es una reorganización aleatoria de los elementos de una secuencia. En Python, el módulo `random` proporciona una función para generar permutaciones aleatorias.

La función `random.shuffle()` toma una secuencia (como una lista o un array) y la reorganiza de forma aleatoria, lo que da como resultado una permutación aleatoria. La función modifica la secuencia original en su lugar y no devuelve nada.

Aquí hay un ejemplo que muestra cómo generar una permutación aleatoria de una lista en Python:

In [74]:
import random

my_list = [1, 2, 3, 4, 5]
random.shuffle(my_list)
print(my_list)


[5, 3, 2, 1, 4]


En este ejemplo, primero importamos el módulo `random`. Luego, creamos una lista `my_list` con los números del `1` al `5`. Llamamos a la función `random.shuffle()` y pasamos `my_list` como argumento. La función reorganiza los elementos de `my_list` de forma aleatoria. Finalmente, imprimimos la lista reorganizada.

La salida de este programa será una lista con los mismos elementos que `my_list`, pero en un orden aleatorio:

`[5, 1, 2, 4, 3]`

También es posible generar permutaciones aleatorias de arrays en Python utilizando la función `numpy.random.permutation()`. Esta función toma un array como entrada y devuelve una permutación aleatoria de los elementos del array. Aquí hay un ejemplo:

In [75]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])
random_permutation = np.random.permutation(my_array)
print(random_permutation)


[4 1 3 2 5]


En este ejemplo, importamos el módulo `numpy` con el alias `np`. Luego, creamos un array `my_array` con los números del `1` al `5`. Llamamos a la función `numpy.random.permutation()` y pasamos `my_array` como argumento. La función devuelve una permutación aleatoria de los elementos de `my_array`, que almacenamos en la variable `random_permutation`. Finalmente, imprimimos la permutación aleatoria.

La salida de este programa será un array con los mismos elementos que `my_array`, pero en un orden aleatorio:

`[3 1 4 5 2]`

## **Funciones universales**

En el contexto de `NumPy`, las Funciones Universales `(o UFuncs, por sus siglas en inglés)` son funciones que operan elemento por elemento en los arreglos de `NumPy`, proporcionando una forma rápida y eficiente de realizar operaciones matemáticas y lógicas en matrices y vectores.

Algunos ejemplos de Funciones Universales incluyen:

* **Funciones matemáticas:** `sqrt` (raíz cuadrada), `exp` (exponencial), `sin` (seno), `cos` (coseno), etc.
* **Funciones lógicas:** `logical_and` (AND lógico), `logical_or` (OR lógico), `logical_not` (NOT lógico), etc.
* **Funciones de agregación:** `sum` (suma), `mean` (media), `std` (desviación estándar), `var` (varianza), etc.

La ventaja de utilizar Funciones Universales en `NumPy` es que son altamente optimizadas y están implementadas en `C` o `Fortran`, lo que las hace mucho más rápidas que las funciones equivalentes en Python nativo.

Aquí hay algunos ejemplos de Funciones Universales en acción:

In [76]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Funciones matemáticas
print(np.sqrt(arr))   # Raíz cuadrada de cada elemento
print(np.exp(arr))    # Exponencial de cada elemento
print(np.sin(arr))    # Seno de cada elemento

# Funciones lógicas
print(np.logical_and(arr > 2, arr < 5))   # Elementos que cumplen ambas condiciones
print(np.logical_or(arr < 2, arr > 4))    # Elementos que cumplen al menos una de las condiciones
print(np.logical_not(arr < 3))            # Elementos que no cumplen la condición

# Funciones de agregación
print(np.sum(arr))    # Suma de todos los elementos
print(np.mean(arr))   # Media de todos los elementos
print(np.std(arr))    # Desviación estándar de todos los elementos
print(np.var(arr))    # Varianza de todos los elementos


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[False False  True  True False]
[ True False False False  True]
[False False  True  True  True]
15
3.0
1.4142135623730951
2.0


## **Funciones de aritmética**

En `NumPy`, las funciones de aritmética son una colección de funciones que realizan operaciones aritméticas sobre los elementos de un array. Estas funciones pueden ser aplicadas a los elementos del array de forma elemento a elemento, o para realizar una operación en todo el array.

Algunas de las funciones de aritmética en NumPy son:

* **add():** suma dos arrays
* **subtract():** resta dos arrays
* **multiply():** multiplica dos arrays
* **divide():** divide dos arrays
* **power():** eleva un array a una potencia
* **sqrt():** calcula la raíz cuadrada de un array
* **exp():** calcula el exponencial de un array
* **log():** calcula el logaritmo natural de un array
* **absolute():** devuelve el valor absoluto de los elementos de un array
* **sin(), cos(), tan():** calculan las funciones trigonométricas de un array

A continuación se muestran algunos ejemplos de estas funciones:

In [77]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Suma de dos arrays
c = np.add(a, b)
print(c) # [5 7 9]

# Resta de dos arrays
d = np.subtract(b, a)
print(d) # [3 3 3]

# Multiplicación de dos arrays
e = np.multiply(a, b)
print(e) # [ 4 10 18]

# División de dos arrays
f = np.divide(b, a)
print(f) # [4.  2.5 2. ]

# Potencia de un array
g = np.power(a, 2)
print(g) # [1 4 9]

# Raíz cuadrada de un array
h = np.sqrt(g)
print(h) # [1. 2. 3.]

# Exponencial de un array
i = np.exp(a)
print(i) # [ 2.71828183  7.3890561  20.08553692]

# Logaritmo natural de un array
j = np.log(a)
print(j) # [0.         0.69314718 1.09861229]

# Valor absoluto de los elementos de un array
k = np.absolute(np.array([-1, -2, 3, -4]))
print(k) # [1 2 3 4]

# Funciones trigonométricas
l = np.sin(np.pi/2)
print(l) # 1.0
m = np.cos(np.pi/4)
print(m) # 0.7071067811865476
n = np.tan(np.pi/4)
print(n) # 0.9999999999999999


[5 7 9]
[3 3 3]
[ 4 10 18]
[4.  2.5 2. ]
[1 4 9]
[1. 2. 3.]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[1 2 3 4]
1.0
0.7071067811865476
0.9999999999999999


## **Funciones de redondeo**

Las funciones de redondeo en Python permiten redondear los valores de los elementos de un array a un número determinado de decimales o al número entero más cercano. Las funciones de redondeo se encuentran en el módulo `NumPy` y se aplican a través de la función universal `np.round()`.

La sintaxis de la función de redondeo es la siguiente:

`np.round(a, decimals=0, out=None)`

**Donde:**

* **a:** El array de entrada que se desea redondear.
* **decimals:** El número de decimales a los que se desea redondear. Por defecto, es 0.
* **out:** Opcional. El array de salida donde se guardará el resultado del redondeo. Si no se especifica, se crea un nuevo array.

A continuación se muestran algunos ejemplos de cómo usar la función `np.round()`:

In [78]:
import numpy as np

# Creamos un array de ejemplo
arr = np.array([1.2345, 2.3456, 3.4567])

# Redondeo a 2 decimales
arr_round = np.round(arr, decimals=2)

print(arr_round) # [1.23 2.35 3.46]


[1.23 2.35 3.46]


En este ejemplo, se crea un array con tres elementos con diferentes valores decimales. Luego, se usa la función `np.round()` para redondear cada elemento a dos decimales. El resultado se almacena en un nuevo array llamado `arr_round`, que se imprime en pantalla.

In [79]:
import numpy as np

# Creamos un array de ejemplo
arr = np.array([1.2345, 2.3456, 3.4567])

# Redondeo al número entero más cercano
arr_round = np.round(arr)

print(arr_round) # [1. 2. 3.]


[1. 2. 3.]


En este ejemplo, se usa la misma función `np.round()` para redondear cada elemento del array `arr` al número entero más cercano. El resultado se almacena en un nuevo array llamado `arr_round`, que se imprime en pantalla.

Además de la función `np.round()`, `NumPy` también tiene otras funciones de redondeo como `np.ceil()` para redondear hacia arriba, `np.floor()` para redondear hacia abajo y `np.rint()` para redondear al número entero más cercano.

## **Funciones de sumas y diferencias**

En Python, las funciones de sumas y diferencias se utilizan para realizar cálculos de suma y resta en matrices o arrays de NumPy. Algunas de estas funciones son:

* **numpy.sum():**

 Esta función se utiliza para calcular la suma de los elementos de una matriz o array. Es posible calcular la suma en un eje en particular, si se especifica.

**Ejemplo:**



In [80]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Suma de todos los elementos
print(np.sum(arr))  # Output: 45

# Suma en el eje 0
print(np.sum(arr, axis=0))  # Output: [12 15 18]

# Suma en el eje 1
print(np.sum(arr, axis=1))  # Output: [ 6 15 24]


45
[12 15 18]
[ 6 15 24]


* **numpy.cumsum():**

 Esta función se utiliza para calcular la suma acumulativa de los elementos de una matriz o array. Es posible calcular la suma acumulativa en un eje en particular, si se especifica.

**Ejemplo:**

In [81]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Suma acumulativa de todos los elementos
print(np.cumsum(arr))  # Output: [ 1  3  6 10 15 21 28 36 45]

# Suma acumulativa en el eje 0
print(np.cumsum(arr, axis=0))  # Output: [[ 1  2  3]
                                #          [ 5   7   9]
                                #          [12  15  18]]

# Suma acumulativa en el eje 1
print(np.cumsum(arr, axis=1))  # Output: [[ 1  3  6]
                                #          [ 4  9 15]
                                #          [ 7 15 24]]


[ 1  3  6 10 15 21 28 36 45]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


* **numpy.diff():**

 Esta función se utiliza para calcular la diferencia entre los elementos de una matriz o array. Es posible calcular la diferencia en un eje en particular, si se especifica.

**Ejemplo:**

In [82]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Diferencia entre todos los elementos
print(np.diff(arr))  # Output: [[1 1]
                     #          [1 1]
                     #          [1 1]]

# Diferencia en el eje 0
print(np.diff(arr, axis=0))  # Output: [[3 3 3]
                             #          [3 3 3]]

# Diferencia en el eje 1
print(np.diff(arr, axis=1))  # Output: [[1 1]
                             #          [1 1]
                             #          [1 1]]


[[1 1]
 [1 1]
 [1 1]]
[[3 3 3]
 [3 3 3]]
[[1 1]
 [1 1]
 [1 1]]


## **Funciones de productos**

En Python, las funciones de productos son una categoría de funciones universales que se utilizan para realizar operaciones de multiplicación en matrices y arreglos NumPy. Estas funciones se encuentran en el módulo `NumPy` y se utilizan para realizar cálculos numéricos rápidos y eficientes.

Algunas de las funciones de productos más comunes son:

* **np.prod():** devuelve el producto de los elementos de un array o una matriz.
* **np.dot():** devuelve el producto punto entre dos arrays.
* **np.vdot():** devuelve el producto punto entre dos arrays como si se hubieran aplanado.
* **np.outer():** devuelve el producto externo de dos arrays.
* **np.tensordot():** devuelve el producto tensor entre dos arrays.
* **np.kron():** devuelve el producto Kronecker de dos arrays.

A continuación, se presentan algunos ejemplos de estas funciones:

In [83]:
import numpy as np

# Crear un array de ejemplo
arr = np.array([1, 2, 3])

# Calcular el producto de los elementos del array
producto = np.prod(arr)
print(producto)  # Output: 6

# Crear dos arrays de ejemplo
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

# Calcular el producto punto entre los dos arrays
producto_punto = np.dot(arr1, arr2)
print(producto_punto)  # Output: 11

# Calcular el producto externo entre los dos arrays
producto_externo = np.outer(arr1, arr2)
print(producto_externo)
# Output:
# [[3 4]
#  [6 8]]

# Crear dos matrices de ejemplo
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

# Calcular el producto tensor entre las dos matrices
producto_tensor = np.tensordot(matriz1, matriz2)
print(producto_tensor)
# Output:
# [[19 22]
#  [43 50]]

# Calcular el producto Kronecker entre los dos arrays
producto_kronecker = np.kron(arr1, arr2)
print(producto_kronecker)  # Output: [3 4 6 8]


6
11
[[3 4]
 [6 8]]
70
[3 4 6 8]


En resumen, las funciones de productos en Python son una herramienta poderosa para realizar cálculos de multiplicación en matrices y arreglos `NumPy`, y pueden ser utilizadas para realizar una variedad de operaciones de multiplicación de manera rápida y eficiente.

## **Funciones de logaritmos**

En Python, las funciones de logaritmos se utilizan para calcular el logaritmo de un número en una base determinada. El logaritmo es la función inversa de la exponenciación y se utiliza comúnmente en matemáticas, estadísticas y otras áreas de la ciencia.

Existen varias funciones de logaritmos en Python que se pueden utilizar. Algunas de las funciones más comunes son:

* **log():** esta función se utiliza para calcular el logaritmo natural de un número. Es decir, el logaritmo en base e.
* **log10():** esta función se utiliza para calcular el logaritmo en base 10 de un número.
* **log2():** esta función se utiliza para calcular el logaritmo en base 2 de un número.

A continuación, se presentan algunos ejemplos de cómo utilizar estas funciones en Python:

In [84]:
import math

# Calcular el logaritmo natural de 5
print(math.log(5))

# Calcular el logaritmo en base 10 de 100
print(math.log10(100))

# Calcular el logaritmo en base 2 de 8
print(math.log2(8))


1.6094379124341003
2.0
3.0


También se pueden utilizar las funciones de logaritmos para resolver ecuaciones logarítmicas. Por ejemplo, si se desea resolver la ecuación `log(x) = 2`, se puede utilizar la función `log()` de la siguiente manera:

In [85]:
import math

# Resolver la ecuación log(x) = 2
x = math.exp(2)
print(x)


7.38905609893065


## **Funciones de MCM y MCD**

En matemáticas, el Máximo Común Divisor `(MCD)` y el Mínimo Común Múltiplo `(MCM)` son dos conceptos importantes relacionados con los números enteros. En Python, podemos utilizar el módulo `math` para calcular estos valores.

El Máximo Común Divisor es el número más grande que divide exactamente dos o más números enteros. Podemos calcular el `MCD` utilizando la función `gcd()` del módulo math. Por ejemplo:

In [86]:
import math

a = 60
b = 48

mcd = math.gcd(a, b)

print("El MCD de", a, "y", b, "es:", mcd)


El MCD de 60 y 48 es: 12


El Mínimo Común Múltiplo es el número más pequeño que es un múltiplo común de dos o más números enteros. Podemos calcular el `MCM` utilizando la función `lcm()` del módulo `math`. Por ejemplo:

In [87]:
import math

a = 60
b = 48

mcm = math.lcm(a, b)

print("El MCM de", a, "y", b, "es:", mcm)


El MCM de 60 y 48 es: 240


También podemos calcular el `MCM` de más de dos números enteros utilizando la función `reduce()` del módulo `functools`. Para ello, debemos importar la función `reduce()` y utilizarla junto con la función `lcm()`. Por ejemplo:

In [88]:
import math
from functools import reduce

numeros = [12, 30, 45]

mcm = reduce(lambda x, y: math.lcm(x, y), numeros)

print("El MCM de los números", numeros, "es:", mcm)


El MCM de los números [12, 30, 45] es: 180


En este ejemplo, utilizamos la función `reduce()` para aplicar la función `lcm()` a cada par de elementos de la lista numeros, obteniendo así el `MCM` de todos ellos.

## **Funciones de trigonometría e hiperbólicas**

Las funciones de trigonometría e hiperbólicas en Python se encuentran en el módulo `math`. Estas funciones son útiles para cálculos matemáticos que involucran ángulos y sus correspondientes funciones trigonométricas y hiperbólicas.

Aquí hay algunas funciones comunes de trigonometría e hiperbólicas en Python:

* **math.sin(x):** devuelve el seno de un ángulo en radianes.
* **math.cos(x):** devuelve el coseno de un ángulo en radianes.
* **math.tan(x):** devuelve la tangente de un ángulo en radianes.
* **math.asin(x):** devuelve el arcoseno en radianes de un valor.
* **math.acos(x):** devuelve el arcocoseno en radianes de un valor.
* **math.atan(x):** devuelve el arcotangente en radianes de un valor.
* **math.sinh(x):** devuelve el seno hiperbólico de un número.
* **math.cosh(x):** devuelve el coseno hiperbólico de un número.
* **math.tanh(x):** devuelve la tangente hiperbólica de un número.
* **math.asinh(x):** devuelve el arcoseno hiperbólico de un valor.
* **math.acosh(x):** devuelve el arcocoseno hiperbólico de un valor.
* **math.atanh(x):** devuelve el arcotangente hiperbólico de un valor.

Todos los argumentos para estas funciones deben estar en radianes.

Aquí hay algunos ejemplos de cómo utilizar estas funciones:

In [96]:
import math

# Calcular el seno, coseno y tangente de un ángulo
angulo = math.pi / 4  # 45 grados en radianes
seno = math.sin(angulo)
coseno = math.cos(angulo)
tangente = math.tan(angulo)
print(f"Seno: {seno:.2f}")
print(f"Coseno: {coseno:.2f}")
print(f"Tangente: {tangente:.2f}")

# Calcular el arcoseno y arcocoseno de un valor
valor = 0.5
arcoseno = math.asin(valor)
arcocoseno = math.acos(valor)
print(f"Arcoseno: {arcoseno:.2f}")
print(f"Arcocoseno: {arcocoseno:.2f}")

# Calcular el seno hiperbólico, coseno hiperbólico y tangente hiperbólica de un número
numero = 2
seno_hiperbolico = math.sinh(numero)
coseno_hiperbolico = math.cosh(numero)
tangente_hiperbolica = math.tanh(numero)
print(f"Seno hiperbólico: {seno_hiperbolico:.2f}")
print(f"Coseno hiperbólico: {coseno_hiperbolico:.2f}")
print(f"Tangente hiperbólica: {tangente_hiperbolica:.2f}")


Seno: 0.71
Coseno: 0.71
Tangente: 1.00
Arcoseno: 0.52
Arcocoseno: 1.05
Seno hiperbólico: 3.63
Coseno hiperbólico: 3.76
Tangente hiperbólica: 0.96


## **Conjuntos en numpy**

En `NumPy`, un conjunto es una estructura de datos unidimensional que contiene elementos únicos y desordenados. Es decir, un conjunto no admite elementos duplicados y no tiene ningún orden predefinido de los elementos.

Para trabajar con conjuntos en `NumPy`, se utiliza la función `np.unique()`, que devuelve un array con los elementos únicos de otro array dado, ordenados de manera ascendente por defecto.

Veamos algunos ejemplos:

In [97]:
import numpy as np

# Creamos un array de ejemplo
arr = np.array([1, 3, 5, 3, 7, 1, 9, 5])

# Obtenemos los elementos únicos del array
conjunto = np.unique(arr)

print(conjunto)


[1 3 5 7 9]


Este código crea un array `arr` con algunos elementos repetidos y utiliza la función `np.unique()` para obtener los elementos únicos del array. El resultado es un conjunto con los elementos `[1, 3, 5, 7, 9]`.

También puedes utilizar la función `np.setdiff1d()` para obtener los elementos de un conjunto que no se encuentran en otro conjunto. Por ejemplo:

In [98]:
# Creamos dos arrays de ejemplo
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

# Obtenemos los elementos de a que no están en b
diff = np.setdiff1d(a, b)

print(diff)


[1 2]


En este caso, la función `np.setdiff1d()` devuelve un conjunto con los elementos `[1, 2]`, ya que estos elementos están en a pero no en `b`.

También puedes utilizar la función `np.intersect1d()` para obtener los elementos que se encuentran en ambos conjuntos:

In [99]:
# Creamos dos arrays de ejemplo
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

# Obtenemos los elementos que están en ambos conjuntos
inter = np.intersect1d(a, b)

print(inter)


[3 4]


En este caso, la función `np.intersect1d()` devuelve un conjunto con los elementos `[3, 4]`, ya que estos elementos se encuentran en ambos conjuntos.

Ten en cuenta que los conjuntos en `NumPy` son inmutables, es decir, no se pueden modificar una vez creados. Si necesitas agregar o eliminar elementos de un conjunto, debes convertirlo a otro tipo de estructura de datos, como una lista, realizar la operación y luego volver a convertirlo en un conjunto.

| **Inicio** | **atrás 15** | **Siguiente 17** |
|----------- |-------------- |---------------|
| [🏠](../../README.md) | [⏪](./15.Modulos_de_math_cmath.ipynb)| [⏩](./17.Representacion_grafica.ipynb)|