| **Inicio** | **atrás 15** | **Siguiente 17** |
|----------- |-------------- |---------------|
| [🏠](../../README.md) | [⏪](./15.Modulos_de_math_cmath.ipynb)| [⏩](./17.Representacion_grafica.ipynb)|

# **16. Modulos de Python: Numpy**

## **Introducción a numpy**

Numpy (Numerical Python) es una biblioteca de Python que se utiliza para trabajar con matrices y arrays multidimensionales. Es una de las bibliotecas más utilizadas en el campo de la ciencia de datos y el análisis numérico. Numpy proporciona una gran cantidad de funciones y herramientas para realizar operaciones matemáticas y estadísticas en arrays.

Para utilizar Numpy, primero debemos instalar la biblioteca en nuestro sistema. Podemos hacer esto utilizando pip, el gestor de paquetes de Python. Para instalar Numpy, abrimos una terminal o línea de comandos y ejecutamos el siguiente comando:

`pip install numpy`

Una vez que Numpy está instalado, podemos comenzar a utilizarlo en nuestros programas de Python. Para ello, debemos importar la biblioteca utilizando la siguiente línea de código:

In [1]:
import numpy as np


En este ejemplo, utilizamos la abreviación `"np"` para referirnos a la biblioteca `Numpy` en nuestro programa.

A continuación, mostraremos algunos ejemplos de cómo utilizar `Numpy` para trabajar con arrays multidimensionales.

* **Crear un array**

Podemos crear un array de `Numpy` utilizando la función `np.array()`. Por ejemplo, para crear un array de una dimensión con los números del 0 al 4, podemos escribir lo siguiente:

In [2]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4])

print(arr)  # Salida: [0 1 2 3 4]


[0 1 2 3 4]


También podemos crear un array de dos dimensiones especificando una lista de listas como argumento para `np.array()`. Por ejemplo, para crear una matriz de 2x3 con los números del 0 al 5, podemos escribir lo siguiente:

In [3]:
import numpy as np

arr = np.array([[0, 1, 2], [3, 4, 5]])

print(arr)
# Salida:
# [[0 1 2]
#  [3 4 5]]


[[0 1 2]
 [3 4 5]]


* **Operaciones con arrays**

Podemos realizar operaciones matemáticas con `arrays` utilizando `Numpy`. Por ejemplo, para sumar dos arrays, podemos utilizar la función `np.add()`. En el siguiente ejemplo, sumamos dos arrays de una dimensión:

In [4]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

sum_arr = np.add(arr1, arr2)

print(sum_arr)  # Salida: [5 7 9]


[5 7 9]


También podemos realizar operaciones entre un escalar y un array. En el siguiente ejemplo, multiplicamos cada elemento del array por 2:

In [5]:
import numpy as np

arr = np.array([1, 2, 3])

mult_arr = np.multiply(arr, 2)

print(mult_arr)  # Salida: [2 4 6]


[2 4 6]


* **Funciones estadísticas**

Numpy proporciona una gran cantidad de funciones para realizar operaciones estadísticas en arrays. Por ejemplo, podemos calcular la media, la mediana y la desviación estándar de un array utilizando las funciones `np.mean()`, `np.median()` y `np.std()`, respectivamente.

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)

print("Media:", mean)  # Salida: Media: 3.0
print("Mediana:", median)  # Salida: Mediana: 3.0
print("Desviación estándar:", std_dev)  # Salida: Desviación estándar: 1.4142135623730951


Media: 3.0
Mediana: 3.0
Desviación estándar: 1.4142135623730951


* **Indexación y segmentación**

Podemos acceder a elementos individuales de un array utilizando la indexación de Numpy. Por ejemplo, para acceder al segundo elemento de un array de una dimensión, podemos escribir lo siguiente:

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

second_elem = arr[1]

print(second_elem)  # Salida: 2


2


También podemos acceder a segmentos de un array utilizando la segmentación de Numpy. Por ejemplo, para acceder a los primeros tres elementos de un array de una dimensión, podemos escribir lo siguiente:

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

first_three = arr[:3]

print(first_three)  # Salida: [1 2 3]


[1 2 3]


**Conclusiones**

Numpy es una biblioteca fundamental para cualquier persona que trabaje con datos numéricos en Python. Nos proporciona una gran cantidad de herramientas para trabajar con arrays multidimensionales y realizar operaciones matemáticas y estadísticas en ellos. En esta introducción, hemos visto algunos ejemplos básicos de cómo utilizar Numpy, pero hay muchas más funciones y herramientas disponibles en la biblioteca.

## **Creando arrays con numpy**

Numpy es una de las bibliotecas más utilizadas en Python para trabajar con arreglos, matrices y operaciones matemáticas. Para empezar a trabajar con Numpy, primero debemos importar la biblioteca. Se puede hacer esto con la siguiente línea de código:

In [9]:
import numpy as np


Una vez importada la biblioteca, podemos empezar a crear arreglos con Numpy. Hay varias formas de hacerlo:

1. **Creando un arreglo a partir de una lista**

Podemos crear un arreglo a partir de una lista de Python utilizando la función `array` de Numpy. Por ejemplo:

In [10]:
import numpy as np

lista = [1, 2, 3, 4, 5]
arreglo = np.array(lista)
print(arreglo)


[1 2 3 4 5]


**2. Creando un arreglo de ceros**

Podemos crear un arreglo de ceros utilizando la función `zeros` de Numpy. Por ejemplo, si queremos crear un arreglo de 3 elementos con ceros, podemos hacerlo así:

In [11]:
import numpy as np

arreglo_ceros = np.zeros(3)
print(arreglo_ceros)


[0. 0. 0.]


**3. Creando un arreglo de unos**

Podemos crear un arreglo de unos utilizando la función `ones` de Numpy. Por ejemplo, si queremos crear un arreglo de 4 elementos con unos, podemos hacerlo así:

In [12]:
import numpy as np

arreglo_unos = np.ones(4)
print(arreglo_unos)


[1. 1. 1. 1.]


**4. Creando un arreglo de valores aleatorios**

Podemos crear un arreglo de valores aleatorios utilizando la función `random` de Numpy. Por ejemplo, si queremos crear un arreglo de 5 elementos con valores aleatorios entre 0 y 1, podemos hacerlo así:

In [13]:
import numpy as np

arreglo_aleatorio = np.random.random(5)
print(arreglo_aleatorio)


[0.9061231  0.58983353 0.93040559 0.23636625 0.81672775]


**5. Creando un arreglo de valores espaciados uniformemente**

Podemos crear un arreglo de valores espaciados uniformemente utilizando la función `linspace` de Numpy. Por ejemplo, si queremos crear un arreglo con 5 valores espaciados uniformemente entre 0 y 1, podemos hacerlo así:

In [14]:
import numpy as np

arreglo_uniforme = np.linspace(0, 1, 5)
print(arreglo_uniforme)


[0.   0.25 0.5  0.75 1.  ]


**6. Creando un arreglo de valores espaciados con un paso**

Podemos crear un arreglo de valores espaciados con un paso utilizando la función `arange` de Numpy. Por ejemplo, si queremos crear un arreglo con valores espaciados de 2 en 2 entre 0 y 8, podemos hacerlo así:

In [15]:
import numpy as np

arreglo_paso = np.arange(0, 8, 2)
print(arreglo_paso)


[0 2 4 6]


## **Dimensiones de un array**

En Python, los arrays tienen una o más dimensiones, lo que significa que podemos tener un arreglo de una dimensión (vector) o un arreglo de varias dimensiones (matriz o tensor). Cada dimensión se refiere al número de índices necesarios para acceder a un elemento particular en el arreglo.

Por ejemplo, en un arreglo de dos dimensiones, necesitamos dos índices para acceder a un elemento en particular. En un arreglo de tres dimensiones, necesitamos tres índices para acceder a un elemento en particular, y así sucesivamente.

Para ver las dimensiones de un array en Python, podemos utilizar la función `ndim` de Numpy. Veamos algunos ejemplos:

In [16]:
import numpy as np

# Un arreglo de una dimensión
a = np.array([1, 2, 3])
print(a.ndim) # Salida: 1

# Un arreglo de dos dimensiones
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.ndim) # Salida: 2

# Un arreglo de tres dimensiones
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c.ndim) # Salida: 3


1
2
3


En el primer ejemplo, `a` es un arreglo de una dimensión (vector), por lo que su dimensión es 1. En el segundo ejemplo, `b` es un arreglo de dos dimensiones (matriz), por lo que su dimensión es 2. En el tercer ejemplo, `c` es un arreglo de tres dimensiones (tensor), por lo que su dimensión es 3.

Podemos acceder a cada elemento de un arreglo utilizando sus índices. Por ejemplo, para acceder al segundo elemento de `a`, podemos hacer lo siguiente:

In [17]:
print(a[1]) # Salida: 2


2


Para acceder al elemento (2, 3) en `b`, podemos hacer lo siguiente:

In [18]:
print(b[1, 2]) # Salida: 6


6


Y para acceder al elemento (1, 2, 1) en `c`, podemos hacer lo siguiente:

In [19]:
print(c[1, 0, 1]) # Salida: 6


6


En resumen, las dimensiones de un array en Python nos indican cuántos índices se necesitan para acceder a un elemento en particular en el arreglo. Podemos utilizar la función `ndim` de Numpy para obtener la dimensión de un arreglo y acceder a los elementos del arreglo utilizando sus índices.

## **Shape de un array**

En Python, el `shape` de un array se refiere a la tupla de números que describe el tamaño de cada dimensión del array. Es decir, si tenemos un array de dos dimensiones con una forma `(shape)` de `(3, 4)`, significa que el array tiene tres filas y cuatro columnas.

Para obtener la forma `(shape)` de un array en Python, podemos utilizar la función `shape()` de la librería `Numpy`. Veamos algunos ejemplos:

In [20]:
import numpy as np

# Un arreglo de una dimensión
a = np.array([1, 2, 3])
print(a.shape) # Salida: (3,)

# Un arreglo de dos dimensiones
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape) # Salida: (2, 3)

# Un arreglo de tres dimensiones
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c.shape) # Salida: (2, 2, 2)


(3,)
(2, 3)
(2, 2, 2)


En el primer ejemplo, `a` es un arreglo de una dimensión (vector) con tres elementos, por lo que su forma es `(3,)`. El paréntesis indica que `a` es un vector (unidimensional), y el número dentro del paréntesis indica la cantidad de elementos en ese vector.

En el segundo ejemplo, `b` es un arreglo de dos dimensiones (matriz) con dos filas y tres columnas, por lo que su forma es `(2, 3)`.

En el tercer ejemplo, `c` es un arreglo de tres dimensiones (tensor) con dos niveles, dos filas y dos columnas, por lo que su forma es `(2, 2, 2)`.

Podemos utilizar la forma `(shape)` de un array para acceder a cada elemento utilizando un bucle `for`. Por ejemplo, para recorrer todos los elementos de `b`, podemos hacer lo siguiente:

In [21]:
for i in range(b.shape[0]):
  for j in range(b.shape[1]):
    print(b[i, j])


1
2
3
4
5
6


Este código recorre todos los elementos de `b` utilizando los índices de fila `(i)` y columna `(j)`, y los imprime en la pantalla.

En resumen, el `shape` de un array en Python nos indica el tamaño de cada dimensión del array. Podemos utilizar la función `shape()` de Numpy para obtener la forma de un array y acceder a los elementos del array utilizando un bucle `for` y los índices de fila y columna.

## **Reshape de un array**

En Python, `reshape` es una función de la librería `Numpy` que nos permite cambiar la forma `(shape)` de un array sin modificar sus datos. En otras palabras, podemos reorganizar los elementos de un array en diferentes formas sin alterar su contenido.

La sintaxis básica de `reshape` es la siguiente:

`numpy.reshape(array, newshape, order='C')`

**Donde:**

* **array** es el array que queremos remodelar.

* **newshape** es una tupla que indica la nueva forma deseada para el array.

* **order** es opcional y especifica cómo se deben leer los elementos del array. Puede ser `'C'` para leer los elementos en orden de fila (por defecto) o `'F'` para leer los elementos en orden de columna.

Veamos algunos ejemplos para entender mejor cómo funciona `reshape`:

In [22]:
import numpy as np

# Creamos un array de una dimensión con 12 elementos
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

# Cambiamos la forma del array a una matriz de 3 filas y 4 columnas
b = np.reshape(a, (3, 4))
print(b)
# Salida:
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# Cambiamos la forma del array a una matriz de 4 filas y 3 columnas
c = np.reshape(a, (4, 3))
print(c)
# Salida:
# [[ 0  1  2]
#  [ 3  4  5]
#  [ 6  7  8]
#  [ 9 10 11]]

# Cambiamos la forma del array a una matriz de 2 niveles, 3 filas y 2 columnas
d = np.reshape(a, (2, 3, 2))
print(d)
# Salida:
# [[[ 0  1]
#   [ 2  3]
#   [ 4  5]]

#  [[ 6  7]
#   [ 8  9]
#   [10 11]]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


* En el primer ejemplo, creamos un array de una dimensión con 12 elementos y luego usamos `reshape` para convertirlo en una matriz de 3 filas y 4 columnas.

* En el segundo ejemplo, usamos `reshape` para convertir el mismo array de una dimensión en una matriz de 4 filas y 3 columnas.

* En el tercer ejemplo, usamos `reshape` para convertir el mismo array de una dimensión en un tensor de dos niveles, con tres filas y dos columnas en cada nivel.

Es importante tener en cuenta que el número de elementos en el array original debe ser igual al número de elementos en la forma deseada después de usar `reshape`. Si la cantidad de elementos no coincide, se producirá un error.

En resumen, `reshape` es una función útil de `Numpy` que nos permite cambiar la forma de un array sin modificar sus datos. Podemos usar esta función para transformar un array de una dimensión en una matriz o tensor de dos o más dimensiones, y viceversa.

| **Inicio** | **atrás 15** | **Siguiente 17** |
|----------- |-------------- |---------------|
| [🏠](../../README.md) | [⏪](./15.Modulos_de_math_cmath.ipynb)| [⏩](./17.Representacion_grafica.ipynb)|