| **Inicio** | **atrás 5** | **Siguiente 7** |
|----------- |-------------- |---------------|
| [🏠](../../README.md) | [⏪](./5.Operadores_de_iteracion.ipynb)| [⏩](./7.Estructuras_de_datos_Diccionarios.ipynb)|

# **Estructuras de datos: Listas**

## **Introducción a listas**

 Las listas son una de las estructuras de datos más útiles y versátiles en Python. Básicamente, una lista es una colección ordenada de elementos, donde cada elemento puede ser de cualquier tipo de dato (números, cadenas, booleanos, incluso otras listas).

Para definir una lista en Python, simplemente se encierra una serie de elementos entre corchetes ```[]```, separados por comas. Por ejemplo:

In [1]:
mi_lista = [1, 2, 3, 4, 5]


En este ejemplo, ```mi_lista``` es una lista que contiene los números del 1 al 5. También es posible definir una lista vacía simplemente utilizando corchetes:

In [2]:
mi_lista_vacia = []


Ahora, veamos algunos ejemplos de operaciones comunes que se pueden realizar con listas en Python:

* **Acceder a elementos de una lista**

Podemos acceder a elementos específicos de una lista utilizando índices numéricos. Los índices comienzan en cero, es decir, el primer elemento de la lista se encuentra en el índice 0, el segundo en el índice 1, y así sucesivamente. Por ejemplo:

In [3]:
mi_lista = [1, 2, 3, 4, 5]
print(mi_lista[0])  # imprime 1
print(mi_lista[2])  # imprime 3


1
3


* **Modificar elementos de una lista**

Los elementos de una lista también pueden ser modificados directamente mediante su índice. Por ejemplo:

In [4]:
mi_lista = [1, 2, 3, 4, 5]
mi_lista[0] = 6
print(mi_lista)  # imprime [6, 2, 3, 4, 5]


[6, 2, 3, 4, 5]


* **Agregar elementos a una lista**

Se pueden agregar elementos a una lista utilizando el método ```append()```. Por ejemplo:

In [5]:
mi_lista = [1, 2, 3, 4, 5]
mi_lista.append(6)
print(mi_lista)  # imprime [1, 2, 3, 4, 5, 6]


[1, 2, 3, 4, 5, 6]


También se puede agregar múltiples elementos a la vez utilizando el método ```extend()```, pasando una lista como argumento:

In [6]:
mi_lista = [1, 2, 3, 4, 5]
mi_lista.extend([6, 7, 8])
print(mi_lista)  # imprime [1, 2, 3, 4, 5, 6, 7, 8]


[1, 2, 3, 4, 5, 6, 7, 8]


* **Eliminar elementos de una lista**

Se pueden eliminar elementos de una lista utilizando la palabra clave ```del```, indicando el índice del elemento que se desea eliminar. Por ejemplo:

In [7]:
mi_lista = [1, 2, 3, 4, 5]
del mi_lista[2]
print(mi_lista)  # imprime [1, 2, 4, 5]


[1, 2, 4, 5]


También se puede eliminar el último elemento de la lista utilizando el método ```pop()```:

In [8]:
mi_lista = [1, 2, 3, 4, 5]
mi_lista.pop()
print(mi_lista)  # imprime [1, 2, 3, 4]


[1, 2, 3, 4]


* **Obtener la longitud de una lista**

Se puede obtener la longitud de una lista utilizando la función ```len()```. Por ejemplo:

In [9]:
mi_lista = [1, 2, 3, 4, 5]
print(len(mi_lista))  # imprime 5


5


## **Elementos de una lista**

Los elementos de una lista en Python son los valores que se encuentran almacenados dentro de la lista. Una lista es una estructura de datos que puede contener cualquier tipo de elemento, incluyendo números, cadenas de texto, booleanos, otras listas, entre otros.

A continuación, te muestro algunos ejemplos de elementos de una lista en Python:

In [11]:
# una lista de números
numeros = [1, 2, 3, 4, 5]
print(numeros)

# una lista de cadenas de texto
nombres = ["Juan", "María", "Pedro", "Luisa"]
print(nombres)

# una lista que mezcla distintos tipos de elementos
mezcla = [1, "Hola", True, 2.5, [1, 2, 3]]
print(mezcla)

# una lista vacía
vacia = []
print(vacia)

[1, 2, 3, 4, 5]
['Juan', 'María', 'Pedro', 'Luisa']
[1, 'Hola', True, 2.5, [1, 2, 3]]
[]


En el primer ejemplo, los elementos de la lista son números enteros del 1 al 5. En el segundo ejemplo, los elementos de la lista son cadenas de texto con los nombres de algunas personas. En el tercer ejemplo, los elementos de la lista son una mezcla de distintos tipos de elementos, incluyendo números, cadenas de texto, booleanos, números decimales y otra lista. En el cuarto ejemplo, la lista está vacía y no tiene elementos.

Cabe destacar que en Python, los elementos de una lista pueden ser modificados, agregados o eliminados en cualquier momento después de haber sido creada la lista.

## **Bucles con listas**

Los bucles con listas en Python son una herramienta muy útil para procesar todos los elementos de una lista de forma automatizada. Hay dos tipos de bucles que se utilizan comúnmente con las listas: el bucle ```for``` y el bucle ```while```.

El bucle ```for``` se utiliza para recorrer los elementos de una lista y realizar una acción específica con cada uno de ellos. A continuación, te muestro un ejemplo de cómo usar un bucle ```for``` con una lista:

In [12]:
numeros = [1, 2, 3, 4, 5]

# recorremos la lista y multiplicamos cada elemento por 2
for numero in numeros:
    resultado = numero * 2
    print(resultado)


2
4
6
8
10


En este ejemplo, creamos una lista de números del 1 al 5 y utilizamos un bucle ```for``` para recorrer todos los elementos de la lista. Con cada elemento de la lista, multiplicamos su valor por 2 y luego imprimimos el resultado por pantalla.

El bucle ```while```, por otro lado, se utiliza para recorrer los elementos de una lista hasta que se cumpla una condición específica. A continuación, te muestro un ejemplo de cómo usar un bucle ```while``` con una lista:

En este ejemplo, creamos una lista de números del 1 al 5 y utilizamos un bucle ```while``` para recorrer los elementos de la lista hasta encontrar un número mayor a 3. Con cada elemento de la lista, imprimimos su valor por pantalla y luego aumentamos el índice para pasar al siguiente elemento de la lista.

En resumen, los bucles con listas en Python son una herramienta poderosa para procesar todos los elementos de una lista de forma automatizada, ya sea utilizando un bucle ```for``` o un bucle ```while```.

## **Concatenación y repetición de listas**

La concatenación y repetición de listas en Python son operaciones que nos permiten unir varias listas en una sola o crear una lista que contenga varias copias de la misma lista.

La concatenación de listas se realiza utilizando el operador ```+```. A continuación, te muestro un ejemplo de cómo utilizar la concatenación de listas en Python:

In [13]:
lista1 = [1, 2, 3]
lista2 = [4, 5, 6]

# concatenamos las dos listas
lista_concatenada = lista1 + lista2

print(lista_concatenada)


[1, 2, 3, 4, 5, 6]


En este ejemplo, creamos dos listas, ```lista1``` y ```lista2```, cada una con algunos números. Luego, utilizamos el operador ```+``` para concatenar las dos listas en una nueva lista llamada ```lista_concatenada```. El resultado de la concatenación es una nueva lista que contiene los elementos de las dos listas originales en orden.

La repetición de listas se realiza utilizando el operador ```*```. A continuación, te muestro un ejemplo de cómo utilizar la repetición de listas en Python:

In [14]:
lista_original = [1, 2, 3]

# repetimos la lista tres veces
lista_repetida = lista_original * 3

print(lista_repetida)


[1, 2, 3, 1, 2, 3, 1, 2, 3]


En este ejemplo, creamos una lista llamada ```lista_original``` con algunos números. Luego, utilizamos el operador ```*``` para repetir la lista tres veces en una nueva lista llamada ```lista_repetida```. El resultado de la repetición es una nueva lista que contiene tres copias de la lista original.

En resumen, la concatenación y repetición de listas en Python son operaciones muy útiles para combinar varias listas en una sola o crear varias copias de una lista existente. La concatenación se realiza con el operador ```+``` y la repetición con el operador ```*```.

## **Más métodos de listas**

En Python, existen varios métodos para manipular y modificar listas. A continuación, te mostraré algunos de los métodos más comunes con ejemplos para que puedas comprender su uso y funcionamiento:

* **append()**

El método ```append()``` se utiliza para agregar un elemento al final de una lista. A continuación, te muestro un ejemplo de cómo utilizar este método:

In [15]:
lista = [1, 2, 3]

# agregamos un elemento al final de la lista
lista.append(4)

print(lista)


[1, 2, 3, 4]


En este ejemplo, creamos una lista llamada lista con los números 1, 2 y 3. Luego, utilizamos el método ```append()``` para agregar el número 4 al final de la lista. El resultado es una nueva lista que contiene los números 1, 2, 3 y 4.

* **extend()**

El método ```extend()``` se utiliza para agregar varios elementos al final de una lista. A continuación, te muestro un ejemplo de cómo utilizar este método:

In [16]:
lista1 = [1, 2, 3]
lista2 = [4, 5, 6]

# agregamos los elementos de la lista2 al final de la lista1
lista1.extend(lista2)

print(lista1)


[1, 2, 3, 4, 5, 6]


En este ejemplo, creamos dos listas, lista1 y lista2. Luego, utilizamos el método ```extend()``` para agregar los elementos de lista2 al final de lista1. El resultado es una nueva lista que contiene los elementos de ambas listas, en este caso los números 1, 2, 3, 4, 5 y 6.

* **insert()**

El método ```insert()``` se utiliza para agregar un elemento en una posición específica de una lista. A continuación, te muestro un ejemplo de cómo utilizar este método:

In [17]:
lista = [1, 2, 3]

# insertamos el número 4 en la segunda posición de la lista
lista.insert(1, 4)

print(lista)


[1, 4, 2, 3]


En este ejemplo, creamos una lista llamada lista con los números 1, 2 y 3. Luego, utilizamos el método ```insert()``` para agregar el número 4 en la segunda posición de la lista. El resultado es una nueva lista que contiene los números 1, 4, 2 y 3.

* **remove()**

El método ```remove()``` se utiliza para eliminar el primer elemento de una lista que coincida con un valor específico. A continuación, te muestro un ejemplo de cómo utilizar este método:

In [18]:
lista = [1, 2, 3, 2]

# eliminamos el número 2 de la lista
lista.remove(2)

print(lista)


[1, 3, 2]


En este ejemplo, creamos una lista llamada lista con los números 1, 2, 3 y 2. Luego, utilizamos el método ```remove()``` para eliminar el primer número 2 que encuentre en la lista. El resultado es una nueva lista que contiene los números 1, 3 y 2.

* **pop()**

El método ```pop()``` se utiliza para eliminar un elemento de una lista en una posición específica y devolver ese elemento. A continuación, te muestro un ejemplo de cómo utilizar este método:

In [19]:
lista = [1, 2, 3]

# eliminamos el segundo elemento de la lista y lo guardamos en una variable
elemento_eliminado = lista.pop(1)

print(lista)
print(elemento_eliminado)


[1, 3]
2


* **index()**

El método ```index()``` se utiliza para encontrar el índice de la primera aparición de un elemento en una lista. A continuación, te muestro un ejemplo de cómo utilizar este método:

In [20]:
lista = [1, 2, 3, 4, 5]

# buscamos el índice del número 3 en la lista
indice = lista.index(3)

print(indice)


2


En este ejemplo, creamos una lista llamada lista con los números 1, 2, 3, 4 y 5. Luego, utilizamos el método ```index()``` para buscar el índice del número 3 en la lista. El resultado es el número 2, ya que el número 3 se encuentra en la tercera posición de la lista y los índices en Python empiezan en cero.

* **count()**

El método ```count()``` se utiliza para contar el número de veces que aparece un elemento en una lista. A continuación, te muestro un ejemplo de cómo utilizar este método:

In [21]:
lista = [1, 2, 3, 2, 4, 2]

# contamos cuántas veces aparece el número 2 en la lista
veces = lista.count(2)

print(veces)


3


En este ejemplo, creamos una lista llamada lista con los números 1, 2, 3, 2, 4 y 2. Luego, utilizamos el método ```count()``` para contar cuántas veces aparece el número 2 en la lista. El resultado es el número 3, ya que el número 2 aparece tres veces en la lista.

* **reverse()**

El método ```reverse()``` se utiliza para invertir el orden de los elementos de una lista. A continuación, te muestro un ejemplo de cómo utilizar este método:

In [22]:
lista = [1, 2, 3]

# invertimos el orden de los elementos de la lista
lista.reverse()

print(lista)


[3, 2, 1]


En este ejemplo, creamos una lista llamada lista con los números 1, 2 y 3. Luego, utilizamos el método ```reverse()``` para invertir el orden de los elementos de la lista. El resultado es una nueva lista que contiene los números 3, 2 y 1.

* **sort()**

El método ```sort()``` se utiliza para ordenar los elementos de una lista en orden ascendente. A continuación, te muestro un ejemplo de cómo utilizar este método:

In [23]:
lista = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]

# ordenamos los elementos de la lista en orden ascendente
lista.sort()

print(lista)


[1, 1, 2, 3, 3, 4, 5, 5, 5, 6, 9]


En este ejemplo, creamos una lista llamada lista con varios números desordenados. Luego, utilizamos el método ```sort()``` para ordenar los elementos de la lista en orden ascendente. El resultado es una nueva lista que contiene los números ordenados.

* **clear()**

El método ```clear()``` se utiliza para eliminar todos los elementos de una lista. A continuación, te muestro un ejemplo de cómo utilizar este método:

In [24]:
lista = [1, 2, 3]

# eliminamos todos los elementos de la lista
lista.clear()

print(lista)


[]


En este ejemplo, creamos una lista llamada lista con los números 1, 2 y 3. Luego, utilizamos el método ```clear()``` para eliminar todos

* **copy()**

El método ```copy()``` se utiliza para crear una copia de una lista. A continuación, te muestro un ejemplo de cómo utilizar este método:


In [25]:
lista = [1, 2, 3]

# creamos una copia de la lista
copia = lista.copy()

print(copia)


[1, 2, 3]


En este ejemplo, creamos una lista llamada lista con los números 1, 2 y 3. Luego, utilizamos el método ```copy()``` para crear una copia de la lista. El resultado es una nueva lista que contiene los mismos elementos que la lista original.

## **Conversión a listas**

La conversión a listas en Python se refiere a la capacidad de transformar diferentes tipos de datos en una lista. Existen varias formas de realizar esta conversión en Python, y a continuación te mostraré algunos ejemplos de cómo hacerlo.

* **Conversión de una cadena en una lista:**

Para convertir una cadena en una lista, se utiliza el método ```split()```. Este método separa una cadena en una lista de subcadenas utilizando un delimitador que se especifica como parámetro. A continuación, te muestro un ejemplo de cómo utilizar este método:

In [26]:
cadena = "Hola, ¿cómo estás?"

# separamos la cadena en una lista utilizando la coma como delimitador
lista = cadena.split(",")

print(lista)


['Hola', ' ¿cómo estás?']


En este ejemplo, creamos una cadena llamada cadena con el valor "Hola, ¿cómo estás?". Luego, utilizamos el método ```split()``` para separar la cadena en una lista utilizando la coma como delimitador. El resultado es una lista que contiene dos elementos: "Hola" y " ¿cómo estás?".

* **Conversión de una tupla en una lista:**

Para convertir una tupla en una lista, se utiliza la función ```list()```. A continuación, te muestro un ejemplo de cómo utilizar esta función:

In [27]:
tupla = (1, 2, 3)

# convertimos la tupla en una lista
lista = list(tupla)

print(lista)


[1, 2, 3]


En este ejemplo, creamos una tupla llamada tupla con los valores 1, 2 y 3. Luego, utilizamos la función ```list()``` para convertir la tupla en una lista. El resultado es una lista que contiene los mismos elementos que la tupla.

* **Conversión de un rango en una lista:**

Para convertir un rango en una lista, se utiliza la función ```list()```. A continuación, te muestro un ejemplo de cómo utilizar esta función:

In [28]:
rango = range(1, 6)

# convertimos el rango en una lista
lista = list(rango)

print(lista)


[1, 2, 3, 4, 5]


En este ejemplo, creamos un rango con los valores del 1 al 5 utilizando la función ```range()```. Luego, utilizamos la función ```list()``` para convertir el rango en una lista. El resultado es una lista que contiene los valores del 1 al 5.

* **Conversión de un conjunto en una lista:**

Para convertir un conjunto en una lista, se utiliza la función ```list()```. A continuación, te muestro un ejemplo de cómo utilizar esta función:

In [29]:
conjunto = {1, 2, 3}

# convertimos el conjunto en una lista
lista = list(conjunto)

print(lista)


[1, 2, 3]


En este ejemplo, creamos un conjunto con los valores 1, 2 y 3. Luego, utilizamos la función ```list()``` para convertir el conjunto en una lista. El resultado es una lista que contiene los mismos elementos que el conjunto.

En resumen, la conversión a listas en Python es una operación muy útil que permite transformar diferentes tipos de datos en una estructura de lista para poder manipularlos de manera más fácil y eficiente.

## **Listas anidadas**

Las listas anidadas en Python son listas que contienen otras listas como elementos. Esto significa que se pueden crear listas con estructuras complejas y multidimensionales, lo que resulta muy útil en situaciones en las que se necesitan almacenar datos de forma organizada.

A continuación, te muestro un ejemplo de cómo se puede crear una lista anidada en Python:

In [31]:
lista_anidada = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(lista_anidada)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


En este ejemplo, hemos creado una lista anidada que contiene tres listas, cada una de las cuales tiene tres elementos.

Para acceder a los elementos de una lista anidada, se utilizan índices dobles. El primer índice indica la posición de la lista que se desea acceder, mientras que el segundo índice indica la posición del elemento dentro de esa lista. A continuación, te muestro un ejemplo de cómo acceder a los elementos de una lista anidada:

In [32]:
lista_anidada = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# accedemos al primer elemento de la segunda lista
elemento = lista_anidada[1][0]

print(elemento)


4


En este ejemplo, hemos accedido al primer elemento de la segunda lista de la lista anidada. El resultado es el número 4.

También se pueden utilizar bucles para recorrer los elementos de una lista anidada. A continuación, te muestro un ejemplo de cómo recorrer los elementos de una lista anidada utilizando un bucle ```for```:

In [33]:
lista_anidada = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# recorremos los elementos de la lista anidada
for lista in lista_anidada:
    for elemento in lista:
        print(elemento)


1
2
3
4
5
6
7
8
9


En este ejemplo, hemos utilizado dos bucles ```for``` para recorrer los elementos de la lista anidada. El primer bucle recorre las listas de la lista anidada, y el segundo bucle recorre los elementos de cada una de esas listas. El resultado es la impresión de cada uno de los elementos de la lista anidada.

En resumen, las listas anidadas en Python son una forma útil de almacenar datos de forma estructurada y multidimensional. Se pueden acceder a los elementos de una lista anidada utilizando índices dobles y se pueden recorrer utilizando bucles ```for```.

## **Matrices con listas**

Las matrices son una estructura de datos bidimensional que se utiliza para representar información tabular, como una hoja de cálculo o una imagen. En Python, se pueden utilizar listas anidadas para crear matrices.

A continuación, te muestro un ejemplo de cómo se puede crear una matriz en Python utilizando listas anidadas:

In [34]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


En este ejemplo, hemos creado una matriz de 3x3 con números del 1 al 9.

Para acceder a los elementos de una matriz, se utilizan índices dobles, donde el primer índice indica la fila y el segundo indica la columna. A continuación, te muestro un ejemplo de cómo acceder a los elementos de una matriz:

In [35]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# accedemos al elemento de la fila 2 y columna 1
elemento = matriz[1][0]

print(elemento)


4


En este ejemplo, hemos accedido al elemento de la fila 2 y columna 1 de la matriz. El resultado es el número 4.

También se pueden utilizar bucles para recorrer los elementos de una matriz. A continuación, te muestro un ejemplo de cómo recorrer los elementos de una matriz utilizando dos bucles ```for```:

In [36]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# recorremos los elementos de la matriz
for fila in matriz:
    for elemento in fila:
        print(elemento)


1
2
3
4
5
6
7
8
9


En este ejemplo, hemos utilizado dos bucles for para recorrer los elementos de la matriz. El primer bucle recorre las filas de la matriz, y el segundo bucle recorre los elementos de cada una de esas filas. El resultado es la impresión de cada uno de los elementos de la matriz.

En resumen, las matrices en Python se pueden crear utilizando listas anidadas, y se pueden acceder y recorrer utilizando índices dobles y bucles for. Las matrices son una estructura de datos útil para representar información tabular en programas Python.

## **Matrices con numpy**

```NumPy``` es una biblioteca de Python utilizada para trabajar con matrices y arreglos numéricos de gran tamaño. Una de las características principales de ```NumPy``` es que ofrece una amplia variedad de funciones y métodos para operar con matrices de manera eficiente. En particular, ```NumPy``` ofrece una clase llamada ndarray que es muy útil para trabajar con matrices.

A continuación, te mostraré cómo se pueden crear matrices con ```NumPy``` utilizando la clase ```ndarray``` y cómo se pueden realizar operaciones con ellas:

* **Creación de matrices con NumPy**

Para crear una matriz con ```NumPy```, es necesario importar la biblioteca y utilizar la función ```array()```. A continuación, te muestro un ejemplo de cómo crear una matriz de 3x3 con valores aleatorios:

In [37]:
import numpy as np

matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matriz)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


En este ejemplo, hemos importado ```NumPy``` como ```np```, y hemos creado una matriz de 3x3 con valores del 1 al 9 utilizando la función ```array()```. La matriz resultante se ha guardado en la variable matriz.

* **Operaciones con matrices en NumPy**

Una vez que se ha creado una matriz con ```NumPy```, es posible realizar diferentes operaciones matemáticas con ella utilizando los métodos que ofrece ```NumPy```. A continuación, te muestro algunos ejemplos de operaciones que se pueden realizar con matrices en ```NumPy```:

* **Suma de matrices**

La suma de matrices se puede realizar utilizando el operador ```+```. A continuación, te muestro un ejemplo de cómo sumar dos matrices en ```NumPy```:

In [38]:
import numpy as np

matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

suma = matriz1 + matriz2

print(suma)


[[ 6  8]
 [10 12]]


En este ejemplo, hemos creado dos matrices de 2x2 (matriz1 y matriz2) y las hemos sumado utilizando el operador ```+```. El resultado se ha guardado en la variable suma y se ha impreso por pantalla.

* **Multiplicación de matrices**

La multiplicación de matrices se puede realizar utilizando el método ```dot()```. A continuación, te muestro un ejemplo de cómo multiplicar dos matrices en ```NumPy```:

In [39]:
import numpy as np

matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

multiplicacion = matriz1.dot(matriz2)

print(multiplicacion)


[[19 22]
 [43 50]]


En este ejemplo, hemos creado dos matrices de 2x2 (matriz1 y matriz2) y las hemos multiplicado utilizando el método ```dot()```. El resultado se ha guardado en la variable multiplicacion y se ha impreso por pantalla.

* **Transposición de matrices**

La transposición de una matriz se puede realizar utilizando el método ```T```. A continuación, te muestro un ejemplo de cómo transponer una matriz en ```NumPy```:

In [40]:
import numpy as np

matriz = np.array([[1, 2], [3, 4]])

transpuesta = matriz.T

print(transpuesta)


[[1 3]
 [2 4]]


En este ejemplo, hemos creado una matriz de 2x2 (matriz) y la hemos transpuesto utilizando el método ```T```.

Las matrices en ```NumPy``` son una estructura de datos fundamental para el procesamiento de datos numéricos y científicos. En esencia, una matriz es un arreglo bidimensional de números. ```NumPy``` proporciona una implementación eficiente de matrices y un conjunto completo de funciones para realizar operaciones matriciales.

Para crear una matriz en ```NumPy```, podemos usar la función ```array()```. La sintaxis básica es la siguiente:

In [41]:
import numpy as np

matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matriz)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


En este ejemplo, hemos creado una matriz de tamaño 3x3, que contiene los números del 1 al 9. La función ```array()``` toma una lista de listas como argumento y crea una matriz a partir de ella.

Podemos acceder a los elementos de una matriz utilizando la notación de corchetes. La sintaxis es la misma que para las listas, pero en este caso necesitamos especificar un índice para cada dimensión de la matriz. Por ejemplo:

In [42]:
print(matriz[0][0]) # imprime 1
print(matriz[1][2]) # imprime 6


1
6


También podemos realizar operaciones matriciales con ```NumPy```. Por ejemplo, podemos sumar dos matrices utilizando el operador ```+```:

In [43]:
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])
resultado = matriz1 + matriz2
print(resultado)


[[ 6  8]
 [10 12]]


Además de las operaciones aritméticas básicas, ```NumPy``` proporciona muchas otras funciones para trabajar con matrices. Por ejemplo, podemos calcular la transpuesta de una matriz utilizando la función ```transpose()```:

In [44]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
transpuesta = np.transpose(matriz)
print(transpuesta)


[[1 4]
 [2 5]
 [3 6]]


## **Estructuras de datos: Listas**

Las listas son una estructura de datos muy común en Python. En esencia, una lista es una colección ordenada de elementos, que pueden ser de diferentes tipos, como números, cadenas de caracteres o incluso otras listas. Cada elemento de una lista está identificado por un índice, que comienza en cero.

Para crear una lista en Python, simplemente encierra los elementos de la lista entre corchetes y sepáralos por comas. Por ejemplo:

In [45]:
lista = [1, 2, 3, 4, 5]


En este ejemplo, hemos creado una lista con cinco elementos, que son los números del 1 al 5.

Podemos acceder a los elementos de una lista utilizando la notación de corchetes. Por ejemplo, para acceder al segundo elemento de la lista, podemos usar el índice 1:

In [46]:
print(lista[1]) # imprime 2


2


También podemos modificar los elementos de una lista utilizando la misma notación de corchetes:

In [47]:
lista[0] = 6
print(lista) # imprime [6, 2, 3, 4, 5]


[6, 2, 3, 4, 5]


Además, Python proporciona una serie de funciones para trabajar con listas. Por ejemplo, podemos agregar un elemento al final de una lista utilizando la función ```append()```:

In [48]:
lista.append(6)
print(lista) # imprime [6, 2, 3, 4, 5, 6]


[6, 2, 3, 4, 5, 6]


También podemos insertar un elemento en una posición específica de la lista utilizando la función ```insert()```:

In [49]:
lista.insert(2, 7)
print(lista) # imprime [6, 2, 7, 3, 4, 5, 6]


[6, 2, 7, 3, 4, 5, 6]


Para eliminar un elemento de una lista, podemos utilizar la función ```remove()```:

In [50]:
lista.remove(4)
print(lista) # imprime [6, 2, 7, 3, 5, 6]


[6, 2, 7, 3, 5, 6]


También podemos ordenar los elementos de una lista utilizando la función ```sort()```:

In [51]:
lista.sort()
print(lista) # imprime [2, 3, 5, 6, 6, 7]


[2, 3, 5, 6, 6, 7]


Además de estas funciones básicas, Python proporciona muchas otras funciones para trabajar con listas. Por ejemplo, podemos usar la función ```len()``` para obtener la longitud de una lista, la función ```max()``` para obtener el elemento máximo de una lista, y la función ```min()``` para obtener el elemento mínimo de una lista.

En resumen, las listas son una estructura de datos muy útil en Python para almacenar y manipular colecciones de elementos. Con las funciones proporcionadas por Python, podemos realizar una gran variedad de operaciones en las listas para satisfacer nuestras necesidades de programación.

## **Lists**

Hay cuatro tipos de datos de colección en Python:

* **Lista:** es una colección ordenada y cambiable (modificable). Permite miembros duplicados.
* **Tupla:** es una colección ordenada e inmutable o inmodificable (inmutable). Permite miembros duplicados.
* **Conjunto:** es una colección desordenada, no indexada y no modificable, pero podemos agregar nuevos elementos al conjunto. No se permiten miembros duplicados.
* **Diccionario:** es una colección desordenada, cambiable (modificable) e indexada. No hay miembros duplicados.

Una lista es una colección de diferentes tipos de datos ordenados y modificables (mutables). Una lista puede estar vacía o puede tener diferentes elementos de tipo de datos.

### **Cómo crear una lista**

En Python podemos crear listas de dos formas:

* Uso de la función incorporada de lista

In [52]:
# syntax
lst = list()

In [53]:
empty_list = list() # esta es una lista vacía, no hay ningún elemento en la lista
print(len(empty_list)) # 0

0


* Usando corchetes, []

In [54]:
# syntax
lst = []

In [55]:
empty_list = [] # esta es una lista vacía, no hay ningún elemento en la lista
print(len(empty_list)) # 0

0


Listas con valores iniciales. Usamos ```len()``` para encontrar la longitud de una lista.

In [56]:
fruits = ['banana', 'orange', 'mango', 'lemon']                     # lista de frutas
vegetables = ['Tomato', 'Potato', 'Cabbage','Onion', 'Carrot']      # lista de verduras
animal_products = ['milk', 'meat', 'butter', 'yoghurt']             # lista de productos animales
web_techs = ['HTML', 'CSS', 'JS', 'React','Redux', 'Node', 'MongDB'] # lista de tecnologías web
countries = ['Finland', 'Estonia', 'Denmark', 'Sweden', 'Norway']

# Imprime las listas y su longitud
print('Fruits:', fruits)
print('Number of fruits:', len(fruits))
print('Vegetables:', vegetables)
print('Number of vegetables:', len(vegetables))
print('Animal products:',animal_products)
print('Number of animal products:', len(animal_products))
print('Web technologies:', web_techs)
print('Number of web technologies:', len(web_techs))
print('Countries:', countries)
print('Number of countries:', len(countries))

Fruits: ['banana', 'orange', 'mango', 'lemon']
Number of fruits: 4
Vegetables: ['Tomato', 'Potato', 'Cabbage', 'Onion', 'Carrot']
Number of vegetables: 5
Animal products: ['milk', 'meat', 'butter', 'yoghurt']
Number of animal products: 4
Web technologies: ['HTML', 'CSS', 'JS', 'React', 'Redux', 'Node', 'MongDB']
Number of web technologies: 7
Countries: ['Finland', 'Estonia', 'Denmark', 'Sweden', 'Norway']
Number of countries: 5


* Las listas pueden tener elementos de diferentes tipos de datos

In [57]:
lst = ['Asabeneh', 25, True, {'country':'Finland', 'city':'Helsinki'}] # lista que contiene diferentes tipos de datos
print(lst)

['Asabeneh', 25, True, {'country': 'Finland', 'city': 'Helsinki'}]


### **Acceder a los elementos de la lista mediante la indexación positiva**

Accedemos a cada elemento de una lista utilizando su índice. El índice de una lista comienza desde 0. La siguiente imagen muestra claramente dónde comienza el índice

![indexacion positiva](../imagenes%20Python/list_index.png "indexacion positiva")

In [58]:
fruits = ['banana', 'orange', 'mango', 'lemon']
first_fruit = fruits[0] # estamos accediendo al primer elemento usando su índice
print(first_fruit)      # banana
second_fruit = fruits[1]
print(second_fruit)     # orange
last_fruit = fruits[3]
print(last_fruit) # lemon
# Last index
last_index = len(fruits) - 1
last_fruit = fruits[last_index]

banana
orange
lemon


### **Acceder a los elementos de la lista mediante la indexación negativa**

La indexación negativa significa comenzar desde el final, -1 se refiere al último elemento, -2 se refiere al penúltimo elemento.

![indexacion negativa](../imagenes%20Python/list_negative_indexing.png "indexacion negativa")

In [59]:
fruits = ['banana', 'orange', 'mango', 'lemon']
first_fruit = fruits[-4]
last_fruit = fruits[-1]
second_last = fruits[-2]
print(first_fruit)      # banana
print(last_fruit)       # lemon
print(second_last)      # mango

banana
lemon
mango


### **Desempaquetar elementos de la lista**

In [60]:
lst = ['item','item2','item3', 'item4', 'item5']
first_item, second_item, third_item, *rest = lst
print(first_item)     # item1
print(second_item)    # item2
print(third_item)     # item3
print(rest)           # ['item4', 'item5']


item
item2
item3
['item4', 'item5']


In [61]:
# Primer ejemplo
fruits = ['banana', 'orange', 'mango', 'lemon','lime','apple']
first_fruit, second_fruit, third_fruit, *rest = lst
print(first_fruit)     # banana
print(second_fruit)    # orange
print(third_fruit)     # mango
print(rest)           # ['lemon','lime','apple']

item
item2
item3
['item4', 'item5']


In [62]:
# Segundo ejemplo sobre la lista de desembalaje
first, second, third,*rest, tenth = [1,2,3,4,5,6,7,8,9,10]
print(first)          # 1
print(second)         # 2
print(third)          # 3
print(rest)           # [4,5,6,7,8,9]
print(tenth)          # 10

1
2
3
[4, 5, 6, 7, 8, 9]
10


In [63]:
# Tercer ejemplo sobre la lista de desembalaje
countries = ['Germany', 'France','Belgium','Sweden','Denmark','Finland','Norway','Iceland','Estonia']
gr, fr, bg, sw, *scandic, es = countries
print(gr)
print(fr)
print(bg)
print(sw)
print(scandic)
print(es)

Germany
France
Belgium
Sweden
['Denmark', 'Finland', 'Norway', 'Iceland']
Estonia


### **Slicing elementos de una lista**

* **Indexación positiva:** podemos especificar un rango de índices positivos especificando el inicio, el final y el paso, el valor de retorno será una nueva lista. (valores predeterminados para ```inicio = 0```, ```final = len (lst) - 1 (último elemento)```, ```paso = 1```)

In [64]:
fruits = ['banana', 'orange', 'mango', 'lemon']
all_fruits = fruits[0:4] # devuelve todas las frutas
print(all_fruits)

['banana', 'orange', 'mango', 'lemon']


In [65]:
# esto también dará el mismo resultado que el anterior
all_fruits = fruits[0:] # si no establecemos dónde parar, toma todo el resto
print(all_fruits)
orange_and_mango = fruits[1:3] # no incluye el primer índice
print(orange_and_mango)
orange_mango_lemon = fruits[1:]
print(orange_mango_lemon)
orange_and_lemon = fruits[::2] # aquí usamos un tercer argumento, paso. Tomará cada segundo artículo - ['banana', 'mango']
print(orange_and_lemon)

['banana', 'orange', 'mango', 'lemon']
['orange', 'mango']
['orange', 'mango', 'lemon']
['banana', 'mango']


* **Indexación negativa:** podemos especificar un rango de índices negativos especificando el inicio, el final y el paso, el valor devuelto será una nueva lista.

In [66]:
fruits = ['banana', 'orange', 'mango', 'lemon']
all_fruits = fruits[-4:] # devuelve todas las frutas
print(all_fruits)
orange_and_mango = fruits[-3:-1] # no incluye el último índice,['naranja', 'mango']
print(orange_and_mango)
orange_mango_lemon = fruits[-3:] # esto dará a partir de -3 hasta el final,['naranja', 'mango', 'limón']
print(orange_mango_lemon)
reverse_fruits = fruits[::-1] # un paso negativo tomará la lista en orden inverso,['limón', 'mango', 'naranja', 'plátano']
print(reverse_fruits)

['banana', 'orange', 'mango', 'lemon']
['orange', 'mango']
['orange', 'mango', 'lemon']
['lemon', 'mango', 'orange', 'banana']


### **Modificación de listas**

Lista es una colección ordenada mutable o modificable de elementos. Vamos a modificar la lista de frutas.

In [67]:
fruits = ['banana', 'orange', 'mango', 'lemon']
fruits[0] = 'avocado'
print(fruits)       #  ['avocado', 'orange', 'mango', 'lemon']
fruits[1] = 'apple'
print(fruits)       #  ['avocado', 'apple', 'mango', 'lemon']
last_index = len(fruits) - 1
fruits[last_index] = 'lime'
print(fruits)        #  ['avocado', 'apple', 'mango', 'lime']

['avocado', 'orange', 'mango', 'lemon']
['avocado', 'apple', 'mango', 'lemon']
['avocado', 'apple', 'mango', 'lime']


### **Comprobación de elementos en una lista**

Comprobación de un elemento si es miembro de una lista mediante el operador ```in```. Vea el ejemplo a continuación.

In [68]:
fruits = ['banana', 'orange', 'mango', 'lemon']
does_exist = 'banana' in fruits
print(does_exist)  # True
does_exist = 'lime' in fruits
print(does_exist)  # False

True
False


### **Adición de elementos a una lista**

Para agregar un elemento al final de una lista existente, usamos el método ```append()```.

In [69]:
fruits = ['banana', 'orange', 'mango', 'lemon']
fruits.append('apple')
print(fruits)           # ['banana', 'orange', 'mango', 'lemon', 'apple']
fruits.append('lime')   # ['banana', 'orange', 'mango', 'lemon', 'apple', 'lime']
print(fruits)

['banana', 'orange', 'mango', 'lemon', 'apple']
['banana', 'orange', 'mango', 'lemon', 'apple', 'lime']


### **Insertar elementos en una lista**

Podemos usar el método ```insert()``` para insertar un solo elemento en un índice específico en una lista. Tenga en cuenta que otros elementos se desplazan a la derecha. Los métodos ```insert()``` toman dos argumentos: índice y un elemento para insertar.

In [70]:
fruits = ['banana', 'orange', 'mango', 'lemon']
fruits.insert(2, 'apple') # insertar manzana entre naranja y mango
print(fruits)           # ['banana', 'orange', 'apple', 'mango', 'lemon']
fruits.insert(3, 'lime')   # ['banana', 'orange', 'apple', 'lime', 'mango', 'lemon']
print(fruits)

['banana', 'orange', 'apple', 'mango', 'lemon']
['banana', 'orange', 'apple', 'lime', 'mango', 'lemon']


### **Eliminación de elementos de una lista**

El método de eliminación elimina un elemento específico de una lista

In [71]:
fruits = ['banana', 'orange', 'mango', 'lemon', 'banana']
fruits.remove('banana')
print(fruits)  # ['orange', 'mango', 'lemon', 'banana'] - este método elimina la primera aparición del elemento en la lista
fruits.remove('lemon')
print(fruits)  # ['orange', 'mango', 'banana']

['orange', 'mango', 'lemon', 'banana']
['orange', 'mango', 'banana']


### **Eliminación de elementos mediante Pop**

El método ```pop()``` elimina el índice especificado (o el último elemento si no se especifica el índice):

In [72]:
fruits = ['banana', 'orange', 'mango', 'lemon']
fruits.pop()
print(fruits)       # ['banana', 'orange', 'mango']

fruits.pop(0)
print(fruits)       # ['orange', 'mango']

['banana', 'orange', 'mango']
['orange', 'mango']


### **Eliminación de elementos mediante Del**

La palabra clave del elimina el índice especificado y también se puede usar para eliminar elementos dentro del rango del índice. También puede eliminar la lista por completo.

In [73]:
fruits = ['banana', 'orange', 'mango', 'lemon', 'kiwi', 'lime']
del fruits[0]
print(fruits)       # ['orange', 'mango', 'lemon', 'kiwi', 'lime']
del fruits[1]
print(fruits)       # ['orange', 'lemon', 'kiwi', 'lime']
del fruits[1:3]     # esto elimina los elementos entre los índices dados, ¡así que no elimina el elemento con el índice 3!
print(fruits)       # ['orange', 'lime']
del fruits
#print(fruits)       # Esto debería dar: NameError: el nombre 'frutas' no está definido

['orange', 'mango', 'lemon', 'kiwi', 'lime']
['orange', 'lemon', 'kiwi', 'lime']
['orange', 'lime']


### **Elementos de la lista de compensación**

El método ```clear()``` vacía la lista:

In [74]:
fruits = ['banana', 'orange', 'mango', 'lemon']
fruits.clear()
print(fruits)       # []

[]


### **Copiar una lista**

Es posible copiar una lista reasignándola a una nueva variable de la siguiente forma: ```lista2 = lista1```. Ahora, ```list2``` es una referencia de ```list1```, cualquier cambio que hagamos en ```list2``` también modificará el original, ```list1```. Pero hay muchos casos en los que no nos gusta modificar el original sino que nos gusta tener una copia diferente. Una forma de evitar el problema anterior es usar ```copy()```.

In [75]:
fruits = ['banana', 'orange', 'mango', 'lemon']
fruits_copy = fruits.copy()
print(fruits_copy)       # ['banana', 'orange', 'mango', 'lemon']

['banana', 'orange', 'mango', 'lemon']


### **Unirse a listas**

Hay varias formas de unir o concatenar dos o más listas en Python.

* Operador más (+)

In [76]:
positive_numbers = [1, 2, 3, 4, 5]
zero = [0]
negative_numbers = [-5,-4,-3,-2,-1]
integers = negative_numbers + zero + positive_numbers
print(integers) # [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5]
fruits = ['banana', 'orange', 'mango', 'lemon']
vegetables = ['Tomato', 'Potato', 'Cabbage', 'Onion', 'Carrot']
fruits_and_vegetables = fruits + vegetables
print(fruits_and_vegetables ) # ['banana', 'orange', 'mango', 'lemon', 'Tomato', 'Potato', 'Cabbage', 'Onion', 'Carrot']

[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5]
['banana', 'orange', 'mango', 'lemon', 'Tomato', 'Potato', 'Cabbage', 'Onion', 'Carrot']


* Unirse usando el método ```extend()``` El método ```extend()``` permite agregar una lista en una lista. Vea el ejemplo a continuación.

In [77]:
num1 = [0, 1, 2, 3]
num2= [4, 5, 6]
num1.extend(num2)
print('Numbers:', num1) # Numbers: [0, 1, 2, 3, 4, 5, 6]
negative_numbers = [-5,-4,-3,-2,-1]
positive_numbers = [1, 2, 3,4,5]
zero = [0]

negative_numbers.extend(zero)
negative_numbers.extend(positive_numbers)
print('Integers:', negative_numbers) # Integers: [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5]
fruits = ['banana', 'orange', 'mango', 'lemon']
vegetables = ['Tomato', 'Potato', 'Cabbage', 'Onion', 'Carrot']
fruits.extend(vegetables)
print('Fruits and vegetables:', fruits ) # Fruits and vegetables: ['banana', 'orange', 'mango', 'lemon', 'Tomato', 'Potato', 'Cabbage', 'Onion', 'Carrot']

Numbers: [0, 1, 2, 3, 4, 5, 6]
Integers: [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5]
Fruits and vegetables: ['banana', 'orange', 'mango', 'lemon', 'Tomato', 'Potato', 'Cabbage', 'Onion', 'Carrot']


### **Contar elementos en una lista**

El método ```count()``` devuelve el número de veces que aparece un elemento en una lista:

In [78]:
fruits = ['banana', 'orange', 'mango', 'lemon']
print(fruits.count('orange'))   # 1
ages = [22, 19, 24, 25, 26, 24, 25, 24]
print(ages.count(24))           # 3

1
3


### **Encontrar el índice de un elemento**

El método ```index()``` devuelve el índice de un elemento de la lista:

In [79]:
fruits = ['banana', 'orange', 'mango', 'lemon']
print(fruits.index('orange'))   # 1
ages = [22, 19, 24, 25, 26, 24, 25, 24]
print(ages.index(24))           # 2, la primera ocurrencia

1
2


### **Invertir una lista**

El método ```reverse()``` invierte el orden de una lista.

In [80]:
fruits = ['banana', 'orange', 'mango', 'lemon']
fruits.reverse()
print(fruits) # ['lemon', 'mango', 'orange', 'banana']
ages = [22, 19, 24, 25, 26, 24, 25, 24]
ages.reverse()
print(ages) # [24, 25, 24, 26, 25, 24, 19, 22]

['lemon', 'mango', 'orange', 'banana']
[24, 25, 24, 26, 25, 24, 19, 22]


### **Clasificación de elementos de la lista**

Para ordenar listas, podemos usar el método ```sort()``` o las funciones integradas ```sorted()```. El método ```sort()``` reordena los elementos de la lista en orden ascendente y modifica la lista original. Si un argumento del método ```sort()``` reverse es igual a verdadero, ordenará la lista en orden descendente.

* **sort():** este método modifica la lista original

In [81]:
fruits = ['banana', 'orange', 'mango', 'lemon']
fruits.sort()
print(fruits)             # sorted in alphabetical order, ['banana', 'lemon', 'mango', 'orange']
fruits.sort(reverse=True)
print(fruits) # ['orange', 'mango', 'lemon', 'banana']
ages = [22, 19, 24, 25, 26, 24, 25, 24]
ages.sort()
print(ages) #  [19, 22, 24, 24, 24, 25, 25, 26]

ages.sort(reverse=True)
print(ages) #  [26, 25, 25, 24, 24, 24, 22, 19]

['banana', 'lemon', 'mango', 'orange']
['orange', 'mango', 'lemon', 'banana']
[19, 22, 24, 24, 24, 25, 25, 26]
[26, 25, 25, 24, 24, 24, 22, 19]


* **sorted():** devuelve la lista ordenada sin modificar la lista original

In [82]:
fruits = ['banana', 'orange', 'mango', 'lemon']
print(sorted(fruits))   # ['banana', 'lemon', 'mango', 'orange']
# Orden inverso
fruits = ['banana', 'orange', 'mango', 'lemon']
fruits = sorted(fruits,reverse=True)
print(fruits)     # ['orange', 'mango', 'lemon', 'banana']

['banana', 'lemon', 'mango', 'orange']
['orange', 'mango', 'lemon', 'banana']


| **Inicio** | **atrás 5** | **Siguiente 7** |
|----------- |-------------- |---------------|
| [🏠](../../README.md) | [⏪](./5.Operadores_de_iteracion.ipynb)| [⏩](./7.Estructuras_de_datos_Diccionarios.ipynb)|