| **Inicio**| **Siguiente 2** |
|----------- |-------------- |
| [🏠](../../../README.md) | [⏩](./2.INTRODUCCION_A_PANDAS.ipynb)|

# **1. INTRODUCCIÓN A NUMPY**

## **Creación y tratamiento de arrays en Numpy**

NumPy es una biblioteca en Python que proporciona soporte para trabajar con matrices multidimensionales, conocidas como arrays. Los arrays de NumPy son eficientes en términos de almacenamiento y procesamiento, lo que los convierte en una herramienta poderosa para el análisis de datos y la computación científica. A continuación, te proporcionaré una explicación detallada sobre la creación y tratamiento de arrays en NumPy, junto con ejemplos ilustrativos.

* **Creación de arrays:**

Para crear un array en NumPy, puedes utilizar la función `np.array()` y pasar una lista o tupla como argumento. Por ejemplo:

In [1]:
import numpy as np

# Crear un array unidimensional
arr1 = np.array([1, 2, 3, 4, 5])

# Crear un array bidimensional
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

* **Propiedades de los arrays:**

Una vez creado un array, puedes acceder a diversas propiedades y atributos para obtener información sobre su forma, tamaño y tipo de datos. Algunos ejemplos de estas propiedades son:

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Obtener la forma del array
print(arr.shape)  # Salida: (5,)

# Obtener el número de dimensiones del array
print(arr.ndim)  # Salida: 1

# Obtener el tamaño total del array
print(arr.size)  # Salida: 5

# Obtener el tipo de datos del array
print(arr.dtype)  # Salida: int64

(5,)
1
5
int64


* **Operaciones con arrays:**

NumPy proporciona una amplia gama de operaciones para trabajar con arrays. Puedes realizar operaciones aritméticas, funciones matemáticas, operaciones lógicas y muchas otras. Estas operaciones se aplican elemento a elemento en el array. Aquí hay algunos ejemplos:

In [3]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Operaciones aritméticas
arr_sum = arr1 + arr2  # Suma de arrays
arr_mul = arr1 * arr2  # Multiplicación de arrays

# Funciones matemáticas
arr_sqrt = np.sqrt(arr1)  # Raíz cuadrada de los elementos del array
arr_exp = np.exp(arr2)  # Exponencial de los elementos del array

# Operaciones lógicas
arr_greater = arr1 > arr2  # Comparación elemento a elemento

# Operaciones de reducción
arr_sum_total = np.sum(arr1)  # Suma de todos los elementos del array
arr_mean = np.mean(arr2)  # Media de los elementos del array

* **Indexación y segmentación de arrays:**

Puedes acceder y manipular elementos individuales de un array utilizando la indexación. NumPy también permite segmentar un array para obtener subconjuntos de elementos. Aquí hay algunos ejemplos:

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Acceder a un elemento individual
print(arr[0])  # Salida: 1

# Acceder a un rango de elementos
print(arr[2:5])  # Salida: [3 4 5]

# Segmentar con pasos
print(arr[1:9:2])  # Salida: [2 4 6 8]

1
[3 4 5]
[2 4 6 8]


Estos son solo algunos ejemplos básicos de la creación y tratamiento de arrays en NumPy. La biblioteca proporciona muchas más funcionalidades y operaciones avanzadas para el procesamiento eficiente de datos y cálculos científicos.

## **Operadores aritméticos en Numpy**

NumPy es una biblioteca en Python que ofrece un amplio conjunto de funciones y operadores para realizar operaciones aritméticas en arrays multidimensionales. Estos operadores aritméticos permiten realizar cálculos elemento a elemento en los arrays, facilitando el procesamiento numérico eficiente. A continuación, te proporcionaré una explicación detallada de los operadores aritméticos en NumPy, junto con ejemplos ilustrativos.

* **Suma (+):**

El operador de suma se utiliza para sumar dos arrays o para sumar un escalar a un array. La suma se realiza elemento a elemento en los arrays. Por ejemplo:

In [5]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Suma de arrays
arr_sum = arr1 + arr2
print(arr_sum)  # Salida: [5 7 9]

# Suma de un escalar a un array
arr_sum_scalar = arr1 + 10
print(arr_sum_scalar)  # Salida: [11 12 13]

[5 7 9]
[11 12 13]


* **Resta (-):**

El operador de resta se utiliza para restar un array de otro array o para restar un escalar de un array. Al igual que la suma, la resta se realiza elemento a elemento en los arrays. Por ejemplo:

In [6]:
import numpy as np

arr1 = np.array([4, 5, 6])
arr2 = np.array([1, 2, 3])

# Resta de arrays
arr_diff = arr1 - arr2
print(arr_diff)  # Salida: [3 3 3]

# Resta de un escalar a un array
arr_diff_scalar = arr1 - 2
print(arr_diff_scalar)  # Salida: [2 3 4]

[3 3 3]
[2 3 4]


* **Multiplicación (*):**

El operador de multiplicación se utiliza para multiplicar dos arrays o para multiplicar un array por un escalar. Nuevamente, la multiplicación se realiza elemento a elemento en los arrays. Por ejemplo:

In [7]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Multiplicación de arrays
arr_prod = arr1 * arr2
print(arr_prod)  # Salida: [4 10 18]

# Multiplicación de un escalar por un array
arr_prod_scalar = arr1 * 3
print(arr_prod_scalar)  # Salida: [3 6 9]

[ 4 10 18]
[3 6 9]


* **División (/):**

El operador de división se utiliza para dividir un array por otro array o para dividir un array por un escalar. Al igual que las operaciones anteriores, la división se realiza elemento a elemento en los arrays. Por ejemplo:

In [8]:
import numpy as np

arr1 = np.array([6, 8, 10])
arr2 = np.array([2, 2, 5])

# División de arrays
arr_div = arr1 / arr2
print(arr_div)  # Salida: [3. 4. 2.]

# División de un array por un escalar
arr_div_scalar = arr1 / 2
print(arr_div_scalar)  # Salida: [3. 4. 5.]

[3. 4. 2.]
[3. 4. 5.]


Estos son solo algunos ejemplos de los operadores aritméticos disponibles en NumPy. Además de estos operadores básicos, NumPy también proporciona operadores para realizar operaciones de exponenciación, raíz cuadrada, redondeo, entre otros. Estos operadores y funciones adicionales amplían la funcionalidad de NumPy y permiten realizar cálculos más complejos en arrays multidimensionales.

## **Funciones universales en Numpy**

En NumPy, las funciones universales, comúnmente conocidas como "`ufuncs`", son funciones que operan elemento a elemento en arrays multidimensionales. Estas funciones proporcionan operaciones matemáticas y estadísticas rápidas y eficientes en los arrays de NumPy. A continuación, te proporcionaré una explicación detallada de las funciones universales en NumPy, junto con ejemplos ilustrativos.

* **Funciones matemáticas:**

NumPy proporciona una amplia gama de funciones matemáticas para realizar cálculos en arrays. Algunas de las funciones matemáticas más comunes son:

**np.sin():** Calcula el seno de cada elemento en el array.

**np.cos():** Calcula el coseno de cada elemento en el array.

**np.exp():** Calcula la exponencial de cada elemento en el array.

**np.log():** Calcula el logaritmo natural de cada elemento en el array.

In [9]:
import numpy as np

arr = np.array([0, np.pi/2, np.pi])

# Seno de cada elemento
sin_arr = np.sin(arr)
print(sin_arr)  # Salida: [0.         1.         1.2246468e-16]

# Coseno de cada elemento
cos_arr = np.cos(arr)
print(cos_arr)  # Salida: [ 1.000000e+00  6.123234e-17 -1.000000e+00]

# Exponencial de cada elemento
exp_arr = np.exp(arr)
print(exp_arr)  # Salida: [ 1.          4.81047738 23.14069263]

# Logaritmo natural de cada elemento
log_arr = np.log(arr)
print(log_arr)  # Salida: [-inf  0.   inf]

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 1.          4.81047738 23.14069263]
[      -inf 0.45158271 1.14472989]


/tmp/ipykernel_7027/2186374687.py:18: RuntimeWarning: divide by zero encountered in log
  log_arr = np.log(arr)


* **Funciones estadísticas:**

NumPy también ofrece funciones universales para realizar cálculos estadísticos en arrays. Algunas de las funciones estadísticas más comunes son:

**np.mean():** Calcula la media de los elementos en el array.

**np.median():** Calcula la mediana de los elementos en el array.

**np.std():** Calcula la desviación estándar de los elementos en el array.

**np.min():** Encuentra el valor mínimo en el array.

**np.max():** Encuentra el valor máximo en el array.

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Media de los elementos
mean = np.mean(arr)
print(mean)  # Salida: 3.0

# Mediana de los elementos
median = np.median(arr)
print(median)  # Salida: 3.0

# Desviación estándar de los elementos
std = np.std(arr)
print(std)  # Salida: 1.4142135623730951

# Valor mínimo en el array
min_val = np.min(arr)
print(min_val)  # Salida: 1

# Valor máximo en el array
max_val = np.max(arr)
print(max_val)  # Salida: 5

3.0
3.0
1.4142135623730951
1
5


Estos son solo algunos ejemplos de las funciones universales disponibles en NumPy. Además de estas funciones, NumPy también proporciona funciones para realizar operaciones de álgebra lineal, manipulación de arrays y más. Las funciones universales de NumPy son esenciales para realizar cálculos eficientes en grandes conjuntos de datos y son una parte fundamental de la biblioteca NumPy.

## **Indexing, Slicing e Iterating**

En NumPy, el indexing, slicing e iterating son técnicas utilizadas para acceder, manipular y recorrer los elementos de un array. A continuación, te proporcionaré una explicación detallada de cada una de estas técnicas junto con ejemplos ilustrativos.

* **Indexing (indexación):**

El indexing se refiere a la forma de acceder a elementos individuales de un array utilizando índices. En NumPy, los índices se utilizan para especificar la ubicación de un elemento en un array. Los índices en NumPy comienzan en 0 y pueden ser enteros o tuplas de enteros para acceder a elementos de arrays multidimensionales.

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Acceder al primer elemento del array
print(arr[0])  # Salida: 1

# Acceder al tercer elemento del array
print(arr[2])  # Salida: 3

# Acceder al último elemento del array
print(arr[-1])  # Salida: 5

arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# Acceder al elemento en la segunda fila y primera columna
print(arr2[1, 0])  # Salida: 4

1
3
5
4


* **Slicing (rebanado):**

El slicing se utiliza para obtener una porción o subconjunto de elementos de un array. Permite especificar un rango de índices para seleccionar una parte del array. La sintaxis general para el slicing es `[inicio:fin:paso]`, donde inicio y fin son los índices de inicio y fin del subconjunto, y paso es el tamaño del salto entre elementos.

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Obtener los primeros tres elementos del array
print(arr[0:3])  # Salida: [1 2 3]

# Obtener elementos a partir del índice 2 hasta el final
print(arr[2:])  # Salida: [3 4 5]

# Obtener elementos con paso de 2
print(arr[::2])  # Salida: [1 3 5]

arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# Obtener la primera fila del array bidimensional
print(arr2[0, :])  # Salida: [1 2 3]

# Obtener la segunda columna del array bidimensional
print(arr2[:, 1])  # Salida: [2 5]

[1 2 3]
[3 4 5]
[1 3 5]
[1 2 3]
[2 5]


* **Iterating (iteración):**

La iteración se refiere a la capacidad de recorrer los elementos de un array. En NumPy, se puede utilizar un bucle for para iterar sobre los elementos de un array unidimensional. Para arrays multidimensionales, se puede utilizar el atributo `nditer()` para recorrer los elementos en un orden determinado.

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Iterar sobre los elementos de un array unidimensional
for element in arr:
    print(element)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# Iterar sobre los elementos de un array bidimensional
for row in arr2:
    for element in row:
        print(element)

1
2
3
4
5
1
2
3
4
5
6


En resumen, el indexing se utiliza para acceder a elementos individuales de un array, el slicing se utiliza para obtener subconjuntos de elementos y el iterating se utiliza para recorrer los elementos de un array. Estas técnicas son fundamentales para el manejo de arrays en NumPy y son ampliamente utilizadas en el análisis de datos y el procesamiento numérico en Python.

## **Funciones y métodos de Numpy**

NumPy es una biblioteca de Python ampliamente utilizada para el procesamiento numérico y científico. Proporciona una amplia gama de funciones y métodos que facilitan la manipulación y operaciones en arrays multidimensionales. A continuación, te proporcionaré una explicación detallada de las funciones y métodos más comunes en NumPy, junto con ejemplos ilustrativos.

**Funciones básicas:**

* **np.array():** Crea un nuevo array de NumPy.

* **np.zeros():** Crea un array de ceros.

* **np.ones():** Crea un array de unos.

* **np.arange():** Crea un array con valores espaciados uniformemente.

* **np.linspace():** Crea un array con valores espaciados de forma lineal.

* **np.random.rand():** Genera números aleatorios en un array.

Ejemplo:

In [14]:
import numpy as np

# Crear un array de NumPy
arr = np.array([1, 2, 3, 4, 5])

# Crear un array de ceros
zeros_arr = np.zeros((2, 3))  # Array de 2 filas y 3 columnas de ceros

# Crear un array de unos
ones_arr = np.ones((3, 2))  # Array de 3 filas y 2 columnas de unos

# Crear un array con valores espaciados uniformemente
range_arr = np.arange(0, 10, 2)  # Array que va desde 0 hasta 10 (exclusivo) con paso 2

# Crear un array con valores espaciados de forma lineal
linspace_arr = np.linspace(0, 1, 5)  # Array que va desde 0 hasta 1 con 5 elementos

# Generar números aleatorios en un array
random_arr = np.random.rand(3, 3)  # Array de 3x3 con valores aleatorios entre 0 y 1

* **Métodos de arrays:**

**shape:** Devuelve la forma del array (número de filas y columnas).

**reshape():** Cambia la forma del array.

**size:** Devuelve el número total de elementos en el array.

**dtype:** Devuelve el tipo de datos del array.

**min(), max(), mean(), sum():** Calculan el mínimo, máximo, media y suma de los elementos del array.

Ejemplo:

In [15]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Obtener la forma del array
print(arr.shape)  # Salida: (2, 3)

# Cambiar la forma del array
reshaped_arr = arr.reshape(3, 2)  # Array con forma (3, 2)

# Obtener el número total de elementos en el array
print(arr.size)  # Salida: 6

# Obtener el tipo de datos del array
print(arr.dtype)  # Salida: int64

# Calcular el mínimo, máximo, media y suma de los elementos del array
print(arr.min())  # Salida: 1
print(arr.max())  # Salida: 6
print(arr.mean())  # Salida: 3.5
print(arr.sum())  # Salida: 21

(2, 3)
6
int64
1
6
3.5
21


* **Funciones matemáticas:**

NumPy ofrece una amplia variedad de funciones matemáticas que se pueden aplicar a arrays, como trigonometría, exponenciales, logaritmos, redondeo, entre otros.

Ejemplo:

In [16]:
import numpy as np

arr = np.array([1, 2, 3])

# Funciones trigonométricas
print(np.sin(arr))  # Salida: [0.84147098, 0.90929743, 0.14112001]
print(np.cos(arr))  # Salida: [0.54030231, -0.41614684, -0.9899925]

# Funciones exponenciales y logarítmicas
print(np.exp(arr))  # Salida: [2.71828183, 7.3890561, 20.08553692]
print(np.log(arr))  # Salida: [0., 0.69314718, 1.09861229]

# Funciones de redondeo
print(np.round([1.3, 2.6, 3.1]))  # Salida: [1., 3., 3.]

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[1. 3. 3.]


Estas son solo algunas de las funciones y métodos más utilizados en NumPy. La biblioteca ofrece muchas más opciones y funcionalidades para realizar operaciones matemáticas y científicas en arrays multidimensionales.

## **Trucos de indexación en Numpy**

Los trucos de indexación en NumPy permiten acceder y manipular elementos en arrays de formas más avanzadas y eficientes. Estas técnicas aprovechan las capacidades de indexación y selección de NumPy para realizar operaciones complejas de una manera concisa y eficiente. A continuación, se presentan algunos de los trucos de indexación más comunes en NumPy con ejemplos ilustrativos:

* **Indexación booleana:**

La indexación booleana permite seleccionar elementos de un array basándose en una condición booleana. Se crea una máscara booleana donde se asigna `True` a los elementos que cumplan la condición y `False` a los que no. Luego, se puede utilizar la máscara para acceder a los elementos correspondientes.

Ejemplo:

In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Crear una máscara booleana
mask = arr > 2  # [False, False, True, True, True]

# Seleccionar los elementos que cumplen la condición
selected_elements = arr[mask]  # [3, 4, 5]

* **Indexación con arrays de enteros:**

La indexación con arrays de enteros permite seleccionar elementos de un array utilizando otro array de enteros como índices. Los valores del array de enteros indican los índices de los elementos que se desean seleccionar.

Ejemplo:

In [18]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Crear un array de enteros como índices
indices = np.array([1, 3])

# Seleccionar los elementos correspondientes a los índices
selected_elements = arr[indices]  # [20, 40]

* **Indexación avanzada:**

La indexación avanzada permite realizar selecciones más complejas utilizando múltiples arrays como índices. Se pueden utilizar arrays de enteros y arrays booleanos para seleccionar elementos de forma simultánea.

Ejemplo:

In [19]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6]])

# Crear arrays de enteros y booleanos como índices
row_indices = np.array([0, 2])
col_indices = np.array([1, 0])
bool_mask = np.array([True, False, True])

# Seleccionar los elementos correspondientes a los índices
selected_elements = arr[row_indices, col_indices]  # [2, 5]

# Seleccionar los elementos correspondientes a la máscara booleana
bool_selected_elements = arr[bool_mask]  # [[1, 2], [5, 6]]

Estos son solo algunos ejemplos de los trucos de indexación en NumPy. La biblioteca proporciona una amplia variedad de técnicas de indexación que permiten realizar selecciones complejas y manipular los datos de forma eficiente. La práctica y la exploración adicional de la documentación oficial de NumPy te ayudarán a dominar estas técnicas y aprovechar al máximo la potencia de indexación de NumPy.

## **Operadores de Álgebra Lineal**

Los operadores de álgebra lineal en NumPy son funciones que permiten realizar diversas operaciones matemáticas relacionadas con vectores, matrices y otros objetos algebraicos. Estas operaciones son fundamentales en el campo del álgebra lineal y se utilizan ampliamente en el procesamiento de datos, la estadística, el aprendizaje automático y muchas otras áreas de la ciencia y la ingeniería. A continuación, se presentan algunos de los operadores de álgebra lineal más comunes en NumPy con ejemplos ilustrativos:

* **Producto de matrices:**

El producto de matrices es una operación básica en álgebra lineal que implica multiplicar dos matrices. NumPy proporciona la función `np.matmul()` para calcular el producto de dos matrices.

Ejemplo:

In [20]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Calcular el producto de matrices
C = np.matmul(A, B)

print(C)
# Salida:
# [[19 22]
#  [43 50]]

[[19 22]
 [43 50]]


* **Inversa de una matriz:**

La inversa de una matriz es otra operación importante en álgebra lineal. La función `np.linalg.inv()` permite calcular la inversa de una matriz cuadrada.

Ejemplo:

In [21]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

# Calcular la inversa de la matriz
A_inv = np.linalg.inv(A)

print(A_inv)
# Salida:
# [[-2.   1. ]
#  [ 1.5 -0.5]]

[[-2.   1. ]
 [ 1.5 -0.5]]


* **Descomposición de valores singulares (SVD):**

La descomposición de valores singulares es una técnica de álgebra lineal que descompone una matriz en tres componentes principales: una matriz de valores singulares, una matriz unitaria izquierda y una matriz unitaria derecha. La función `np.linalg.svd()` permite realizar la descomposición de valores singulares.

Ejemplo:

In [22]:
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6]])

# Realizar la descomposición de valores singulares
U, S, V = np.linalg.svd(A)

print(U)
print(S)
print(V)
# Salida:
# [[-0.2298477  -0.88346102]
#  [-0.52474482 -0.24078249]
#  [-0.81964194  0.40189604]]
# [9.52551809 0.51430058]
# [[-0.61962948 -0.78489445]
#  [-0.78489445  0.61962948]]

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


Estos son solo algunos ejemplos de los operadores de álgebra lineal disponibles en NumPy. La biblioteca proporciona muchas más funciones y operaciones relacionadas con el álgebra lineal, como cálculo de determinantes, resolución de sistemas de ecuaciones lineales, autovalores y autovectores, entre otros. La práctica y la exploración adicional de la documentación oficial de NumPy te ayudarán a familiarizarte con todas las capacidades de álgebra lineal que ofrece.

## **Generación de números aleatorios en Numpy**

La generación de números aleatorios es una funcionalidad importante en NumPy que permite crear secuencias de números pseudoaleatorios. NumPy proporciona varias funciones para generar números aleatorios siguiendo diferentes distribuciones estadísticas. A continuación, se presentan algunos ejemplos de generación de números aleatorios en NumPy:

* **Generación de números aleatorios en un rango:**

La función `np.random.rand()` se utiliza para generar números aleatorios en el rango `[0, 1)` distribuidos de forma uniforme.

Ejemplo:

In [23]:
import numpy as np

# Generar un número aleatorio en el rango [0, 1)
random_num = np.random.rand()

print(random_num)
# Salida: un número aleatorio entre 0 y 1

0.42948891296663716


* **Generación de un array de números aleatorios:**

La función `np.random.rand()` también se puede utilizar para generar un array de números aleatorios especificando las dimensiones del array.

Ejemplo:

In [24]:
import numpy as np

# Generar un array de números aleatorios de forma (3, 3)
random_array = np.random.rand(3, 3)

print(random_array)
# Salida: una matriz de 3x3 con números aleatorios en el rango [0, 1)

[[0.28903345 0.5273379  0.45974973]
 [0.9264806  0.38359552 0.87619998]
 [0.57389353 0.36310487 0.13088551]]


* **Generación de números aleatorios siguiendo una distribución normal:**

La función `np.random.randn()` se utiliza para generar números aleatorios siguiendo una distribución normal estándar (media 0 y desviación estándar 1).

Ejemplo:

In [25]:
import numpy as np

# Generar un número aleatorio siguiendo una distribución normal estándar
random_num = np.random.randn()

print(random_num)
# Salida: un número aleatorio siguiendo una distribución normal estándar

0.870089791803877


* **Generación de números aleatorios enteros:**

La función `np.random.randint()` se utiliza para generar números aleatorios enteros en un rango especificado.

Ejemplo:

In [26]:
import numpy as np

# Generar un número aleatorio entero en el rango [1, 10)
random_num = np.random.randint(1, 10)

print(random_num)
# Salida: un número aleatorio entero entre 1 y 10

4


Estos son solo algunos ejemplos de generación de números aleatorios en NumPy. La biblioteca ofrece muchas más funciones y opciones para generar números aleatorios siguiendo diferentes distribuciones, establecer semillas aleatorias y generar secuencias aleatorias reproducibles. La generación de números aleatorios es útil en diversas aplicaciones, como simulaciones, generación de datos de prueba y selección aleatoria de muestras.

| **Inicio**| **Siguiente 2** |
|----------- |-------------- |
| [🏠](../../../README.md) | [⏩](./2.INTRODUCCION_A_PANDAS.ipynb)|