| **Inicio** | **atrás 22** | **Siguiente 24** |
|----------- |-------------- |---------------|
| [🏠](../../README.md) | [⏪](./22.Union_y_Separacion.ipynb)| [⏩](./24.Tipos_de_Graficas.ipynb)|

# **23. Acelera el procesamiento de datos con Funciones Universales (UFuncs) de Numpy**

## **Introducción a las funciones universales**

Las Funciones Universales (UFuncs) de Numpy son funciones que se aplican a cada elemento de un arreglo de Numpy de forma rápida y eficiente. Estas funciones incluyen operaciones matemáticas básicas, funciones trigonométricas, funciones exponenciales y logarítmicas, entre otras.

In [1]:
import numpy as np

# Crear un arreglo de Numpy unidimensional
arr = np.array([1, 2, 3, 4, 5])

# Aplicar la función cuadrado a cada elemento del arreglo
square_arr = np.square(arr)
print(square_arr)

# Aplicar la función exponencial a cada elemento del arreglo
exp_arr = np.exp(arr)
print(exp_arr)

# Aplicar la función seno a cada elemento del arreglo
sin_arr = np.sin(arr)
print(sin_arr)

[ 1  4  9 16 25]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


## **Funciones universales básicas: add, subtract, divide, multiple, power y absolute**

In [2]:
import numpy as np

# Crear dos arreglos de Numpy unidimensionales
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# Sumar los elementos de los dos arreglos
sum_arr = np.add(arr1, arr2)
print(sum_arr)

# Restar los elementos de los dos arreglos
sub_arr = np.subtract(arr2, arr1)
print(sub_arr)

# Dividir los elementos de los dos arreglos
div_arr = np.divide(arr1, arr2)
print(div_arr)

# Multiplicar los elementos de los dos arreglos
mul_arr = np.multiply(arr1, arr2)
print(mul_arr)

# Elevar los elementos de arr1 a los elementos de arr2
pow_arr = np.power(arr1, arr2)
print(pow_arr)

# Obtener el valor absoluto de los elementos de arr1
abs_arr = np.absolute(arr1)
print(abs_arr)

[ 7  9 11 13 15]
[5 5 5 5 5]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[ 6 14 24 36 50]
[      1     128    6561  262144 9765625]
[1 2 3 4 5]


## **Ejemplo de función universal para el cálculo del índice de la masa corporal**

In [3]:
import numpy as np

# Crear un arreglo de Numpy bidimensional con datos de peso (en kg) y altura (en m)
datos = np.array([[70, 1.80],
                  [80, 1.75],
                  [65, 1.68]])

# Obtener los pesos y alturas por separado
pesos = datos[:, 0]
alturas = datos[:, 1]

# Calcular el índice de masa corporal (IMC)
imc = np.divide(pesos, np.power(alturas, 2))
print(imc)

[21.60493827 26.12244898 23.03004535]


## **Comparación de tiempos de ejecución entre arrays con ufuncs y listas   tradicionales**

Las funciones universales (ufuncs) en Numpy se han optimizado para trabajar con arreglos de manera eficiente, lo que significa que en general son mucho más rápidas que las operaciones equivalentes en listas tradicionales de Python. Esto se debe a que Numpy utiliza código nativo de bajo nivel (C y Fortran) para realizar operaciones en los arreglos, mientras que Python trabaja con objetos de alto nivel.

A continuación, se muestra un ejemplo que compara los tiempos de ejecución de una operación simple de suma entre un arreglo de Numpy y una lista de Python:

In [4]:
import numpy as np
import time

# Crear un arreglo de Numpy con 1000000 elementos
a = np.random.rand(1000000)

# Crear una lista de Python con 1000000 elementos
b = list(a)

# Medir el tiempo de ejecución de la suma en Numpy
start_time = time.time()
c = a + a
print("Tiempo de ejecución con Numpy:", time.time() - start_time, "segundos")

# Medir el tiempo de ejecución de la suma en la lista de Python
start_time = time.time()
d = [i + i for i in b]
print("Tiempo de ejecución con lista de Python:", time.time() - start_time, "segundos")

Tiempo de ejecución con Numpy: 0.05339670181274414 segundos
Tiempo de ejecución con lista de Python: 0.7357568740844727 segundos


| **Inicio** | **atrás 22** | **Siguiente 24** |
|----------- |-------------- |---------------|
| [🏠](../../README.md) | [⏪](./22.Union_y_Separacion.ipynb)| [⏩](./24.Tipos_de_Graficas.ipynb)|